// data.ts — Dummy data for Work Schedule (Scheduler) feature
import type {
  AssignedEmployee,
  ExecutionHistoryStats,
  ExecutionRecord,
  ScheduleExecutionLog,
  ScheduledJob,
  SchedulerManagementStats,
  SchedulerModule,
  WorkSchedule,
  WorkScheduleStats,
} from './types'

export const shiftTypeLabels: Record<string, string> = {
  regular: 'Regular',
  shifting: 'Shifting',
  split: 'Jam Penggal',
}

export const shiftTypeColors: Record<string, string> = {
  regular: 'bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300',
  shifting: 'bg-violet-100 text-violet-700 dark:bg-violet-900/40 dark:text-violet-300',
  split: 'bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300',
}

export const workDayLabels: Record<string, string> = {
  monday: 'Sen',
  tuesday: 'Sel',
  wednesday: 'Rab',
  thursday: 'Kam',
  friday: 'Jum',
  saturday: 'Sab',
  sunday: 'Min',
}

export const allWorkDays = [
  'monday',
  'tuesday',
  'wednesday',
  'thursday',
  'friday',
  'saturday',
  'sunday',
] as const

export const dummyWorkSchedules: WorkSchedule[] = [
  {
    id: 'ws-001',
    code: 'WS-REG-01',
    name: 'Jam Kerja Reguler',
    description: 'Jadwal kerja standar untuk karyawan kantor, Senin s.d. Jumat',
    type: 'regular',
    sessions: [{ label: 'Kerja', startTime: '08:00', endTime: '17:00' }],
    workDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
    gracePeriodMinutes: 15,
    breakDurationMinutes: 60,
    overtimeThresholdMinutes: 30,
    status: 'active',
    totalEmployees: 128,
    createdAt: '2025-01-10',
    updatedAt: '2026-08-15',
    createdBy: 'Admin HR',
  },
  {
    id: 'ws-002',
    code: 'WS-SHF-01',
    name: 'Shift Pagi',
    description: 'Shift pagi untuk operasional pabrik dan produksi',
    type: 'shifting',
    sessions: [{ label: 'Pagi', startTime: '06:00', endTime: '14:00' }],
    workDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'],
    gracePeriodMinutes: 10,
    breakDurationMinutes: 30,
    overtimeThresholdMinutes: 0,
    status: 'active',
    totalEmployees: 45,
    createdAt: '2025-01-15',
    updatedAt: '2026-07-20',
    createdBy: 'Admin Produksi',
  },
  {
    id: 'ws-003',
    code: 'WS-SHF-02',
    name: 'Shift Siang',
    description: 'Shift siang untuk operasional pabrik dan produksi',
    type: 'shifting',
    sessions: [{ label: 'Siang', startTime: '14:00', endTime: '22:00' }],
    workDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'],
    gracePeriodMinutes: 10,
    breakDurationMinutes: 30,
    overtimeThresholdMinutes: 0,
    status: 'active',
    totalEmployees: 42,
    createdAt: '2025-01-15',
    updatedAt: '2026-07-20',
    createdBy: 'Admin Produksi',
  },
  {
    id: 'ws-004',
    code: 'WS-SHF-03',
    name: 'Shift Malam',
    description: 'Shift malam untuk operasional pabrik, lintas tengah malam',
    type: 'shifting',
    sessions: [{ label: 'Malam', startTime: '22:00', endTime: '06:00', crossMidnight: true }],
    workDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'],
    gracePeriodMinutes: 10,
    breakDurationMinutes: 30,
    overtimeThresholdMinutes: 0,
    status: 'active',
    totalEmployees: 38,
    createdAt: '2025-01-15',
    updatedAt: '2026-07-20',
    createdBy: 'Admin Produksi',
  },
  {
    id: 'ws-005',
    code: 'WS-SPL-01',
    name: 'Jam Penggal Retail',
    description: 'Jadwal khusus retail: pagi dan sore terpisah dengan jeda istirahat panjang',
    type: 'split',
    sessions: [
      { label: 'Sesi Pagi', startTime: '08:00', endTime: '12:00' },
      { label: 'Sesi Sore', startTime: '16:00', endTime: '21:00' },
    ],
    workDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    gracePeriodMinutes: 15,
    breakDurationMinutes: 0,
    overtimeThresholdMinutes: 30,
    status: 'active',
    totalEmployees: 22,
    createdAt: '2025-02-01',
    updatedAt: '2026-06-10',
    createdBy: 'Admin HR',
  },
  {
    id: 'ws-006',
    code: 'WS-REG-02',
    name: 'Jam Kerja Fleksibel',
    description: 'Jadwal kerja fleksibel untuk tim engineering, dapat mulai antara 08.00–10.00',
    type: 'regular',
    sessions: [{ label: 'Kerja', startTime: '09:00', endTime: '18:00' }],
    workDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
    gracePeriodMinutes: 60,
    breakDurationMinutes: 60,
    overtimeThresholdMinutes: 60,
    status: 'active',
    totalEmployees: 35,
    createdAt: '2025-03-01',
    updatedAt: '2026-09-01',
    createdBy: 'Admin HR',
  },
  {
    id: 'ws-007',
    code: 'WS-SPL-02',
    name: 'Jam Penggal Security',
    description: 'Jadwal petugas keamanan dengan dua sesi jaga: dini hari dan sore malam',
    type: 'split',
    sessions: [
      { label: 'Jaga Dini Hari', startTime: '00:00', endTime: '06:00' },
      { label: 'Jaga Sore-Malam', startTime: '18:00', endTime: '24:00' },
    ],
    workDays: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
    gracePeriodMinutes: 5,
    breakDurationMinutes: 0,
    overtimeThresholdMinutes: 0,
    status: 'inactive',
    totalEmployees: 0,
    createdAt: '2025-04-10',
    updatedAt: '2026-05-01',
    createdBy: 'Admin GA',
  },
  {
    id: 'ws-008',
    code: 'WS-REG-03',
    name: 'Jam Kerja Sabtu',
    description: 'Jadwal kerja untuk Sabtu setengah hari, tim operasional',
    type: 'regular',
    sessions: [{ label: 'Kerja', startTime: '08:00', endTime: '13:00' }],
    workDays: ['saturday'],
    gracePeriodMinutes: 15,
    breakDurationMinutes: 0,
    overtimeThresholdMinutes: 30,
    status: 'inactive',
    totalEmployees: 0,
    createdAt: '2025-05-01',
    updatedAt: '2026-08-01',
    createdBy: 'Admin HR',
  },
]

export const dummyWorkScheduleStats: WorkScheduleStats = {
  total: dummyWorkSchedules.length,
  active: dummyWorkSchedules.filter((s) => s.status === 'active').length,
  regular: dummyWorkSchedules.filter((s) => s.type === 'regular').length,
  shifting: dummyWorkSchedules.filter((s) => s.type === 'shifting').length,
  split: dummyWorkSchedules.filter((s) => s.type === 'split').length,
}

export const dummyAssignedEmployees: Record<string, AssignedEmployee[]> = {
  'ws-001': [
    {
      id: 'emp-01',
      name: 'Budi Pratama',
      nik: 'EMP-2023-001',
      department: 'Teknologi Informasi',
      position: 'Senior Software Engineer',
      assignedAt: '2025-01-10',
    },
    {
      id: 'emp-02',
      name: 'Siti Rahmawati',
      nik: 'EMP-2023-002',
      department: 'Human Resources',
      position: 'HR Specialist',
      assignedAt: '2025-01-12',
    },
    {
      id: 'emp-03',
      name: 'Ahmad Fauzi',
      nik: 'EMP-2023-005',
      department: 'Keuangan & Akuntansi',
      position: 'Accounting Officer',
      assignedAt: '2025-02-01',
    },
    {
      id: 'emp-04',
      name: 'Dewi Lestari',
      nik: 'EMP-2023-008',
      department: 'Pemasaran & Sales',
      position: 'Product Marketing Lead',
      assignedAt: '2025-02-15',
    },
    {
      id: 'emp-05',
      name: 'Rian Saputra',
      nik: 'EMP-2023-012',
      department: 'Teknologi Informasi',
      position: 'Frontend Developer',
      assignedAt: '2025-03-01',
    },
  ],
  'ws-002': [
    {
      id: 'emp-06',
      name: 'Joko Widodo Susanto',
      nik: 'EMP-2023-040',
      department: 'Operasional Pabrik',
      position: 'Operator Mesin A',
      assignedAt: '2025-01-15',
    },
    {
      id: 'emp-07',
      name: 'Andi Firmansyah',
      nik: 'EMP-2023-041',
      department: 'Operasional Pabrik',
      position: 'Teknisi Maintenance',
      assignedAt: '2025-01-16',
    },
  ],
}

export const dummyExecutionLogs: Record<string, ScheduleExecutionLog[]> = {
  'ws-001': [
    {
      id: 'log-01',
      scheduleId: 'ws-001',
      executedAt: '2026-09-15 00:00:15',
      status: 'success',
      affectedEmployees: 128,
      triggerType: 'scheduled',
      message: 'Penjadwalan harian otomatis berhasil diterapkan untuk 128 karyawan.',
    },
    {
      id: 'log-02',
      scheduleId: 'ws-001',
      executedAt: '2026-09-14 00:00:12',
      status: 'success',
      affectedEmployees: 128,
      triggerType: 'scheduled',
      message: 'Sinkronisasi roster harian berhasil tanpa konflik.',
    },
    {
      id: 'log-03',
      scheduleId: 'ws-001',
      executedAt: '2026-09-10 14:22:00',
      status: 'warning',
      affectedEmployees: 3,
      triggerType: 'manual',
      message: 'Pembaruan manual jam kerja: 3 karyawan memiliki jadwal khusus terpisah.',
    },
  ],
}

// ─── Scheduler Management Dummy Data ──────────────────────────────────────────

export const moduleBadgeColors: Record<SchedulerModule, string> = {
  Attendance: 'bg-blue-50 text-blue-700 border-blue-200 dark:bg-blue-950/40 dark:text-blue-300 dark:border-blue-800/50',
  Leave: 'bg-purple-50 text-purple-700 border-purple-200 dark:bg-purple-950/40 dark:text-purple-300 dark:border-purple-800/50',
  Payroll: 'bg-emerald-50 text-emerald-700 border-emerald-200 dark:bg-emerald-950/40 dark:text-emerald-300 dark:border-emerald-800/50',
  Employee: 'bg-amber-50 text-amber-700 border-amber-200 dark:bg-amber-950/40 dark:text-amber-300 dark:border-amber-800/50',
  Workflow: 'bg-sky-50 text-sky-700 border-sky-200 dark:bg-sky-950/40 dark:text-sky-300 dark:border-sky-800/50',
  System: 'bg-rose-50 text-rose-700 border-rose-200 dark:bg-rose-950/40 dark:text-rose-300 dark:border-rose-800/50',
  Overtime: 'bg-indigo-50 text-indigo-700 border-indigo-200 dark:bg-indigo-950/40 dark:text-indigo-300 dark:border-indigo-800/50',
  Claim: 'bg-teal-50 text-teal-700 border-teal-200 dark:bg-teal-950/40 dark:text-teal-300 dark:border-teal-800/50',
  'Business Trip': 'bg-violet-50 text-violet-700 border-violet-200 dark:bg-violet-950/40 dark:text-violet-300 dark:border-violet-800/50',
}

export const defaultScheduledJobs: ScheduledJob[] = [
  {
    id: 'job-01',
    name: 'Daily Attendance Processing',
    module: 'Attendance',
    frequency: 'Daily · 01:00',
    lastRun: '05 Sep · 01:02',
    nextRun: '06 Sep · 01:00',
    status: 'active',
    result: 'success',
    description: 'Memproses rekonsiliasi presensi harian seluruh karyawan aktif.',
  },
  {
    id: 'job-02',
    name: 'Attendance Device Sync',
    module: 'Attendance',
    frequency: 'Every 15 min',
    lastRun: '05 Sep · 20:30',
    nextRun: '05 Sep · 20:45',
    status: 'running',
    result: 'running',
    description: 'Sinkronisasi data log clock-in/out dari mesin fingerprint & face recognition.',
  },
  {
    id: 'job-03',
    name: 'Leave Balance Accrual',
    module: 'Leave',
    frequency: 'Monthly',
    lastRun: '01 Sep · 00:04',
    nextRun: '01 Oct · 00:00',
    status: 'active',
    result: 'success',
    description: 'Penambahan saldo cuti tahunan otomatis awal bulan.',
  },
  {
    id: 'job-04',
    name: 'Payroll Period Generation',
    module: 'Payroll',
    frequency: 'Monthly',
    lastRun: '25 Aug · 20:03',
    nextRun: '25 Sep · 20:00',
    status: 'active',
    result: 'success',
    description: 'Generate draf periode payroll bulanan dan kalkulasi komponen gaji pokok.',
  },
  {
    id: 'job-05',
    name: 'Contract Expiry Reminder',
    module: 'Employee',
    frequency: 'Daily · 08:00',
    lastRun: '05 Sep · 08:01',
    nextRun: '06 Sep · 08:00',
    status: 'active',
    result: 'success',
    description: 'Kirim notifikasi email kontrak karyawan yang akan berakhir dalam 30 & 60 hari.',
  },
  {
    id: 'job-06',
    name: 'Pending Approval Reminder',
    module: 'Workflow',
    frequency: 'Daily · 09:00',
    lastRun: '05 Sep · 09:00',
    nextRun: '06 Sep · 09:00',
    status: 'inactive',
    result: 'idle',
    description: 'Kirim blast reminder kepada approver yang memiliki antrean approval tertunda.',
  },
  {
    id: 'job-07',
    name: 'Failed Job Retry',
    module: 'System',
    frequency: 'Hourly',
    lastRun: '05 Sep · 20:00',
    nextRun: '05 Sep · 21:00',
    status: 'failed',
    result: 'failed',
    description: 'Mencoba kembali eksekusi background job yang mengalami kegagalan.',
    errorLog: {
      message: 'Connection timeout to biometric gateway 192.168.10.25: Connection refused after 3 retries',
      timestamp: '05 Sep 2026 20:00:15',
      code: 'ERR_GATEWAY_TIMEOUT',
      details: 'Failed to establish TCP socket handshake on port 4370. Device might be offline or undergoing maintenance.',
    },
  },
  {
    id: 'job-08',
    name: 'Overtime Auto-Calculation',
    module: 'Overtime',
    frequency: 'Daily · 23:00',
    lastRun: '05 Sep · 23:05',
    nextRun: '06 Sep · 23:00',
    status: 'active',
    result: 'success',
    description: 'Kalkulasi lembur otomatis berdasarkan clock-out aktual vs jam kerja terjadwal.',
  },
  {
    id: 'job-09',
    name: 'Claim Reimbursement Sync',
    module: 'Claim',
    frequency: 'Weekly · Mon',
    lastRun: '01 Sep · 07:00',
    nextRun: '08 Sep · 07:00',
    status: 'active',
    result: 'success',
    description: 'Sinkronisasi status klaim yang disetujui ke antrean transfer finance.',
  },
  {
    id: 'job-10',
    name: 'Business Trip Allowance Processing',
    module: 'Business Trip',
    frequency: 'Daily · 06:00',
    lastRun: '05 Sep · 06:02',
    nextRun: '06 Sep · 06:00',
    status: 'active',
    result: 'success',
    description: 'Hitung uang harian perjalanan dinas aktif.',
  },
  {
    id: 'job-11',
    name: 'Audit Trail Archival',
    module: 'System',
    frequency: 'Monthly',
    lastRun: '01 Sep · 02:00',
    nextRun: '01 Oct · 02:00',
    status: 'active',
    result: 'success',
    description: 'Arsipkan log aktivitas sistem yang berusia lebih dari 90 hari ke storage dingin.',
  },
  {
    id: 'job-12',
    name: 'Tax PPh 21 Calculation',
    module: 'Payroll',
    frequency: 'Monthly',
    lastRun: '25 Aug · 21:00',
    nextRun: '25 Sep · 21:00',
    status: 'active',
    result: 'success',
    description: 'Kalkulasi estimasi potongan PPh 21 metode TER bulanan.',
  },
  {
    id: 'job-13',
    name: 'Employee Birthday Notification',
    module: 'Employee',
    frequency: 'Daily · 07:30',
    lastRun: '05 Sep · 07:30',
    nextRun: '06 Sep · 07:30',
    status: 'active',
    result: 'success',
    description: 'Kirim ucapan ulang tahun otomatis ke feed pengumuman dan email karyawan.',
  },
  {
    id: 'job-14',
    name: 'Shift Schedule Auto-Publish',
    module: 'Attendance',
    frequency: 'Weekly · Sun',
    lastRun: '31 Aug · 23:00',
    nextRun: '07 Sep · 23:00',
    status: 'active',
    result: 'success',
    description: 'Publikasi jadwal shift mingguan yang sudah di-approve oleh admin.',
  },
  {
    id: 'job-15',
    name: 'BPJS Ketenagakerjaan Sync',
    module: 'Payroll',
    frequency: 'Monthly',
    lastRun: '20 Aug · 03:00',
    nextRun: '20 Sep · 03:00',
    status: 'active',
    result: 'success',
    description: 'Sinkronisasi iuran JKK, JKM, JHT, dan JP dengan data upah terkini.',
  },
  {
    id: 'job-16',
    name: 'Probation Review Reminder',
    module: 'Employee',
    frequency: 'Daily · 08:30',
    lastRun: '05 Sep · 08:30',
    nextRun: '06 Sep · 08:30',
    status: 'active',
    result: 'success',
    description: 'Notifikasi evaluasi masa percobaan 2 minggu sebelum selesai.',
  },
  {
    id: 'job-17',
    name: 'Database Index Optimization',
    module: 'System',
    frequency: 'Weekly · Sun',
    lastRun: '31 Aug · 02:00',
    nextRun: '07 Sep · 02:00',
    status: 'active',
    result: 'success',
    description: 'Maintenance indeks database dan query vacuum.',
  },
  {
    id: 'job-18',
    name: 'Approval Escalation Trigger',
    module: 'Workflow',
    frequency: 'Every 6 hours',
    lastRun: '05 Sep · 18:00',
    nextRun: '06 Sep · 00:00',
    status: 'active',
    result: 'success',
    description: 'Eskalasi pengajuan yang melebihi batas SLA ke atasan tingkat berikutnya.',
  },
  {
    id: 'job-19',
    name: 'Face Recognition Model Sync',
    module: 'Attendance',
    frequency: 'Daily · 02:00',
    lastRun: '05 Sep · 02:00',
    nextRun: '06 Sep · 02:00',
    status: 'failed',
    result: 'failed',
    description: 'Update model embedding wajah karyawan ke terminal absensi.',
    errorLog: {
      message: 'SSL certificate validation failed on edge terminal #4 (Gedung B Lt. 2)',
      timestamp: '05 Sep 2026 02:00:10',
      code: 'ERR_SSL_CERT_UNTRUSTED',
      details: 'Edge terminal device certificate expired. Renew local trust store on terminal device.',
    },
  },
  {
    id: 'job-20',
    name: 'Payroll Bank Transfer Generation',
    module: 'Payroll',
    frequency: 'Monthly',
    lastRun: '26 Aug · 10:00',
    nextRun: '26 Sep · 10:00',
    status: 'active',
    result: 'success',
    description: 'Buat file batch payroll transfer (BCA, Mandiri, BNI).',
  },
  {
    id: 'job-21',
    name: 'Annual Leave Reset Policy',
    module: 'Leave',
    frequency: 'Yearly',
    lastRun: '01 Jan · 00:00',
    nextRun: '01 Jan · 00:00',
    status: 'inactive',
    result: 'idle',
    description: 'Hanguskan sisa cuti tahun lalu yang melewati batas masa tenggang.',
  },
  {
    id: 'job-22',
    name: 'Session Cleanup Daemon',
    module: 'System',
    frequency: 'Hourly',
    lastRun: '05 Sep · 20:00',
    nextRun: '05 Sep · 21:00',
    status: 'active',
    result: 'success',
    description: 'Hapus sesi token login yang kedaluwarsa.',
  },
  {
    id: 'job-23',
    name: 'Travel Expense Currency Rates Sync',
    module: 'Business Trip',
    frequency: 'Daily · 05:00',
    lastRun: '05 Sep · 05:01',
    nextRun: '06 Sep · 05:00',
    status: 'active',
    result: 'success',
    description: 'Perbarui kurs valuta asing Bank Indonesia untuk klaim luar negeri.',
  },
  {
    id: 'job-24',
    name: 'Overtime Meal Allowance Validator',
    module: 'Overtime',
    frequency: 'Daily · 23:30',
    lastRun: '05 Sep · 23:30',
    nextRun: '06 Sep · 23:30',
    status: 'active',
    result: 'success',
    description: 'Verifikasi kelayakan uang makan lembur di atas 3 jam.',
  },
  {
    id: 'job-25',
    name: 'Leave Cancellation Expired Cleaner',
    module: 'Leave',
    frequency: 'Daily · 00:30',
    lastRun: '05 Sep · 00:30',
    nextRun: '06 Sep · 00:30',
    status: 'active',
    result: 'success',
    description: 'Bersihkan draf pembatalan cuti yang tidak disubmit.',
  },
  {
    id: 'job-26',
    name: 'Notification Queue Dispatcher',
    module: 'System',
    frequency: 'Every 5 min',
    lastRun: '05 Sep · 20:40',
    nextRun: '05 Sep · 20:45',
    status: 'active',
    result: 'success',
    description: 'Kirim notifikasi push dan WhatsApp gateway dari antrean.',
  },
]

export const defaultSchedulerManagementStats: SchedulerManagementStats = {
  totalJobs: 26,
  totalModules: 12,
  active: 22,
  activePercentage: 84.6,
  running: 1,
  runningLabel: 'Device sync',
  failed: 2,
  failedLabel: 'Needs attention',
}

export const defaultExecutionHistoryStats: ExecutionHistoryStats = {
  totalRuns: 42,
  successRate: 95.2,
  avgDuration: '1m 49s',
  failed: 2,
}

export const dummyExecutionRecords: ExecutionRecord[] = [
  {
    runId: 'EXE-20260905-0102',
    schedulerId: 'job-01',
    schedulerName: 'Daily Attendance Processing',
    module: 'Attendance',
    trigger: 'Scheduled',
    startedAt: '05 Sep 2026 · 01:02:03',
    finishedAt: '05 Sep 2026 · 01:03:51',
    startedFormatted: '05 Sep · 01:02',
    duration: '1m 48s',
    result: 'Success',
    totalRecords: 1248,
    processed: 1248,
    succeeded: 1248,
    skipped: 0,
    failed: 0,
    remaining: 0,
    warnings: 0,
    timeline: [
      { time: '01:02:03', title: 'Job queued', color: 'blue' },
      { time: '01:02:04', title: 'Execution started', color: 'blue' },
      { time: '01:02:06', title: 'Loaded 1,248 attendance records', color: 'blue' },
      { time: '01:02:28', title: 'Processing attendance records', color: 'purple' },
      { time: '01:03:49', title: '1,248 records processed', color: 'green' },
      { time: '01:03:51', title: 'Execution completed', color: 'green' },
    ],
    logs: [
      { time: '01:02:04', level: 'INFO', message: 'Attendance processing started' },
      { time: '01:02:06', level: 'INFO', message: 'Found 1,248 employee records' },
      { time: '01:02:28', level: 'INFO', message: 'Processing attendance records' },
      { time: '01:03:49', level: 'INFO', message: '1,248 records processed successfully' },
      { time: '01:03:51', level: 'INFO', message: 'Job completed' },
    ],
  },
  {
    runId: 'EXE-20260904-0101',
    schedulerId: 'job-01',
    schedulerName: 'Daily Attendance Processing',
    module: 'Attendance',
    trigger: 'Scheduled',
    startedAt: '04 Sep 2026 · 01:01:02',
    finishedAt: '04 Sep 2026 · 01:02:53',
    startedFormatted: '04 Sep · 01:01',
    duration: '1m 51s',
    result: 'Success',
    totalRecords: 1244,
    processed: 1244,
    succeeded: 1244,
    skipped: 0,
    failed: 0,
    remaining: 0,
    warnings: 0,
    timeline: [
      { time: '01:01:02', title: 'Job queued', color: 'blue' },
      { time: '01:01:03', title: 'Execution started', color: 'blue' },
      { time: '01:01:05', title: 'Loaded 1,244 attendance records', color: 'blue' },
      { time: '01:01:25', title: 'Processing attendance records', color: 'purple' },
      { time: '01:02:50', title: '1,244 records processed', color: 'green' },
      { time: '01:02:53', title: 'Execution completed', color: 'green' },
    ],
    logs: [
      { time: '01:01:03', level: 'INFO', message: 'Attendance processing started' },
      { time: '01:01:05', level: 'INFO', message: 'Found 1,244 employee records' },
      { time: '01:02:53', level: 'INFO', message: 'Job completed' },
    ],
  },
  {
    runId: 'EXE-20260903-2044',
    schedulerId: 'job-01',
    schedulerName: 'Daily Attendance Processing',
    module: 'Attendance',
    trigger: 'Manual',
    startedAt: '03 Sep 2026 · 20:44:00',
    finishedAt: '03 Sep 2026 · 20:45:52',
    startedFormatted: '03 Sep · 20:44',
    duration: '1m 52s',
    result: 'Success',
    totalRecords: 1241,
    processed: 1241,
    succeeded: 1241,
    skipped: 0,
    failed: 0,
    remaining: 0,
    warnings: 0,
    timeline: [
      { time: '20:44:00', title: 'Manual trigger received', color: 'blue' },
      { time: '20:44:02', title: 'Execution started', color: 'blue' },
      { time: '20:45:50', title: '1,241 records processed', color: 'green' },
      { time: '20:45:52', title: 'Execution completed', color: 'green' },
    ],
    logs: [
      { time: '20:44:00', level: 'INFO', message: 'Manual run initiated by Super Admin' },
      { time: '20:45:52', level: 'INFO', message: 'Job completed successfully' },
    ],
  },
  {
    runId: 'EXE-20260903-0100',
    schedulerId: 'job-01',
    schedulerName: 'Daily Attendance Processing',
    module: 'Attendance',
    trigger: 'Scheduled',
    startedAt: '03 Sep 2026 · 01:00:02',
    finishedAt: '03 Sep 2026 · 01:02:12',
    startedFormatted: '03 Sep · 01:00',
    duration: '2m 10s',
    result: 'Failed',
    totalRecords: 1241,
    processed: 802,
    succeeded: 801,
    skipped: 0,
    failed: 1,
    remaining: 439,
    warnings: 6,
    bannerError:
      'ATTENDANCE_PROCESSING_ERROR · Failed while processing employee attendance record EMP-01842.',
    timeline: [
      { time: '01:00:02', title: 'Job queued', color: 'blue' },
      { time: '01:00:03', title: 'Execution started', color: 'blue' },
      { time: '01:00:08', title: 'Loaded 1,241 attendance records', color: 'blue' },
      { time: '01:01:44', title: 'Processing employee EMP-01842', color: 'amber' },
      { time: '01:02:12', title: 'Execution failed', color: 'red' },
    ],
    logs: [
      { time: '01:00:03', level: 'INFO', message: 'Attendance processing started' },
      { time: '01:00:08', level: 'INFO', message: 'Loaded 1,241 attendance records' },
      { time: '01:01:44', level: 'WARN', message: 'Warning at employee EMP-01842: shift missing' },
      { time: '01:02:12', level: 'ERROR', message: 'AttendanceCalculationException: Unable to resolve work pattern for employee batch 17' },
    ],
    errorContext: {
      code: 'ATTENDANCE_PROCESSING_ERROR',
      errorCodeShort: 'ATT-CALC-500',
      failedStep: 'Calculate status',
      attempt: '3 of 3',
      employee: 'EMP-01842 - Andi Pratama',
      recordDate: '03 Sep 2026',
      errorMessage:
        'Unable to calculate attendance because shift assignment was not found for the employee.',
      suggestedCheck: 'verify shift assignment and rerun this execution.',
      stackContext: [
        'AttendanceService.calculateStatus()',
        'WorkPatternResolver.resolve()',
        'Employee batch: 17',
        'Company timezone: Asia/Jakarta',
        'Retry attempt: 3/3',
      ],
    },
  },
  {
    runId: 'EXE-20260902-0102',
    schedulerId: 'job-01',
    schedulerName: 'Daily Attendance Processing',
    module: 'Attendance',
    trigger: 'Scheduled',
    startedAt: '02 Sep 2026 · 01:02:00',
    finishedAt: '02 Sep 2026 · 01:03:46',
    startedFormatted: '02 Sep · 01:02',
    duration: '1m 46s',
    result: 'Success',
    totalRecords: 1239,
    processed: 1239,
    succeeded: 1239,
    skipped: 0,
    failed: 0,
    remaining: 0,
    warnings: 0,
    timeline: [
      { time: '01:02:00', title: 'Job queued', color: 'blue' },
      { time: '01:02:02', title: 'Execution started', color: 'blue' },
      { time: '01:03:46', title: 'Execution completed', color: 'green' },
    ],
    logs: [
      { time: '01:02:02', level: 'INFO', message: 'Attendance processing started' },
      { time: '01:03:46', level: 'INFO', message: '1,239 records processed successfully' },
    ],
  },
  {
    runId: 'EXE-20260901-0101',
    schedulerId: 'job-01',
    schedulerName: 'Daily Attendance Processing',
    module: 'Attendance',
    trigger: 'Scheduled',
    startedAt: '01 Sep 2026 · 01:01:00',
    finishedAt: '01 Sep 2026 · 01:02:50',
    startedFormatted: '01 Sep · 01:01',
    duration: '1m 50s',
    result: 'Success',
    totalRecords: 1236,
    processed: 1236,
    succeeded: 1236,
    skipped: 0,
    failed: 0,
    remaining: 0,
    warnings: 0,
    timeline: [
      { time: '01:01:00', title: 'Job queued', color: 'blue' },
      { time: '01:01:02', title: 'Execution started', color: 'blue' },
      { time: '01:02:50', title: 'Execution completed', color: 'green' },
    ],
    logs: [
      { time: '01:01:02', level: 'INFO', message: 'Attendance processing started' },
      { time: '01:02:50', level: 'INFO', message: '1,236 records processed successfully' },
    ],
  },
]


