import type { ApprovalRequest } from './types'

export const dummyApprovalRequests: ApprovalRequest[] = [
  {
    id: 'req-001',
    employeeName: 'Rina Marlina',
    department: 'Engineering',
    position: 'Software Engineer',
    requestType: 'leave',
    requestDate: '2025-06-12',
    details: 'Cuti Tahunan — 3 Hari (15 - 17 Jun 2025)',
    status: 'pending',
    currentLevel: 2,
    totalLevels: 3,
    workflowName: 'Leave Approval',
    days: 3,
    reason: 'Keperluan keluarga di luar kota',
    timeline: [
      {
        level: 1,
        name: 'Direct Manager',
        approverName: 'Budi Santoso',
        status: 'approved',
        approvedAt: '2025-06-12 10:30',
        note: 'Silakan berkoordinasi dengan tim untuk serah terima pekerjaan.',
      },
      {
        level: 2,
        name: 'Department Head',
        approverName: 'Dewi Rahayu (Anda)',
        status: 'pending',
      },
      {
        level: 3,
        name: 'HR Manager',
        approverName: 'Ahmad Fauzi',
        status: 'waiting',
      },
    ],
  },
  {
    id: 'req-002',
    employeeName: 'Wahyu Prasetyo',
    department: 'Engineering',
    position: 'Backend Developer',
    requestType: 'overtime',
    requestDate: '2025-06-13',
    details: 'Lembur Hari Kerja — 4 Jam',
    status: 'pending',
    currentLevel: 1,
    totalLevels: 2,
    workflowName: 'Overtime Approval',
    days: 4,
    reason: 'Deployment production bug fixing & monitoring',
    timeline: [
      {
        level: 1,
        name: 'Direct Manager',
        approverName: 'Budi Santoso (Anda)',
        status: 'pending',
      },
      {
        level: 2,
        name: 'Department Head',
        approverName: 'Dewi Rahayu',
        status: 'waiting',
      },
    ],
  },
  {
    id: 'req-003',
    employeeName: 'Siti Rahayu',
    department: 'Finance',
    position: 'Finance Analyst',
    requestType: 'reimbursement',
    requestDate: '2025-06-11',
    details: 'Klaim Reimburse — Rp 750,000',
    status: 'pending',
    currentLevel: 3,
    totalLevels: 4,
    workflowName: 'Reimbursement Approval',
    amount: 750000,
    reason: 'Beli buku referensi analisis finansial perusahaan & langganan software',
    attachmentUrl: '/assets/receipt-dummy.jpg',
    timeline: [
      {
        level: 1,
        name: 'Direct Manager',
        approverName: 'Hendra Wijaya',
        status: 'approved',
        approvedAt: '2025-06-11 14:15',
        note: 'Approved for finance analysis book.',
      },
      {
        level: 2,
        name: 'Department Head',
        approverName: 'Diana Lestari',
        status: 'approved',
        approvedAt: '2025-06-12 09:10',
        note: 'Sesuai dengan budget departemen Finance.',
      },
      {
        level: 3,
        name: 'Finance Manager',
        approverName: 'Yuni Astuti (Anda)',
        status: 'pending',
      },
      {
        level: 4,
        name: 'Director',
        approverName: 'Hendra Gunawan',
        status: 'waiting',
      },
    ],
  },
  {
    id: 'req-004',
    employeeName: 'Dian Kurniawan',
    department: 'Marketing',
    position: 'Marketing Specialist',
    requestType: 'leave',
    requestDate: '2025-06-10',
    details: 'Cuti Sakit — 2 Hari (11 - 12 Jun 2025)',
    status: 'approved',
    currentLevel: 2,
    totalLevels: 2,
    workflowName: 'Leave Approval Short',
    days: 2,
    reason: 'Sakit demam berdarah (surat dokter terlampir)',
    attachmentUrl: '/assets/doctor-note-dummy.pdf',
    timeline: [
      {
        level: 1,
        name: 'Direct Manager',
        approverName: 'Diana Lestari',
        status: 'approved',
        approvedAt: '2025-06-10 11:00',
        note: 'GWS Dian. Cepat sembuh.',
      },
      {
        level: 2,
        name: 'HR Specialist',
        approverName: 'Ahmad Fauzi (Anda)',
        status: 'approved',
        approvedAt: '2025-06-10 13:40',
        note: 'Surat dokter terlampir dan valid.',
      },
    ],
  },
  {
    id: 'req-005',
    employeeName: 'Annisa Fitri',
    department: 'HR',
    position: 'HR Generalist',
    requestType: 'loan',
    requestDate: '2025-06-08',
    details: 'Pengajuan Pinjaman Karyawan — Rp 5,000,000',
    status: 'pending',
    currentLevel: 1,
    totalLevels: 3,
    workflowName: 'Loan Request',
    amount: 5000000,
    reason: 'Biaya pendaftaran sekolah anak masuk SD',
    timeline: [
      {
        level: 1,
        name: 'Direct Manager',
        approverName: 'Ahmad Fauzi (Anda)',
        status: 'pending',
      },
      {
        level: 2,
        name: 'Finance Specialist',
        approverName: 'Yuni Astuti',
        status: 'waiting',
      },
      {
        level: 3,
        name: 'Director',
        approverName: 'Hendra Gunawan',
        status: 'waiting',
      },
    ],
  },
  {
    id: 'req-006',
    employeeName: 'Budi Santoso',
    department: 'Operations',
    position: 'Operations Manager',
    requestType: 'leave',
    requestDate: '2025-06-09',
    details: 'Cuti Tahunan — 5 Hari (15 - 19 Jun 2025)',
    status: 'pending',
    currentLevel: 1,
    totalLevels: 2,
    workflowName: 'Leave Approval Short',
    days: 5,
    reason: 'Acara pernikahan adik kandung',
    timeline: [
      {
        level: 1,
        name: 'Department Head',
        approverName: 'Diana Lestari (Anda)',
        status: 'pending',
      },
      {
        level: 2,
        name: 'Director',
        approverName: 'Hendra Gunawan',
        status: 'waiting',
      },
    ],
  },
  {
    id: 'req-007',
    employeeName: 'Dewi Rahayu',
    department: 'Product',
    position: 'Product Owner',
    requestType: 'reimbursement',
    requestDate: '2025-06-07',
    details: 'Reimburse Transport Dinas — Rp 350,000',
    status: 'pending',
    currentLevel: 1,
    totalLevels: 2,
    workflowName: 'Reimbursement Approval',
    amount: 350000,
    reason: 'Taksimeter perjalanan dinas bertemu partner eksternal',
    timeline: [
      {
        level: 1,
        name: 'Direct Manager',
        approverName: 'Ahmad Fauzi (Anda)',
        status: 'pending',
      },
      {
        level: 2,
        name: 'Finance Specialist',
        approverName: 'Yuni Astuti',
        status: 'waiting',
      },
    ],
  },
  {
    id: 'req-008',
    employeeName: 'Hendra Wijaya',
    department: 'Sales',
    position: 'Account Executive',
    requestType: 'loan',
    requestDate: '2025-06-06',
    details: 'Pinjaman Renovasi Rumah — Rp 10,000,000',
    status: 'pending',
    currentLevel: 1,
    totalLevels: 2,
    workflowName: 'Loan Request Medium',
    amount: 10000000,
    reason: 'Perbaikan atap bocor menjelang musim hujan',
    timeline: [
      {
        level: 1,
        name: 'Direct Manager',
        approverName: 'Diana Lestari (Anda)',
        status: 'pending',
      },
      {
        level: 2,
        name: 'Finance Specialist',
        approverName: 'Yuni Astuti',
        status: 'waiting',
      },
    ],
  },
  {
    id: 'req-009',
    employeeName: 'Diana Lestari',
    department: 'Marketing',
    position: 'Marketing Lead',
    requestType: 'overtime',
    requestDate: '2025-06-05',
    details: 'Lembur Weekend — 8 Jam',
    status: 'pending',
    currentLevel: 2,
    totalLevels: 3,
    workflowName: 'Overtime Approval Long',
    days: 8,
    reason: 'Penyelenggaraan Booth & Event di PRJ Kemayoran',
    timeline: [
      {
        level: 1,
        name: 'Direct Manager',
        approverName: 'Budi Santoso',
        status: 'approved',
        approvedAt: '2025-06-05 18:20',
        note: 'Telah diverifikasi jadwal event.',
      },
      {
        level: 2,
        name: 'Department Head',
        approverName: 'Ahmad Fauzi (Anda)',
        status: 'pending',
      },
      {
        level: 3,
        name: 'HR Manager',
        approverName: 'Yuni Astuti',
        status: 'waiting',
      },
    ],
  },
  {
    id: 'req-010',
    employeeName: 'Yuni Astuti',
    department: 'HR',
    position: 'HR Manager',
    requestType: 'leave',
    requestDate: '2025-06-04',
    details: 'Cuti Alasan Penting — 2 Hari',
    status: 'rejected',
    currentLevel: 1,
    totalLevels: 2,
    workflowName: 'HR Special Leave',
    days: 2,
    reason: 'Urusan perpanjangan sertifikat tanah keluarga',
    timeline: [
      {
        level: 1,
        name: 'Director',
        approverName: 'Hendra Gunawan (Anda)',
        status: 'approved',
        approvedAt: '2025-06-04 14:00',
        note: 'Mohon reschedule ke bulan depan dikarenakan audit tahunan.',
      },
    ],
  },
  {
    id: 'req-011',
    employeeName: 'Hendra Gunawan',
    department: 'Executive',
    position: 'Chief Executive Officer',
    requestType: 'reimbursement',
    requestDate: '2025-06-03',
    details: 'Klaim Perjamuan Client Executive — Rp 2,500,000',
    status: 'approved',
    currentLevel: 2,
    totalLevels: 2,
    workflowName: 'Executive Reimbursement',
    amount: 2500000,
    reason: 'Makan malam bisnis dengan investor luar negeri',
    attachmentUrl: '/assets/receipt-dummy.jpg',
    timeline: [
      {
        level: 1,
        name: 'Finance Manager',
        approverName: 'Yuni Astuti',
        status: 'approved',
        approvedAt: '2025-06-03 16:50',
        note: 'Sesuai dengan plafon biaya representasi direksi.',
      },
      {
        level: 2,
        name: 'Commissioner',
        approverName: 'Ahmad Fauzi (Anda)',
        status: 'approved',
        approvedAt: '2025-06-04 09:30',
        note: 'Dokumen terlampir dan lengkap.',
      },
    ],
  },
  {
    id: 'req-012',
    employeeName: 'Ahmad Fauzi',
    department: 'HR',
    position: 'HR Specialist',
    requestType: 'overtime',
    requestDate: '2025-06-02',
    details: 'Lembur Rekrutmen Massal — 3 Jam',
    status: 'pending',
    currentLevel: 1,
    totalLevels: 2,
    workflowName: 'Overtime Approval Short',
    days: 3,
    reason: 'Interview kandidat batch baru engineering team',
    timeline: [
      {
        level: 1,
        name: 'Direct Manager',
        approverName: 'Yuni Astuti (Anda)',
        status: 'pending',
      },
      {
        level: 2,
        name: 'Department Head',
        approverName: 'Dewi Rahayu',
        status: 'waiting',
      },
    ],
  },
  {
    id: 'req-013',
    employeeName: 'Santi Pratiwi',
    department: 'Finance',
    position: 'Finance Staff',
    requestType: 'loan',
    requestDate: '2025-06-01',
    details: 'Pengajuan Pinjaman Pendidikan — Rp 3,000,000',
    status: 'pending',
    currentLevel: 1,
    totalLevels: 2,
    workflowName: 'Loan Request Short',
    amount: 3000000,
    reason: 'Pembayaran UKT semester ganjil kuliah malam',
    timeline: [
      {
        level: 1,
        name: 'Direct Manager',
        approverName: 'Yuni Astuti (Anda)',
        status: 'pending',
      },
      {
        level: 2,
        name: 'Finance Specialist',
        approverName: 'Dewi Rahayu',
        status: 'waiting',
      },
    ],
  },
  {
    id: 'req-014',
    employeeName: 'Doni Siregar',
    department: 'Sales',
    position: 'Sales Representative',
    requestType: 'leave',
    requestDate: '2025-05-31',
    details: 'Cuti Menikah — 3 Hari',
    status: 'pending',
    currentLevel: 1,
    totalLevels: 2,
    workflowName: 'Leave Approval Short',
    days: 3,
    reason: 'Acara pernikahan pribadi',
    timeline: [
      {
        level: 1,
        name: 'Direct Manager',
        approverName: 'Diana Lestari (Anda)',
        status: 'pending',
      },
      {
        level: 2,
        name: 'HR Specialist',
        approverName: 'Ahmad Fauzi',
        status: 'waiting',
      },
    ],
  },
  {
    id: 'req-015',
    employeeName: 'Maya Indah',
    department: 'Marketing',
    position: 'Public Relation Executive',
    requestType: 'reimbursement',
    requestDate: '2025-05-30',
    details: 'Klaim Iklan Media Massa — Rp 1,500,000',
    status: 'pending',
    currentLevel: 1,
    totalLevels: 2,
    workflowName: 'Reimbursement Approval',
    amount: 1500000,
    reason: 'Pembayaran press release peluncuran produk baru',
    attachmentUrl: '/assets/receipt-dummy.jpg',
    timeline: [
      {
        level: 1,
        name: 'Direct Manager',
        approverName: 'Diana Lestari (Anda)',
        status: 'pending',
      },
      {
        level: 2,
        name: 'Finance Specialist',
        approverName: 'Yuni Astuti',
        status: 'waiting',
      },
    ],
  },
]
