import type { ApprovalRequest } from './types'

export const dummyApprovalRequests: ApprovalRequest[] = [
  // ─── Business Trip Requests ────────────────────────────────────────────────
  {
    id: 'req-bt-001',
    employeeName: 'Dimas Anggara',
    employeeAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    department: 'Enterprise Sales',
    position: 'Account Executive Lead',
    requestType: 'business_trip',
    requestDate: '2026-04-20',
    details: 'Kunjungan Klien & Closing Kontrak — Surabaya (3 Hari)',
    status: 'pending',
    currentLevel: 2,
    totalLevels: 3,
    workflowName: 'Business Trip Approval Workflow',
    days: 3,
    amount: 4750000,
    advanceMoney: 2500000,
    destination: 'Surabaya, Jawa Timur',
    travelDates: '28 Apr 2026 - 30 Apr 2026',
    transportType: 'Pesawat (Garuda Indonesia GA-314)',
    reason: 'Finalisasi negosiasi dan penandatanganan kontrak implementasi ERP dengan PT Petrokimia Nusantara di Surabaya.',
    attachmentUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80',
    timeline: [
      {
        level: 1,
        name: 'Line Manager Review',
        approverName: 'Budi Santoso',
        status: 'approved',
        approvedAt: '2026-04-20 14:10',
        note: 'Peluang deal Q2 sangat potensial. Disetujui untuk berangkat 2 orang.',
      },
      {
        level: 2,
        name: 'Department Head / VP',
        approverName: 'Dewi Rahayu (Anda)',
        status: 'pending',
      },
      {
        level: 3,
        name: 'Finance & GA Travel Desk',
        approverName: 'Farhan Maulana',
        status: 'waiting',
      },
    ],
  },
  {
    id: 'req-bt-002',
    employeeName: 'Ratna Sari',
    employeeAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&auto=format&fit=crop&q=80',
    department: 'Product & Engineering',
    position: 'Principal UI/UX Designer',
    requestType: 'business_trip',
    requestDate: '2026-04-18',
    details: 'Konferensi Tech & Design Summit — Tokyo, Jepang (5 Hari)',
    status: 'pending',
    currentLevel: 1,
    totalLevels: 3,
    workflowName: 'Business Trip Approval Workflow',
    days: 5,
    amount: 28500000,
    advanceMoney: 15000000,
    destination: 'Tokyo, Jepang',
    travelDates: '12 Mei 2026 - 16 Mei 2026',
    transportType: 'Pesawat Internasional (ANA Airways NH-836)',
    reason: 'Mewakili perusahaan sebagai speaker di APAC Design Conference 2026 serta benchmarking produk fintech.',
    attachmentUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80',
    timeline: [
      {
        level: 1,
        name: 'Line Manager Review',
        approverName: 'Dewi Rahayu (Anda)',
        status: 'pending',
      },
      {
        level: 2,
        name: 'Department Head / VP',
        approverName: 'Rizky Pratama',
        status: 'waiting',
      },
      {
        level: 3,
        name: 'Finance & GA Travel Desk',
        approverName: 'Farhan Maulana',
        status: 'waiting',
      },
    ],
  },

  // ─── Claim & Reimbursement Requests ────────────────────────────────────────
  {
    id: 'req-cl-001',
    employeeName: 'Siti Rahayu',
    employeeAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&auto=format&fit=crop&q=80',
    department: 'Finance & Accounting',
    position: 'Senior Finance Analyst',
    requestType: 'claim',
    requestDate: '2026-04-22',
    details: 'Reimbursement Medical & Kacamata Resep — Rp 1,450,000',
    status: 'pending',
    currentLevel: 2,
    totalLevels: 3,
    workflowName: 'Claim & Reimbursement Approval',
    amount: 1450000,
    categoryLabel: 'Medical & Dental Care',
    costCenter: 'CC-FIN-301 (Finance & Treasury)',
    paymentMethod: 'Bank Transfer (BCA)',
    bankAccount: '8820-192-381 a.n Siti Rahayu',
    reason: 'Klaim pemeriksaan mata tahunan dan penggantian lensa kacamata anti-radiasi di Optik Melawai.',
    attachmentUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80',
    timeline: [
      {
        level: 1,
        name: 'Direct Line Manager',
        approverName: 'Hendra Wijaya',
        status: 'approved',
        approvedAt: '2026-04-22 11:20',
        note: 'Kuitansi Optik Melawai lengkap dan dalam batas plafon tahunan.',
      },
      {
        level: 2,
        name: 'HR Policy & Audit Verifier',
        approverName: 'Amanda Putri (Anda)',
        status: 'pending',
      },
      {
        level: 3,
        name: 'Finance Disbursement Batch',
        approverName: 'Farhan Maulana',
        status: 'waiting',
      },
    ],
  },
  {
    id: 'req-cl-002',
    employeeName: 'Bagas Prasetyo',
    employeeAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    department: 'Software Engineering',
    position: 'Senior Backend Engineer',
    requestType: 'claim',
    requestDate: '2026-04-23',
    details: 'Jamuan Makan Siang Klien BCA — Rp 530,150',
    status: 'pending',
    currentLevel: 1,
    totalLevels: 3,
    workflowName: 'Claim & Reimbursement Approval',
    amount: 530150,
    categoryLabel: 'Client Meal & Entertainment',
    costCenter: 'CC-TECH-101 (Core Engineering)',
    paymentMethod: 'Bank Transfer (BCA)',
    bankAccount: '5270-492-110 a.n Bagas Prasetyo',
    reason: 'Makan siang koordinasi integrasi API Payment Gateway dengan tim IT Bank BCA di Restoran Sederhana GI.',
    attachmentUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80',
    timeline: [
      {
        level: 1,
        name: 'Direct Line Manager',
        approverName: 'Rizky Pratama (Anda)',
        status: 'pending',
      },
      {
        level: 2,
        name: 'HR Policy & Audit Verifier',
        approverName: 'Amanda Putri',
        status: 'waiting',
      },
      {
        level: 3,
        name: 'Finance Disbursement Batch',
        approverName: 'Farhan Maulana',
        status: 'waiting',
      },
    ],
  },

  // ─── Leave Requests ────────────────────────────────────────────────────────
  {
    id: 'req-lv-001',
    employeeName: 'Rina Marlina',
    employeeAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    department: 'Software Engineering',
    position: 'Frontend Engineer',
    requestType: 'leave',
    requestDate: '2026-04-21',
    details: 'Cuti Tahunan — 3 Hari (02 - 04 Mei 2026)',
    status: 'pending',
    currentLevel: 2,
    totalLevels: 3,
    workflowName: 'Leave Approval Workflow',
    days: 3,
    reason: 'Keperluan keluarga dan mudik di luar kota (pekerjaan sprint sudah didelegasikan ke rekan tim).',
    timeline: [
      {
        level: 1,
        name: 'Direct Line Manager',
        approverName: 'Rizky Pratama',
        status: 'approved',
        approvedAt: '2026-04-21 16:30',
        note: 'Handover pekerjaan sudah jelas. Selamat berlibur.',
      },
      {
        level: 2,
        name: 'Department Head',
        approverName: 'Dewi Rahayu (Anda)',
        status: 'pending',
      },
      {
        level: 3,
        name: 'HR Manager',
        approverName: 'Ahmad Fauzi',
        status: 'waiting',
      },
    ],
  },
  {
    id: 'req-lv-002',
    employeeName: 'Dian Kurniawan',
    employeeAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    department: 'Brand Marketing',
    position: 'Marketing Specialist',
    requestType: 'leave',
    requestDate: '2026-04-20',
    details: 'Cuti Sakit — 2 Hari (21 - 22 Apr 2026)',
    status: 'approved',
    currentLevel: 3,
    totalLevels: 3,
    workflowName: 'Leave Approval Workflow',
    days: 2,
    reason: 'Sakit demam berdarah (surat keterangan dokter terlampir dan tervalidasi).',
    attachmentUrl: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=600&auto=format&fit=crop&q=80',
    timeline: [
      {
        level: 1,
        name: 'Direct Line Manager',
        approverName: 'Diana Lestari',
        status: 'approved',
        approvedAt: '2026-04-20 09:00',
        note: 'Lekas sembuh Dian.',
      },
      {
        level: 2,
        name: 'Department Head',
        approverName: 'Ahmad Fauzi',
        status: 'approved',
        approvedAt: '2026-04-20 10:15',
        note: 'Disetujui.',
      },
      {
        level: 3,
        name: 'HR Manager',
        approverName: 'Amanda Putri (Anda)',
        status: 'approved',
        approvedAt: '2026-04-20 11:00',
        note: 'Surat dokter valid dan telah dicatat pada sistem absensi.',
      },
    ],
  },

  // ─── Overtime Requests ─────────────────────────────────────────────────────
  {
    id: 'req-ot-001',
    employeeName: 'Wahyu Prasetyo',
    employeeAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&auto=format&fit=crop&q=80',
    department: 'Cloud & Infrastructure',
    position: 'DevOps Engineer',
    requestType: 'overtime',
    requestDate: '2026-04-24',
    details: 'Lembur Hari Kerja — 4 Jam (18:00 - 22:00)',
    status: 'pending',
    currentLevel: 1,
    totalLevels: 2,
    workflowName: 'Overtime Approval Workflow',
    days: 4,
    reason: 'Maintenance server database cluster & upgrade kernel production di luar jam sibuk.',
    timeline: [
      {
        level: 1,
        name: 'Direct Supervisor',
        approverName: 'Rizky Pratama (Anda)',
        status: 'pending',
      },
      {
        level: 2,
        name: 'HR Operations',
        approverName: 'Amanda Putri',
        status: 'waiting',
      },
    ],
  },
  {
    id: 'req-ot-002',
    employeeName: 'Diana Lestari',
    employeeAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80',
    department: 'Brand Marketing',
    position: 'Event Coordinator Lead',
    requestType: 'overtime',
    requestDate: '2026-04-19',
    details: 'Lembur Akhir Pekan — 8 Jam (Sabtu, 20 Apr)',
    status: 'pending',
    currentLevel: 1,
    totalLevels: 2,
    workflowName: 'Overtime Approval Workflow',
    days: 8,
    reason: 'Penyelenggaraan Booth Tech Expo & Workshop di JCC Senayan.',
    timeline: [
      {
        level: 1,
        name: 'Direct Supervisor',
        approverName: 'Dewi Rahayu (Anda)',
        status: 'pending',
      },
      {
        level: 2,
        name: 'HR Operations',
        approverName: 'Amanda Putri',
        status: 'waiting',
      },
    ],
  },
]

