import type { ApprovalLevel, MatrixEntry, RoutingRule, TestResult, Workflow } from './types'

export const dummyWorkflows: Workflow[] = [
  {
    id: 'wf-001',
    name: 'Leave Approval',
    description: 'Workflow persetujuan pengajuan cuti karyawan semua divisi',
    module: 'leave',
    status: 'active',
    totalLevels: 3,
    totalRequests: 247,
    avgProcessingDays: 2.4,
    pendingRequests: 12,
    createdAt: '2025-01-10',
    updatedAt: '2025-05-20',
    createdBy: 'Admin HR',
  },
  {
    id: 'wf-002',
    name: 'Overtime Approval',
    description: 'Workflow persetujuan lembur karyawan dengan limit waktu',
    module: 'overtime',
    status: 'active',
    totalLevels: 2,
    totalRequests: 189,
    avgProcessingDays: 1.2,
    pendingRequests: 8,
    createdAt: '2025-01-15',
    updatedAt: '2025-06-01',
    createdBy: 'Admin HR',
  },
  {
    id: 'wf-003',
    name: 'Reimbursement Approval',
    description: 'Persetujuan klaim penggantian biaya operasional karyawan',
    module: 'reimbursement',
    status: 'active',
    totalLevels: 4,
    totalRequests: 103,
    avgProcessingDays: 3.8,
    pendingRequests: 5,
    createdAt: '2025-02-01',
    updatedAt: '2025-06-10',
    createdBy: 'Finance Admin',
  },
  {
    id: 'wf-004',
    name: 'Resignation Process',
    description: 'Alur pengunduran diri karyawan hingga clearance selesai',
    module: 'resignation',
    status: 'active',
    totalLevels: 5,
    totalRequests: 14,
    avgProcessingDays: 14.0,
    pendingRequests: 2,
    createdAt: '2025-02-10',
    updatedAt: '2025-04-30',
    createdBy: 'Admin HR',
  },
  {
    id: 'wf-005',
    name: 'Loan Request',
    description: 'Persetujuan pinjaman karyawan melalui HR dan Finance',
    module: 'loan',
    status: 'draft',
    totalLevels: 3,
    totalRequests: 0,
    avgProcessingDays: 0,
    pendingRequests: 0,
    createdAt: '2025-06-15',
    updatedAt: '2025-06-15',
    createdBy: 'Admin HR',
  },
  {
    id: 'wf-006',
    name: 'Promotion Approval',
    description: 'Workflow persetujuan promosi jabatan melalui multi-level',
    module: 'promotion',
    status: 'inactive',
    totalLevels: 4,
    totalRequests: 22,
    avgProcessingDays: 7.5,
    pendingRequests: 0,
    createdAt: '2025-03-01',
    updatedAt: '2025-05-01',
    createdBy: 'Admin HR',
  },
]

export const dummyApprovalLevels: Record<string, ApprovalLevel[]> = {
  'wf-001': [
    {
      id: 'lvl-001-1',
      workflowId: 'wf-001',
      level: 1,
      name: 'Direct Manager',
      approverType: 'direct_manager',
      approverValue: 'Direct Manager',
      approvalType: 'any_one',
      timeoutDays: 2,
      timeoutAction: 'escalate',
      requireNote: false,
      canDelegate: true,
    },
    {
      id: 'lvl-001-2',
      workflowId: 'wf-001',
      level: 2,
      name: 'Department Head',
      approverType: 'department_head',
      approverValue: 'Department Head',
      approvalType: 'any_one',
      timeoutDays: 2,
      timeoutAction: 'escalate',
      requireNote: false,
      canDelegate: true,
    },
    {
      id: 'lvl-001-3',
      workflowId: 'wf-001',
      level: 3,
      name: 'HR Manager',
      approverType: 'role',
      approverValue: 'HR Manager',
      approvalType: 'any_one',
      timeoutDays: 1,
      timeoutAction: 'auto_approve',
      requireNote: true,
      canDelegate: false,
    },
  ],
  'wf-002': [
    {
      id: 'lvl-002-1',
      workflowId: 'wf-002',
      level: 1,
      name: 'Supervisor',
      approverType: 'direct_manager',
      approverValue: 'Direct Manager',
      approvalType: 'any_one',
      timeoutDays: 1,
      timeoutAction: 'escalate',
      requireNote: false,
      canDelegate: false,
    },
    {
      id: 'lvl-002-2',
      workflowId: 'wf-002',
      level: 2,
      name: 'HR Staff',
      approverType: 'role',
      approverValue: 'HR Staff',
      approvalType: 'any_one',
      timeoutDays: 1,
      timeoutAction: 'auto_approve',
      requireNote: false,
      canDelegate: false,
    },
  ],
  'wf-003': [
    {
      id: 'lvl-003-1',
      workflowId: 'wf-003',
      level: 1,
      name: 'Direct Manager',
      approverType: 'direct_manager',
      approverValue: 'Direct Manager',
      approvalType: 'any_one',
      timeoutDays: 2,
      timeoutAction: 'escalate',
      requireNote: false,
      canDelegate: true,
    },
    {
      id: 'lvl-003-2',
      workflowId: 'wf-003',
      level: 2,
      name: 'Department Head',
      approverType: 'department_head',
      approverValue: 'Department Head',
      approvalType: 'any_one',
      timeoutDays: 3,
      timeoutAction: 'escalate',
      requireNote: true,
      canDelegate: true,
    },
    {
      id: 'lvl-003-3',
      workflowId: 'wf-003',
      level: 3,
      name: 'Finance Manager',
      approverType: 'role',
      approverValue: 'Finance Manager',
      approvalType: 'any_one',
      timeoutDays: 3,
      timeoutAction: 'escalate',
      requireNote: true,
      canDelegate: false,
    },
    {
      id: 'lvl-003-4',
      workflowId: 'wf-003',
      level: 4,
      name: 'Director',
      approverType: 'role',
      approverValue: 'Director',
      approvalType: 'any_one',
      timeoutDays: 5,
      timeoutAction: 'auto_reject',
      requireNote: true,
      canDelegate: false,
    },
  ],
}

export const dummyRoutingRules: Record<string, RoutingRule[]> = {
  'wf-001': [
    {
      id: 'rule-001-1',
      workflowId: 'wf-001',
      name: 'Leave > 5 days — require Director approval',
      priority: 1,
      conditions: {
        id: 'grp-1',
        logic: 'AND',
        rules: [
          {
            id: 'r1',
            field: 'leave_days',
            operator: 'gt',
            value: 5,
            label: 'Jumlah hari cuti > 5',
          },
        ],
      },
    },
    {
      id: 'rule-001-2',
      workflowId: 'wf-001',
      name: 'Annual Leave — standard flow',
      priority: 2,
      conditions: {
        id: 'grp-2',
        logic: 'AND',
        rules: [
          {
            id: 'r2',
            field: 'leave_type',
            operator: 'eq',
            value: 'annual',
            label: 'Tipe cuti = Tahunan',
          },
        ],
      },
    },
  ],
}

export const dummyTestResult: TestResult = {
  workflowName: 'Leave Approval',
  matchedConditions: ['leave_type = annual', 'leave_days <= 5'],
  levels: [
    {
      level: 1,
      name: 'Direct Manager',
      approver: 'Budi Santoso',
      approverType: 'direct_manager',
      estimatedDays: 1,
    },
    {
      level: 2,
      name: 'Department Head',
      approver: 'Dewi Rahayu',
      approverType: 'department_head',
      estimatedDays: 1,
    },
    {
      level: 3,
      name: 'HR Manager',
      approver: 'Ahmad Fauzi',
      approverType: 'role',
      estimatedDays: 1,
    },
  ],
  totalEstimatedDays: 3,
  canBeApproved: true,
  warnings: [],
}

export const dummyMatrixEntries: MatrixEntry[] = [
  {
    id: 'm-001',
    employeeName: 'Rina Marlina',
    department: 'Engineering',
    position: 'Software Engineer',
    requestType: 'leave',
    workflowName: 'Leave Approval',
    currentLevel: 1,
    totalLevels: 3,
    status: 'in_progress',
    daysElapsed: 1,
  },
  {
    id: 'm-002',
    employeeName: 'Dian Kurniawan',
    department: 'Marketing',
    position: 'Marketing Manager',
    requestType: 'overtime',
    workflowName: 'Overtime Approval',
    currentLevel: 2,
    totalLevels: 2,
    status: 'in_progress',
    daysElapsed: 2,
  },
  {
    id: 'm-003',
    employeeName: 'Siti Rahayu',
    department: 'Finance',
    position: 'Finance Analyst',
    requestType: 'reimbursement',
    workflowName: 'Reimbursement Approval',
    currentLevel: 3,
    totalLevels: 4,
    status: 'in_progress',
    daysElapsed: 5,
  },
  {
    id: 'm-004',
    employeeName: 'Budi Santoso',
    department: 'Operations',
    position: 'Ops Manager',
    requestType: 'leave',
    workflowName: 'Leave Approval',
    currentLevel: 3,
    totalLevels: 3,
    status: 'approved',
    daysElapsed: 2,
  },
  {
    id: 'm-005',
    employeeName: 'Wahyu Prasetyo',
    department: 'Engineering',
    position: 'Backend Developer',
    requestType: 'overtime',
    workflowName: 'Overtime Approval',
    currentLevel: 1,
    totalLevels: 2,
    status: 'pending',
    daysElapsed: 0,
  },
  {
    id: 'm-006',
    employeeName: 'Annisa Fitri',
    department: 'HR',
    position: 'HR Generalist',
    requestType: 'loan',
    workflowName: 'Loan Request',
    currentLevel: 1,
    totalLevels: 3,
    status: 'rejected',
    daysElapsed: 3,
  },
]

export const moduleLabels: Record<string, string> = {
  leave: 'Cuti',
  overtime: 'Lembur',
  reimbursement: 'Reimburse',
  loan: 'Pinjaman',
  resignation: 'Pengunduran Diri',
  transfer: 'Transfer',
  promotion: 'Promosi',
}

export const moduleColors: Record<string, string> = {
  leave: 'bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300',
  overtime: 'bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300',
  reimbursement: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/40 dark:text-emerald-300',
  loan: 'bg-purple-100 text-purple-700 dark:bg-purple-900/40 dark:text-purple-300',
  resignation: 'bg-red-100 text-red-700 dark:bg-red-900/40 dark:text-red-300',
  transfer: 'bg-cyan-100 text-cyan-700 dark:bg-cyan-900/40 dark:text-cyan-300',
  promotion: 'bg-orange-100 text-orange-700 dark:bg-orange-900/40 dark:text-orange-300',
}
