import type { ApprovalLevel, MatrixEntry, RoutingRule, TestResult, Workflow } from './types'

export const dummyWorkflows: Workflow[] = [
  {
    id: 'wf-001',
    name: 'Leave Approval Workflow',
    description: 'Persetujuan cuti tahunan, sakit, dan izin khusus karyawan',
    module: 'leave',
    status: 'active',
    totalLevels: 3,
    totalRequests: 247,
    avgProcessingDays: 2.4,
    pendingRequests: 12,
    createdAt: '2025-01-10',
    updatedAt: '2025-05-20',
    createdBy: 'Admin HR',
  },
  {
    id: 'wf-002',
    name: 'Overtime Approval Workflow',
    description: 'Persetujuan lembur hari kerja & weekend dengan limit waktu',
    module: 'overtime',
    status: 'active',
    totalLevels: 2,
    totalRequests: 189,
    avgProcessingDays: 1.2,
    pendingRequests: 8,
    createdAt: '2025-01-15',
    updatedAt: '2025-06-01',
    createdBy: 'Admin HR',
  },
  {
    id: 'wf-003',
    name: 'Claim & Reimbursement Approval',
    description: 'Verifikasi struk OCR dan persetujuan klaim biaya operasional',
    module: 'claim',
    status: 'active',
    totalLevels: 3,
    totalRequests: 142,
    avgProcessingDays: 2.8,
    pendingRequests: 6,
    createdAt: '2025-02-01',
    updatedAt: '2025-06-10',
    createdBy: 'Finance Admin',
  },
  {
    id: 'wf-004',
    name: 'Business Trip Approval Workflow',
    description: 'Persetujuan perjalanan dinas domestik & internasional beserta uang muka',
    module: 'business_trip',
    status: 'active',
    totalLevels: 3,
    totalRequests: 95,
    avgProcessingDays: 3.1,
    pendingRequests: 4,
    createdAt: '2025-02-15',
    updatedAt: '2025-06-12',
    createdBy: 'Admin HR & GA',
  },
  {
    id: 'wf-005',
    name: 'Resignation Clearance Process',
    description: 'Alur pengunduran diri karyawan hingga exit interview dan serah terima aset',
    module: 'resignation',
    status: 'active',
    totalLevels: 4,
    totalRequests: 14,
    avgProcessingDays: 14.0,
    pendingRequests: 2,
    createdAt: '2025-02-10',
    updatedAt: '2025-04-30',
    createdBy: 'Admin HR',
  },
  {
    id: 'wf-006',
    name: 'Employee Loan Request',
    description: 'Persetujuan pinjaman dana darurat karyawan melalui HR dan Finance',
    module: 'loan',
    status: 'draft',
    totalLevels: 3,
    totalRequests: 0,
    avgProcessingDays: 0,
    pendingRequests: 0,
    createdAt: '2025-06-15',
    updatedAt: '2025-06-15',
    createdBy: 'Admin HR',
  },
  {
    id: 'wf-007',
    name: 'Promotion & Mutation Approval',
    description: 'Workflow persetujuan promosi jabatan dan mutasi antar divisi',
    module: 'promotion',
    status: 'inactive',
    totalLevels: 4,
    totalRequests: 22,
    avgProcessingDays: 7.5,
    pendingRequests: 0,
    createdAt: '2025-03-01',
    updatedAt: '2025-05-01',
    createdBy: 'Admin HR',
  },
]

export const dummyApprovalLevels: Record<string, ApprovalLevel[]> = {
  'wf-001': [
    {
      id: 'lvl-001-1',
      workflowId: 'wf-001',
      level: 1,
      name: 'Direct Line Manager',
      approverType: 'direct_manager',
      approverValue: 'Direct Manager',
      approvalType: 'any_one',
      timeoutDays: 2,
      timeoutAction: 'escalate',
      requireNote: false,
      canDelegate: true,
    },
    {
      id: 'lvl-001-2',
      workflowId: 'wf-001',
      level: 2,
      name: 'Department Head',
      approverType: 'department_head',
      approverValue: 'Department Head',
      approvalType: 'any_one',
      timeoutDays: 2,
      timeoutAction: 'escalate',
      requireNote: false,
      canDelegate: true,
    },
    {
      id: 'lvl-001-3',
      workflowId: 'wf-001',
      level: 3,
      name: 'HR Manager',
      approverType: 'role',
      approverValue: 'HR Manager',
      approvalType: 'any_one',
      timeoutDays: 1,
      timeoutAction: 'auto_approve',
      requireNote: true,
      canDelegate: false,
    },
  ],
  'wf-002': [
    {
      id: 'lvl-002-1',
      workflowId: 'wf-002',
      level: 1,
      name: 'Direct Supervisor',
      approverType: 'direct_manager',
      approverValue: 'Direct Manager',
      approvalType: 'any_one',
      timeoutDays: 1,
      timeoutAction: 'escalate',
      requireNote: false,
      canDelegate: false,
    },
    {
      id: 'lvl-002-2',
      workflowId: 'wf-002',
      level: 2,
      name: 'HR Operations',
      approverType: 'role',
      approverValue: 'HR Staff',
      approvalType: 'any_one',
      timeoutDays: 1,
      timeoutAction: 'auto_approve',
      requireNote: false,
      canDelegate: false,
    },
  ],
  'wf-003': [
    {
      id: 'lvl-003-1',
      workflowId: 'wf-003',
      level: 1,
      name: 'Direct Line Manager',
      approverType: 'direct_manager',
      approverValue: 'Direct Manager',
      approvalType: 'any_one',
      timeoutDays: 2,
      timeoutAction: 'escalate',
      requireNote: false,
      canDelegate: true,
    },
    {
      id: 'lvl-003-2',
      workflowId: 'wf-003',
      level: 2,
      name: 'HR Policy & Audit Verifier',
      approverType: 'role',
      approverValue: 'HR Verifier',
      approvalType: 'any_one',
      timeoutDays: 2,
      timeoutAction: 'escalate',
      requireNote: true,
      canDelegate: true,
    },
    {
      id: 'lvl-003-3',
      workflowId: 'wf-003',
      level: 3,
      name: 'Finance Disbursement Batch',
      approverType: 'role',
      approverValue: 'Treasury Officer',
      approvalType: 'any_one',
      timeoutDays: 3,
      timeoutAction: 'escalate',
      requireNote: true,
      canDelegate: false,
    },
  ],
  'wf-004': [
    {
      id: 'lvl-004-1',
      workflowId: 'wf-004',
      level: 1,
      name: 'Line Manager Review',
      approverType: 'direct_manager',
      approverValue: 'Direct Manager',
      approvalType: 'any_one',
      timeoutDays: 2,
      timeoutAction: 'escalate',
      requireNote: false,
      canDelegate: true,
    },
    {
      id: 'lvl-004-2',
      workflowId: 'wf-004',
      level: 2,
      name: 'Department Head / VP',
      approverType: 'department_head',
      approverValue: 'Department Head',
      approvalType: 'any_one',
      timeoutDays: 2,
      timeoutAction: 'escalate',
      requireNote: true,
      canDelegate: true,
    },
    {
      id: 'lvl-004-3',
      workflowId: 'wf-004',
      level: 3,
      name: 'Finance & GA Travel Desk',
      approverType: 'role',
      approverValue: 'GA & Finance Travel Desk',
      approvalType: 'any_one',
      timeoutDays: 3,
      timeoutAction: 'escalate',
      requireNote: true,
      canDelegate: false,
    },
  ],
}

export const dummyRoutingRules: Record<string, RoutingRule[]> = {
  'wf-001': [
    {
      id: 'rule-001-1',
      workflowId: 'wf-001',
      name: 'Leave > 5 days — require Director approval',
      priority: 1,
      conditions: {
        id: 'grp-1',
        logic: 'AND',
        rules: [
          {
            id: 'r1',
            field: 'leave_days',
            operator: 'gt',
            value: 5,
            label: 'Jumlah hari cuti > 5',
          },
        ],
      },
    },
    {
      id: 'rule-001-2',
      workflowId: 'wf-001',
      name: 'Annual Leave — standard flow',
      priority: 2,
      conditions: {
        id: 'grp-2',
        logic: 'AND',
        rules: [
          {
            id: 'r2',
            field: 'leave_type',
            operator: 'eq',
            value: 'annual',
            label: 'Tipe cuti = Tahunan',
          },
        ],
      },
    },
  ],
  'wf-002': [
    {
      id: 'rule-002-1',
      workflowId: 'wf-002',
      name: 'Lembur Weekend — Require Dept Head',
      priority: 1,
      conditions: {
        id: 'grp-overtime-1',
        logic: 'AND',
        rules: [
          {
            id: 'rot-1',
            field: 'day_type',
            operator: 'eq',
            value: 'weekend',
            label: 'Hari Lembur = Akhir Pekan (Sabtu/Minggu)',
          },
        ],
      },
    },
  ],
  'wf-003': [
    {
      id: 'rule-003-1',
      workflowId: 'wf-003',
      name: 'Klaim > Rp 2.000.000 — Verifikasi Finance Head',
      priority: 1,
      conditions: {
        id: 'grp-claim-1',
        logic: 'AND',
        rules: [
          {
            id: 'rcl-1',
            field: 'amount',
            operator: 'gt',
            value: 2000000,
            label: 'Nominal Klaim > Rp 2.000.000',
          },
        ],
      },
    },
  ],
  'wf-004': [
    {
      id: 'rule-004-1',
      workflowId: 'wf-004',
      name: 'Dinas Internasional — Wajib Approval Direksi',
      priority: 1,
      conditions: {
        id: 'grp-trip-1',
        logic: 'AND',
        rules: [
          {
            id: 'rtrip-1',
            field: 'trip_type',
            operator: 'eq',
            value: 'international',
            label: 'Jenis Perjalanan = Internasional / Luar Negeri',
          },
        ],
      },
    },
  ],
}

export const dummyTestResult: TestResult = {
  workflowName: 'Leave Approval Workflow',
  matchedConditions: ['leave_type = annual', 'leave_days <= 5'],
  levels: [
    {
      level: 1,
      name: 'Direct Line Manager',
      approver: 'Budi Santoso',
      approverType: 'direct_manager',
      estimatedDays: 1,
    },
    {
      level: 2,
      name: 'Department Head',
      approver: 'Dewi Rahayu',
      approverType: 'department_head',
      estimatedDays: 1,
    },
    {
      level: 3,
      name: 'HR Manager',
      approver: 'Ahmad Fauzi',
      approverType: 'role',
      estimatedDays: 1,
    },
  ],
  totalEstimatedDays: 3,
  canBeApproved: true,
  warnings: [],
}

export const dummyMatrixEntries: MatrixEntry[] = [
  {
    id: 'm-001',
    employeeName: 'Rina Marlina',
    department: 'Engineering',
    position: 'Software Engineer',
    requestType: 'leave',
    workflowName: 'Leave Approval Workflow',
    currentLevel: 1,
    totalLevels: 3,
    status: 'in_progress',
    daysElapsed: 1,
  },
  {
    id: 'm-002',
    employeeName: 'Wahyu Prasetyo',
    department: 'Engineering',
    position: 'Backend Developer',
    requestType: 'overtime',
    workflowName: 'Overtime Approval Workflow',
    currentLevel: 1,
    totalLevels: 2,
    status: 'pending',
    daysElapsed: 0,
  },
  {
    id: 'm-003',
    employeeName: 'Siti Rahayu',
    department: 'Finance & Accounting',
    position: 'Senior Finance Analyst',
    requestType: 'claim',
    workflowName: 'Claim & Reimbursement Approval',
    currentLevel: 2,
    totalLevels: 3,
    status: 'in_progress',
    daysElapsed: 2,
  },
  {
    id: 'm-004',
    employeeName: 'Dimas Anggara',
    department: 'Enterprise Sales',
    position: 'Account Executive Lead',
    requestType: 'business_trip',
    workflowName: 'Business Trip Approval Workflow',
    currentLevel: 2,
    totalLevels: 3,
    status: 'in_progress',
    daysElapsed: 1,
  },
  {
    id: 'm-005',
    employeeName: 'Budi Santoso',
    department: 'Operations',
    position: 'Ops Manager',
    requestType: 'leave',
    workflowName: 'Leave Approval Workflow',
    currentLevel: 3,
    totalLevels: 3,
    status: 'approved',
    daysElapsed: 2,
  },
  {
    id: 'm-006',
    employeeName: 'Ratna Sari',
    department: 'Product & Design',
    position: 'UI/UX Designer',
    requestType: 'business_trip',
    workflowName: 'Business Trip Approval Workflow',
    currentLevel: 3,
    totalLevels: 3,
    status: 'approved',
    daysElapsed: 3,
  },
  {
    id: 'm-007',
    employeeName: 'Annisa Fitri',
    department: 'Human Resources',
    position: 'HR Generalist',
    requestType: 'loan',
    workflowName: 'Employee Loan Request',
    currentLevel: 1,
    totalLevels: 3,
    status: 'rejected',
    daysElapsed: 3,
  },
]

export const moduleLabels: Record<string, string> = {
  leave: 'Cuti',
  overtime: 'Lembur',
  claim: 'Klaim Reimbursement',
  reimbursement: 'Reimburse',
  business_trip: 'Perjalanan Dinas',
  loan: 'Pinjaman',
  resignation: 'Pengunduran Diri',
  transfer: 'Transfer',
  promotion: 'Promosi',
}

export const moduleColors: Record<string, string> = {
  leave: 'bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300 border border-blue-200/60',
  overtime: 'bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300 border border-amber-200/60',
  claim: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/40 dark:text-emerald-300 border border-emerald-200/60',
  reimbursement: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/40 dark:text-emerald-300 border border-emerald-200/60',
  business_trip: 'bg-purple-100 text-purple-700 dark:bg-purple-900/40 dark:text-purple-300 border border-purple-200/60',
  loan: 'bg-indigo-100 text-indigo-700 dark:bg-indigo-900/40 dark:text-indigo-300 border border-indigo-200/60',
  resignation: 'bg-red-100 text-red-700 dark:bg-red-900/40 dark:text-red-300 border border-red-200/60',
  transfer: 'bg-cyan-100 text-cyan-700 dark:bg-cyan-900/40 dark:text-cyan-300 border border-cyan-200/60',
  promotion: 'bg-orange-100 text-orange-700 dark:bg-orange-900/40 dark:text-orange-300 border border-orange-200/60',
}
