/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../routes/__root'
import { Route as appRouteRouteImport } from './../../routes/(app)/route'
import { Route as authResetRouteImport } from './../../routes/(auth)/reset'
import { Route as authSigninRouteImport } from './../../routes/(auth)/signin'
import { Route as authSignoutRouteImport } from './../../routes/(auth)/signout'
import { Route as authVerificationRouteImport } from './../../routes/(auth)/verification'
import { Route as appdashboardIndexRouteImport } from './../../routes/(app)/(dashboard)/index'
import { Route as appApprovalIndexRouteImport } from './../../routes/(app)/approval/index'
import { Route as appAttendanceIndexRouteImport } from './../../routes/(app)/attendance/index'
import { Route as appLeaveIndexRouteImport } from './../../routes/(app)/leave/index'
import { Route as appPayrollIndexRouteImport } from './../../routes/(app)/payroll/index'
import { Route as appPerformanceIndexRouteImport } from './../../routes/(app)/performance/index'
import { Route as appReportIndexRouteImport } from './../../routes/(app)/report/index'
import { Route as appdashboardDashboardCustomizeRouteImport } from './../../routes/(app)/(dashboard)/dashboard.customize'
import { Route as appdashboardDashboardEmployeeRouteImport } from './../../routes/(app)/(dashboard)/dashboard.employee'
import { Route as appdashboardDashboardExecutiveRouteImport } from './../../routes/(app)/(dashboard)/dashboard.executive'
import { Route as appdashboardDashboardHrRouteImport } from './../../routes/(app)/(dashboard)/dashboard.hr'
import { Route as appdashboardDashboardManagerRouteImport } from './../../routes/(app)/(dashboard)/dashboard.manager'
import { Route as appCompanyDocumentIndexRouteImport } from './../../routes/(app)/company/document/index'
import { Route as appCompanyEmployeeIndexRouteImport } from './../../routes/(app)/company/employee/index'
import { Route as appCompanyEmployeeIdRouteImport } from './../../routes/(app)/company/employee/$id'
import { Route as appCompanyEmployeeNewRouteImport } from './../../routes/(app)/company/employee/new'
import { Route as appCompanyEmployeeUpdateRouteImport } from './../../routes/(app)/company/employee/update'
import { Route as appCompanyOrganizationIndexRouteImport } from './../../routes/(app)/company/organization/index'
import { Route as appCompanyOrganizationIdRouteImport } from './../../routes/(app)/company/organization/$id'
import { Route as appCompanyOrganizationNewRouteImport } from './../../routes/(app)/company/organization/new'
import { Route as appCompanyOrganizationUpdateRouteImport } from './../../routes/(app)/company/organization/update'
import { Route as appSettingsApprovalWorkflowIndexRouteImport } from './../../routes/(app)/settings/approval-workflow/index'
import { Route as appSettingsApprovalWorkflowMatrixRouteImport } from './../../routes/(app)/settings/approval-workflow/matrix'
import { Route as appSettingsApprovalWorkflowNewRouteImport } from './../../routes/(app)/settings/approval-workflow/new'
import { Route as appSettingsCompanyIndexRouteImport } from './../../routes/(app)/settings/company/index'
import { Route as appSettingsMasterDataIndexRouteImport } from './../../routes/(app)/settings/master-data/index'
import { Route as appSettingsMasterDataDepartmentsRouteImport } from './../../routes/(app)/settings/master-data/departments'
import { Route as appSettingsMasterDataDivisionsRouteImport } from './../../routes/(app)/settings/master-data/divisions'
import { Route as appSettingsMasterDataGradesRouteImport } from './../../routes/(app)/settings/master-data/grades'
import { Route as appSettingsMasterDataHolidaysRouteImport } from './../../routes/(app)/settings/master-data/holidays'
import { Route as appSettingsMasterDataImportRouteImport } from './../../routes/(app)/settings/master-data/import'
import { Route as appSettingsMasterDataLeaveTypesRouteImport } from './../../routes/(app)/settings/master-data/leave-types'
import { Route as appSettingsMasterDataPayrollComponentsRouteImport } from './../../routes/(app)/settings/master-data/payroll-components'
import { Route as appSettingsMasterDataPositionsRouteImport } from './../../routes/(app)/settings/master-data/positions'
import { Route as appSettingsMasterDataShiftsRouteImport } from './../../routes/(app)/settings/master-data/shifts'
import { Route as appSettingsNotificationIndexRouteImport } from './../../routes/(app)/settings/notification/index'
import { Route as appSettingsSecurityIndexRouteImport } from './../../routes/(app)/settings/security/index'
import { Route as appSettingsUserRoleIndexRouteImport } from './../../routes/(app)/settings/user-role/index'
import { Route as appSettingsUserRoleCreateRoleRouteImport } from './../../routes/(app)/settings/user-role/create-role'
import { Route as appSettingsApprovalWorkflowIdIndexRouteImport } from './../../routes/(app)/settings/approval-workflow/$id/index'
import { Route as appSettingsApprovalWorkflowIdConditionsRouteImport } from './../../routes/(app)/settings/approval-workflow/$id/conditions'
import { Route as appSettingsApprovalWorkflowIdLevelsRouteImport } from './../../routes/(app)/settings/approval-workflow/$id/levels'
import { Route as appSettingsApprovalWorkflowIdTestRouteImport } from './../../routes/(app)/settings/approval-workflow/$id/test'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetRoute = authResetRouteImport.update({
  id: '/(auth)/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const authSigninRoute = authSigninRouteImport.update({
  id: '/(auth)/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignoutRoute = authSignoutRouteImport.update({
  id: '/(auth)/signout',
  path: '/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerificationRoute = authVerificationRouteImport.update({
  id: '/(auth)/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const appdashboardIndexRoute = appdashboardIndexRouteImport.update({
  id: '/(dashboard)/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const appApprovalIndexRoute = appApprovalIndexRouteImport.update({
  id: '/approval/',
  path: '/approval/',
  getParentRoute: () => appRouteRoute,
} as any)
const appAttendanceIndexRoute = appAttendanceIndexRouteImport.update({
  id: '/attendance/',
  path: '/attendance/',
  getParentRoute: () => appRouteRoute,
} as any)
const appLeaveIndexRoute = appLeaveIndexRouteImport.update({
  id: '/leave/',
  path: '/leave/',
  getParentRoute: () => appRouteRoute,
} as any)
const appPayrollIndexRoute = appPayrollIndexRouteImport.update({
  id: '/payroll/',
  path: '/payroll/',
  getParentRoute: () => appRouteRoute,
} as any)
const appPerformanceIndexRoute = appPerformanceIndexRouteImport.update({
  id: '/performance/',
  path: '/performance/',
  getParentRoute: () => appRouteRoute,
} as any)
const appReportIndexRoute = appReportIndexRouteImport.update({
  id: '/report/',
  path: '/report/',
  getParentRoute: () => appRouteRoute,
} as any)
const appdashboardDashboardCustomizeRoute =
  appdashboardDashboardCustomizeRouteImport.update({
    id: '/(dashboard)/dashboard/customize',
    path: '/dashboard/customize',
    getParentRoute: () => appRouteRoute,
  } as any)
const appdashboardDashboardEmployeeRoute =
  appdashboardDashboardEmployeeRouteImport.update({
    id: '/(dashboard)/dashboard/employee',
    path: '/dashboard/employee',
    getParentRoute: () => appRouteRoute,
  } as any)
const appdashboardDashboardExecutiveRoute =
  appdashboardDashboardExecutiveRouteImport.update({
    id: '/(dashboard)/dashboard/executive',
    path: '/dashboard/executive',
    getParentRoute: () => appRouteRoute,
  } as any)
const appdashboardDashboardHrRoute = appdashboardDashboardHrRouteImport.update({
  id: '/(dashboard)/dashboard/hr',
  path: '/dashboard/hr',
  getParentRoute: () => appRouteRoute,
} as any)
const appdashboardDashboardManagerRoute =
  appdashboardDashboardManagerRouteImport.update({
    id: '/(dashboard)/dashboard/manager',
    path: '/dashboard/manager',
    getParentRoute: () => appRouteRoute,
  } as any)
const appCompanyDocumentIndexRoute = appCompanyDocumentIndexRouteImport.update({
  id: '/company/document/',
  path: '/company/document/',
  getParentRoute: () => appRouteRoute,
} as any)
const appCompanyEmployeeIndexRoute = appCompanyEmployeeIndexRouteImport.update({
  id: '/company/employee/',
  path: '/company/employee/',
  getParentRoute: () => appRouteRoute,
} as any)
const appCompanyEmployeeIdRoute = appCompanyEmployeeIdRouteImport.update({
  id: '/company/employee/$id',
  path: '/company/employee/$id',
  getParentRoute: () => appRouteRoute,
} as any)
const appCompanyEmployeeNewRoute = appCompanyEmployeeNewRouteImport.update({
  id: '/company/employee/new',
  path: '/company/employee/new',
  getParentRoute: () => appRouteRoute,
} as any)
const appCompanyEmployeeUpdateRoute =
  appCompanyEmployeeUpdateRouteImport.update({
    id: '/company/employee/update',
    path: '/company/employee/update',
    getParentRoute: () => appRouteRoute,
  } as any)
const appCompanyOrganizationIndexRoute =
  appCompanyOrganizationIndexRouteImport.update({
    id: '/company/organization/',
    path: '/company/organization/',
    getParentRoute: () => appRouteRoute,
  } as any)
const appCompanyOrganizationIdRoute =
  appCompanyOrganizationIdRouteImport.update({
    id: '/company/organization/$id',
    path: '/company/organization/$id',
    getParentRoute: () => appRouteRoute,
  } as any)
const appCompanyOrganizationNewRoute =
  appCompanyOrganizationNewRouteImport.update({
    id: '/company/organization/new',
    path: '/company/organization/new',
    getParentRoute: () => appRouteRoute,
  } as any)
const appCompanyOrganizationUpdateRoute =
  appCompanyOrganizationUpdateRouteImport.update({
    id: '/company/organization/update',
    path: '/company/organization/update',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsApprovalWorkflowIndexRoute =
  appSettingsApprovalWorkflowIndexRouteImport.update({
    id: '/settings/approval-workflow/',
    path: '/settings/approval-workflow/',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsApprovalWorkflowMatrixRoute =
  appSettingsApprovalWorkflowMatrixRouteImport.update({
    id: '/settings/approval-workflow/matrix',
    path: '/settings/approval-workflow/matrix',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsApprovalWorkflowNewRoute =
  appSettingsApprovalWorkflowNewRouteImport.update({
    id: '/settings/approval-workflow/new',
    path: '/settings/approval-workflow/new',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsCompanyIndexRoute = appSettingsCompanyIndexRouteImport.update({
  id: '/settings/company/',
  path: '/settings/company/',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsMasterDataIndexRoute =
  appSettingsMasterDataIndexRouteImport.update({
    id: '/settings/master-data/',
    path: '/settings/master-data/',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsMasterDataDepartmentsRoute =
  appSettingsMasterDataDepartmentsRouteImport.update({
    id: '/settings/master-data/departments',
    path: '/settings/master-data/departments',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsMasterDataDivisionsRoute =
  appSettingsMasterDataDivisionsRouteImport.update({
    id: '/settings/master-data/divisions',
    path: '/settings/master-data/divisions',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsMasterDataGradesRoute =
  appSettingsMasterDataGradesRouteImport.update({
    id: '/settings/master-data/grades',
    path: '/settings/master-data/grades',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsMasterDataHolidaysRoute =
  appSettingsMasterDataHolidaysRouteImport.update({
    id: '/settings/master-data/holidays',
    path: '/settings/master-data/holidays',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsMasterDataImportRoute =
  appSettingsMasterDataImportRouteImport.update({
    id: '/settings/master-data/import',
    path: '/settings/master-data/import',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsMasterDataLeaveTypesRoute =
  appSettingsMasterDataLeaveTypesRouteImport.update({
    id: '/settings/master-data/leave-types',
    path: '/settings/master-data/leave-types',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsMasterDataPayrollComponentsRoute =
  appSettingsMasterDataPayrollComponentsRouteImport.update({
    id: '/settings/master-data/payroll-components',
    path: '/settings/master-data/payroll-components',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsMasterDataPositionsRoute =
  appSettingsMasterDataPositionsRouteImport.update({
    id: '/settings/master-data/positions',
    path: '/settings/master-data/positions',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsMasterDataShiftsRoute =
  appSettingsMasterDataShiftsRouteImport.update({
    id: '/settings/master-data/shifts',
    path: '/settings/master-data/shifts',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsNotificationIndexRoute =
  appSettingsNotificationIndexRouteImport.update({
    id: '/settings/notification/',
    path: '/settings/notification/',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsSecurityIndexRoute =
  appSettingsSecurityIndexRouteImport.update({
    id: '/settings/security/',
    path: '/settings/security/',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsUserRoleIndexRoute =
  appSettingsUserRoleIndexRouteImport.update({
    id: '/settings/user-role/',
    path: '/settings/user-role/',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsUserRoleCreateRoleRoute =
  appSettingsUserRoleCreateRoleRouteImport.update({
    id: '/settings/user-role/create-role',
    path: '/settings/user-role/create-role',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsApprovalWorkflowIdIndexRoute =
  appSettingsApprovalWorkflowIdIndexRouteImport.update({
    id: '/settings/approval-workflow/$id/',
    path: '/settings/approval-workflow/$id/',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsApprovalWorkflowIdConditionsRoute =
  appSettingsApprovalWorkflowIdConditionsRouteImport.update({
    id: '/settings/approval-workflow/$id/conditions',
    path: '/settings/approval-workflow/$id/conditions',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsApprovalWorkflowIdLevelsRoute =
  appSettingsApprovalWorkflowIdLevelsRouteImport.update({
    id: '/settings/approval-workflow/$id/levels',
    path: '/settings/approval-workflow/$id/levels',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsApprovalWorkflowIdTestRoute =
  appSettingsApprovalWorkflowIdTestRouteImport.update({
    id: '/settings/approval-workflow/$id/test',
    path: '/settings/approval-workflow/$id/test',
    getParentRoute: () => appRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/reset': typeof authResetRoute
  '/signin': typeof authSigninRoute
  '/signout': typeof authSignoutRoute
  '/verification': typeof authVerificationRoute
  '/': typeof appdashboardIndexRoute
  '/approval/': typeof appApprovalIndexRoute
  '/attendance/': typeof appAttendanceIndexRoute
  '/leave/': typeof appLeaveIndexRoute
  '/payroll/': typeof appPayrollIndexRoute
  '/performance/': typeof appPerformanceIndexRoute
  '/report/': typeof appReportIndexRoute
  '/dashboard/customize': typeof appdashboardDashboardCustomizeRoute
  '/dashboard/employee': typeof appdashboardDashboardEmployeeRoute
  '/dashboard/executive': typeof appdashboardDashboardExecutiveRoute
  '/dashboard/hr': typeof appdashboardDashboardHrRoute
  '/dashboard/manager': typeof appdashboardDashboardManagerRoute
  '/company/employee/$id': typeof appCompanyEmployeeIdRoute
  '/company/employee/new': typeof appCompanyEmployeeNewRoute
  '/company/employee/update': typeof appCompanyEmployeeUpdateRoute
  '/company/organization/$id': typeof appCompanyOrganizationIdRoute
  '/company/organization/new': typeof appCompanyOrganizationNewRoute
  '/company/organization/update': typeof appCompanyOrganizationUpdateRoute
  '/settings/approval-workflow/matrix': typeof appSettingsApprovalWorkflowMatrixRoute
  '/settings/approval-workflow/new': typeof appSettingsApprovalWorkflowNewRoute
  '/settings/master-data/departments': typeof appSettingsMasterDataDepartmentsRoute
  '/settings/master-data/divisions': typeof appSettingsMasterDataDivisionsRoute
  '/settings/master-data/grades': typeof appSettingsMasterDataGradesRoute
  '/settings/master-data/holidays': typeof appSettingsMasterDataHolidaysRoute
  '/settings/master-data/import': typeof appSettingsMasterDataImportRoute
  '/settings/master-data/leave-types': typeof appSettingsMasterDataLeaveTypesRoute
  '/settings/master-data/payroll-components': typeof appSettingsMasterDataPayrollComponentsRoute
  '/settings/master-data/positions': typeof appSettingsMasterDataPositionsRoute
  '/settings/master-data/shifts': typeof appSettingsMasterDataShiftsRoute
  '/settings/user-role/create-role': typeof appSettingsUserRoleCreateRoleRoute
  '/company/document/': typeof appCompanyDocumentIndexRoute
  '/company/employee/': typeof appCompanyEmployeeIndexRoute
  '/company/organization/': typeof appCompanyOrganizationIndexRoute
  '/settings/approval-workflow/': typeof appSettingsApprovalWorkflowIndexRoute
  '/settings/company/': typeof appSettingsCompanyIndexRoute
  '/settings/master-data/': typeof appSettingsMasterDataIndexRoute
  '/settings/notification/': typeof appSettingsNotificationIndexRoute
  '/settings/security/': typeof appSettingsSecurityIndexRoute
  '/settings/user-role/': typeof appSettingsUserRoleIndexRoute
  '/settings/approval-workflow/$id/conditions': typeof appSettingsApprovalWorkflowIdConditionsRoute
  '/settings/approval-workflow/$id/levels': typeof appSettingsApprovalWorkflowIdLevelsRoute
  '/settings/approval-workflow/$id/test': typeof appSettingsApprovalWorkflowIdTestRoute
  '/settings/approval-workflow/$id/': typeof appSettingsApprovalWorkflowIdIndexRoute
}
export interface FileRoutesByTo {
  '/reset': typeof authResetRoute
  '/signin': typeof authSigninRoute
  '/signout': typeof authSignoutRoute
  '/verification': typeof authVerificationRoute
  '/': typeof appdashboardIndexRoute
  '/approval': typeof appApprovalIndexRoute
  '/attendance': typeof appAttendanceIndexRoute
  '/leave': typeof appLeaveIndexRoute
  '/payroll': typeof appPayrollIndexRoute
  '/performance': typeof appPerformanceIndexRoute
  '/report': typeof appReportIndexRoute
  '/dashboard/customize': typeof appdashboardDashboardCustomizeRoute
  '/dashboard/employee': typeof appdashboardDashboardEmployeeRoute
  '/dashboard/executive': typeof appdashboardDashboardExecutiveRoute
  '/dashboard/hr': typeof appdashboardDashboardHrRoute
  '/dashboard/manager': typeof appdashboardDashboardManagerRoute
  '/company/employee/$id': typeof appCompanyEmployeeIdRoute
  '/company/employee/new': typeof appCompanyEmployeeNewRoute
  '/company/employee/update': typeof appCompanyEmployeeUpdateRoute
  '/company/organization/$id': typeof appCompanyOrganizationIdRoute
  '/company/organization/new': typeof appCompanyOrganizationNewRoute
  '/company/organization/update': typeof appCompanyOrganizationUpdateRoute
  '/settings/approval-workflow/matrix': typeof appSettingsApprovalWorkflowMatrixRoute
  '/settings/approval-workflow/new': typeof appSettingsApprovalWorkflowNewRoute
  '/settings/master-data/departments': typeof appSettingsMasterDataDepartmentsRoute
  '/settings/master-data/divisions': typeof appSettingsMasterDataDivisionsRoute
  '/settings/master-data/grades': typeof appSettingsMasterDataGradesRoute
  '/settings/master-data/holidays': typeof appSettingsMasterDataHolidaysRoute
  '/settings/master-data/import': typeof appSettingsMasterDataImportRoute
  '/settings/master-data/leave-types': typeof appSettingsMasterDataLeaveTypesRoute
  '/settings/master-data/payroll-components': typeof appSettingsMasterDataPayrollComponentsRoute
  '/settings/master-data/positions': typeof appSettingsMasterDataPositionsRoute
  '/settings/master-data/shifts': typeof appSettingsMasterDataShiftsRoute
  '/settings/user-role/create-role': typeof appSettingsUserRoleCreateRoleRoute
  '/company/document': typeof appCompanyDocumentIndexRoute
  '/company/employee': typeof appCompanyEmployeeIndexRoute
  '/company/organization': typeof appCompanyOrganizationIndexRoute
  '/settings/approval-workflow': typeof appSettingsApprovalWorkflowIndexRoute
  '/settings/company': typeof appSettingsCompanyIndexRoute
  '/settings/master-data': typeof appSettingsMasterDataIndexRoute
  '/settings/notification': typeof appSettingsNotificationIndexRoute
  '/settings/security': typeof appSettingsSecurityIndexRoute
  '/settings/user-role': typeof appSettingsUserRoleIndexRoute
  '/settings/approval-workflow/$id/conditions': typeof appSettingsApprovalWorkflowIdConditionsRoute
  '/settings/approval-workflow/$id/levels': typeof appSettingsApprovalWorkflowIdLevelsRoute
  '/settings/approval-workflow/$id/test': typeof appSettingsApprovalWorkflowIdTestRoute
  '/settings/approval-workflow/$id': typeof appSettingsApprovalWorkflowIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)/reset': typeof authResetRoute
  '/(auth)/signin': typeof authSigninRoute
  '/(auth)/signout': typeof authSignoutRoute
  '/(auth)/verification': typeof authVerificationRoute
  '/(app)/(dashboard)/': typeof appdashboardIndexRoute
  '/(app)/approval/': typeof appApprovalIndexRoute
  '/(app)/attendance/': typeof appAttendanceIndexRoute
  '/(app)/leave/': typeof appLeaveIndexRoute
  '/(app)/payroll/': typeof appPayrollIndexRoute
  '/(app)/performance/': typeof appPerformanceIndexRoute
  '/(app)/report/': typeof appReportIndexRoute
  '/(app)/(dashboard)/dashboard/customize': typeof appdashboardDashboardCustomizeRoute
  '/(app)/(dashboard)/dashboard/employee': typeof appdashboardDashboardEmployeeRoute
  '/(app)/(dashboard)/dashboard/executive': typeof appdashboardDashboardExecutiveRoute
  '/(app)/(dashboard)/dashboard/hr': typeof appdashboardDashboardHrRoute
  '/(app)/(dashboard)/dashboard/manager': typeof appdashboardDashboardManagerRoute
  '/(app)/company/employee/$id': typeof appCompanyEmployeeIdRoute
  '/(app)/company/employee/new': typeof appCompanyEmployeeNewRoute
  '/(app)/company/employee/update': typeof appCompanyEmployeeUpdateRoute
  '/(app)/company/organization/$id': typeof appCompanyOrganizationIdRoute
  '/(app)/company/organization/new': typeof appCompanyOrganizationNewRoute
  '/(app)/company/organization/update': typeof appCompanyOrganizationUpdateRoute
  '/(app)/settings/approval-workflow/matrix': typeof appSettingsApprovalWorkflowMatrixRoute
  '/(app)/settings/approval-workflow/new': typeof appSettingsApprovalWorkflowNewRoute
  '/(app)/settings/master-data/departments': typeof appSettingsMasterDataDepartmentsRoute
  '/(app)/settings/master-data/divisions': typeof appSettingsMasterDataDivisionsRoute
  '/(app)/settings/master-data/grades': typeof appSettingsMasterDataGradesRoute
  '/(app)/settings/master-data/holidays': typeof appSettingsMasterDataHolidaysRoute
  '/(app)/settings/master-data/import': typeof appSettingsMasterDataImportRoute
  '/(app)/settings/master-data/leave-types': typeof appSettingsMasterDataLeaveTypesRoute
  '/(app)/settings/master-data/payroll-components': typeof appSettingsMasterDataPayrollComponentsRoute
  '/(app)/settings/master-data/positions': typeof appSettingsMasterDataPositionsRoute
  '/(app)/settings/master-data/shifts': typeof appSettingsMasterDataShiftsRoute
  '/(app)/settings/user-role/create-role': typeof appSettingsUserRoleCreateRoleRoute
  '/(app)/company/document/': typeof appCompanyDocumentIndexRoute
  '/(app)/company/employee/': typeof appCompanyEmployeeIndexRoute
  '/(app)/company/organization/': typeof appCompanyOrganizationIndexRoute
  '/(app)/settings/approval-workflow/': typeof appSettingsApprovalWorkflowIndexRoute
  '/(app)/settings/company/': typeof appSettingsCompanyIndexRoute
  '/(app)/settings/master-data/': typeof appSettingsMasterDataIndexRoute
  '/(app)/settings/notification/': typeof appSettingsNotificationIndexRoute
  '/(app)/settings/security/': typeof appSettingsSecurityIndexRoute
  '/(app)/settings/user-role/': typeof appSettingsUserRoleIndexRoute
  '/(app)/settings/approval-workflow/$id/conditions': typeof appSettingsApprovalWorkflowIdConditionsRoute
  '/(app)/settings/approval-workflow/$id/levels': typeof appSettingsApprovalWorkflowIdLevelsRoute
  '/(app)/settings/approval-workflow/$id/test': typeof appSettingsApprovalWorkflowIdTestRoute
  '/(app)/settings/approval-workflow/$id/': typeof appSettingsApprovalWorkflowIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/reset'
    | '/signin'
    | '/signout'
    | '/verification'
    | '/'
    | '/approval/'
    | '/attendance/'
    | '/leave/'
    | '/payroll/'
    | '/performance/'
    | '/report/'
    | '/dashboard/customize'
    | '/dashboard/employee'
    | '/dashboard/executive'
    | '/dashboard/hr'
    | '/dashboard/manager'
    | '/company/employee/$id'
    | '/company/employee/new'
    | '/company/employee/update'
    | '/company/organization/$id'
    | '/company/organization/new'
    | '/company/organization/update'
    | '/settings/approval-workflow/matrix'
    | '/settings/approval-workflow/new'
    | '/settings/master-data/departments'
    | '/settings/master-data/divisions'
    | '/settings/master-data/grades'
    | '/settings/master-data/holidays'
    | '/settings/master-data/import'
    | '/settings/master-data/leave-types'
    | '/settings/master-data/payroll-components'
    | '/settings/master-data/positions'
    | '/settings/master-data/shifts'
    | '/settings/user-role/create-role'
    | '/company/document/'
    | '/company/employee/'
    | '/company/organization/'
    | '/settings/approval-workflow/'
    | '/settings/company/'
    | '/settings/master-data/'
    | '/settings/notification/'
    | '/settings/security/'
    | '/settings/user-role/'
    | '/settings/approval-workflow/$id/conditions'
    | '/settings/approval-workflow/$id/levels'
    | '/settings/approval-workflow/$id/test'
    | '/settings/approval-workflow/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/reset'
    | '/signin'
    | '/signout'
    | '/verification'
    | '/'
    | '/approval'
    | '/attendance'
    | '/leave'
    | '/payroll'
    | '/performance'
    | '/report'
    | '/dashboard/customize'
    | '/dashboard/employee'
    | '/dashboard/executive'
    | '/dashboard/hr'
    | '/dashboard/manager'
    | '/company/employee/$id'
    | '/company/employee/new'
    | '/company/employee/update'
    | '/company/organization/$id'
    | '/company/organization/new'
    | '/company/organization/update'
    | '/settings/approval-workflow/matrix'
    | '/settings/approval-workflow/new'
    | '/settings/master-data/departments'
    | '/settings/master-data/divisions'
    | '/settings/master-data/grades'
    | '/settings/master-data/holidays'
    | '/settings/master-data/import'
    | '/settings/master-data/leave-types'
    | '/settings/master-data/payroll-components'
    | '/settings/master-data/positions'
    | '/settings/master-data/shifts'
    | '/settings/user-role/create-role'
    | '/company/document'
    | '/company/employee'
    | '/company/organization'
    | '/settings/approval-workflow'
    | '/settings/company'
    | '/settings/master-data'
    | '/settings/notification'
    | '/settings/security'
    | '/settings/user-role'
    | '/settings/approval-workflow/$id/conditions'
    | '/settings/approval-workflow/$id/levels'
    | '/settings/approval-workflow/$id/test'
    | '/settings/approval-workflow/$id'
  id:
    | '__root__'
    | '/(app)'
    | '/(auth)/reset'
    | '/(auth)/signin'
    | '/(auth)/signout'
    | '/(auth)/verification'
    | '/(app)/(dashboard)/'
    | '/(app)/approval/'
    | '/(app)/attendance/'
    | '/(app)/leave/'
    | '/(app)/payroll/'
    | '/(app)/performance/'
    | '/(app)/report/'
    | '/(app)/(dashboard)/dashboard/customize'
    | '/(app)/(dashboard)/dashboard/employee'
    | '/(app)/(dashboard)/dashboard/executive'
    | '/(app)/(dashboard)/dashboard/hr'
    | '/(app)/(dashboard)/dashboard/manager'
    | '/(app)/company/employee/$id'
    | '/(app)/company/employee/new'
    | '/(app)/company/employee/update'
    | '/(app)/company/organization/$id'
    | '/(app)/company/organization/new'
    | '/(app)/company/organization/update'
    | '/(app)/settings/approval-workflow/matrix'
    | '/(app)/settings/approval-workflow/new'
    | '/(app)/settings/master-data/departments'
    | '/(app)/settings/master-data/divisions'
    | '/(app)/settings/master-data/grades'
    | '/(app)/settings/master-data/holidays'
    | '/(app)/settings/master-data/import'
    | '/(app)/settings/master-data/leave-types'
    | '/(app)/settings/master-data/payroll-components'
    | '/(app)/settings/master-data/positions'
    | '/(app)/settings/master-data/shifts'
    | '/(app)/settings/user-role/create-role'
    | '/(app)/company/document/'
    | '/(app)/company/employee/'
    | '/(app)/company/organization/'
    | '/(app)/settings/approval-workflow/'
    | '/(app)/settings/company/'
    | '/(app)/settings/master-data/'
    | '/(app)/settings/notification/'
    | '/(app)/settings/security/'
    | '/(app)/settings/user-role/'
    | '/(app)/settings/approval-workflow/$id/conditions'
    | '/(app)/settings/approval-workflow/$id/levels'
    | '/(app)/settings/approval-workflow/$id/test'
    | '/(app)/settings/approval-workflow/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authResetRoute: typeof authResetRoute
  authSigninRoute: typeof authSigninRoute
  authSignoutRoute: typeof authSignoutRoute
  authVerificationRoute: typeof authVerificationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset': {
      id: '/(auth)/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof authResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signout': {
      id: '/(auth)/signout'
      path: '/signout'
      fullPath: '/signout'
      preLoaderRoute: typeof authSignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verification': {
      id: '/(auth)/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof authVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(dashboard)/': {
      id: '/(app)/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appdashboardIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/approval/': {
      id: '/(app)/approval/'
      path: '/approval'
      fullPath: '/approval/'
      preLoaderRoute: typeof appApprovalIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/attendance/': {
      id: '/(app)/attendance/'
      path: '/attendance'
      fullPath: '/attendance/'
      preLoaderRoute: typeof appAttendanceIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/leave/': {
      id: '/(app)/leave/'
      path: '/leave'
      fullPath: '/leave/'
      preLoaderRoute: typeof appLeaveIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/payroll/': {
      id: '/(app)/payroll/'
      path: '/payroll'
      fullPath: '/payroll/'
      preLoaderRoute: typeof appPayrollIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/performance/': {
      id: '/(app)/performance/'
      path: '/performance'
      fullPath: '/performance/'
      preLoaderRoute: typeof appPerformanceIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/report/': {
      id: '/(app)/report/'
      path: '/report'
      fullPath: '/report/'
      preLoaderRoute: typeof appReportIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(dashboard)/dashboard/customize': {
      id: '/(app)/(dashboard)/dashboard/customize'
      path: '/dashboard/customize'
      fullPath: '/dashboard/customize'
      preLoaderRoute: typeof appdashboardDashboardCustomizeRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(dashboard)/dashboard/employee': {
      id: '/(app)/(dashboard)/dashboard/employee'
      path: '/dashboard/employee'
      fullPath: '/dashboard/employee'
      preLoaderRoute: typeof appdashboardDashboardEmployeeRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(dashboard)/dashboard/executive': {
      id: '/(app)/(dashboard)/dashboard/executive'
      path: '/dashboard/executive'
      fullPath: '/dashboard/executive'
      preLoaderRoute: typeof appdashboardDashboardExecutiveRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(dashboard)/dashboard/hr': {
      id: '/(app)/(dashboard)/dashboard/hr'
      path: '/dashboard/hr'
      fullPath: '/dashboard/hr'
      preLoaderRoute: typeof appdashboardDashboardHrRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(dashboard)/dashboard/manager': {
      id: '/(app)/(dashboard)/dashboard/manager'
      path: '/dashboard/manager'
      fullPath: '/dashboard/manager'
      preLoaderRoute: typeof appdashboardDashboardManagerRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/company/document/': {
      id: '/(app)/company/document/'
      path: '/company/document'
      fullPath: '/company/document/'
      preLoaderRoute: typeof appCompanyDocumentIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/company/employee/': {
      id: '/(app)/company/employee/'
      path: '/company/employee'
      fullPath: '/company/employee/'
      preLoaderRoute: typeof appCompanyEmployeeIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/company/employee/$id': {
      id: '/(app)/company/employee/$id'
      path: '/company/employee/$id'
      fullPath: '/company/employee/$id'
      preLoaderRoute: typeof appCompanyEmployeeIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/company/employee/new': {
      id: '/(app)/company/employee/new'
      path: '/company/employee/new'
      fullPath: '/company/employee/new'
      preLoaderRoute: typeof appCompanyEmployeeNewRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/company/employee/update': {
      id: '/(app)/company/employee/update'
      path: '/company/employee/update'
      fullPath: '/company/employee/update'
      preLoaderRoute: typeof appCompanyEmployeeUpdateRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/company/organization/': {
      id: '/(app)/company/organization/'
      path: '/company/organization'
      fullPath: '/company/organization/'
      preLoaderRoute: typeof appCompanyOrganizationIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/company/organization/$id': {
      id: '/(app)/company/organization/$id'
      path: '/company/organization/$id'
      fullPath: '/company/organization/$id'
      preLoaderRoute: typeof appCompanyOrganizationIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/company/organization/new': {
      id: '/(app)/company/organization/new'
      path: '/company/organization/new'
      fullPath: '/company/organization/new'
      preLoaderRoute: typeof appCompanyOrganizationNewRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/company/organization/update': {
      id: '/(app)/company/organization/update'
      path: '/company/organization/update'
      fullPath: '/company/organization/update'
      preLoaderRoute: typeof appCompanyOrganizationUpdateRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/approval-workflow/': {
      id: '/(app)/settings/approval-workflow/'
      path: '/settings/approval-workflow'
      fullPath: '/settings/approval-workflow/'
      preLoaderRoute: typeof appSettingsApprovalWorkflowIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/approval-workflow/matrix': {
      id: '/(app)/settings/approval-workflow/matrix'
      path: '/settings/approval-workflow/matrix'
      fullPath: '/settings/approval-workflow/matrix'
      preLoaderRoute: typeof appSettingsApprovalWorkflowMatrixRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/approval-workflow/new': {
      id: '/(app)/settings/approval-workflow/new'
      path: '/settings/approval-workflow/new'
      fullPath: '/settings/approval-workflow/new'
      preLoaderRoute: typeof appSettingsApprovalWorkflowNewRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/company/': {
      id: '/(app)/settings/company/'
      path: '/settings/company'
      fullPath: '/settings/company/'
      preLoaderRoute: typeof appSettingsCompanyIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/master-data/': {
      id: '/(app)/settings/master-data/'
      path: '/settings/master-data'
      fullPath: '/settings/master-data/'
      preLoaderRoute: typeof appSettingsMasterDataIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/master-data/departments': {
      id: '/(app)/settings/master-data/departments'
      path: '/settings/master-data/departments'
      fullPath: '/settings/master-data/departments'
      preLoaderRoute: typeof appSettingsMasterDataDepartmentsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/master-data/divisions': {
      id: '/(app)/settings/master-data/divisions'
      path: '/settings/master-data/divisions'
      fullPath: '/settings/master-data/divisions'
      preLoaderRoute: typeof appSettingsMasterDataDivisionsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/master-data/grades': {
      id: '/(app)/settings/master-data/grades'
      path: '/settings/master-data/grades'
      fullPath: '/settings/master-data/grades'
      preLoaderRoute: typeof appSettingsMasterDataGradesRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/master-data/holidays': {
      id: '/(app)/settings/master-data/holidays'
      path: '/settings/master-data/holidays'
      fullPath: '/settings/master-data/holidays'
      preLoaderRoute: typeof appSettingsMasterDataHolidaysRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/master-data/import': {
      id: '/(app)/settings/master-data/import'
      path: '/settings/master-data/import'
      fullPath: '/settings/master-data/import'
      preLoaderRoute: typeof appSettingsMasterDataImportRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/master-data/leave-types': {
      id: '/(app)/settings/master-data/leave-types'
      path: '/settings/master-data/leave-types'
      fullPath: '/settings/master-data/leave-types'
      preLoaderRoute: typeof appSettingsMasterDataLeaveTypesRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/master-data/payroll-components': {
      id: '/(app)/settings/master-data/payroll-components'
      path: '/settings/master-data/payroll-components'
      fullPath: '/settings/master-data/payroll-components'
      preLoaderRoute: typeof appSettingsMasterDataPayrollComponentsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/master-data/positions': {
      id: '/(app)/settings/master-data/positions'
      path: '/settings/master-data/positions'
      fullPath: '/settings/master-data/positions'
      preLoaderRoute: typeof appSettingsMasterDataPositionsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/master-data/shifts': {
      id: '/(app)/settings/master-data/shifts'
      path: '/settings/master-data/shifts'
      fullPath: '/settings/master-data/shifts'
      preLoaderRoute: typeof appSettingsMasterDataShiftsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/notification/': {
      id: '/(app)/settings/notification/'
      path: '/settings/notification'
      fullPath: '/settings/notification/'
      preLoaderRoute: typeof appSettingsNotificationIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/security/': {
      id: '/(app)/settings/security/'
      path: '/settings/security'
      fullPath: '/settings/security/'
      preLoaderRoute: typeof appSettingsSecurityIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/user-role/': {
      id: '/(app)/settings/user-role/'
      path: '/settings/user-role'
      fullPath: '/settings/user-role/'
      preLoaderRoute: typeof appSettingsUserRoleIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/user-role/create-role': {
      id: '/(app)/settings/user-role/create-role'
      path: '/settings/user-role/create-role'
      fullPath: '/settings/user-role/create-role'
      preLoaderRoute: typeof appSettingsUserRoleCreateRoleRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/approval-workflow/$id/': {
      id: '/(app)/settings/approval-workflow/$id/'
      path: '/settings/approval-workflow/$id'
      fullPath: '/settings/approval-workflow/$id/'
      preLoaderRoute: typeof appSettingsApprovalWorkflowIdIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/approval-workflow/$id/conditions': {
      id: '/(app)/settings/approval-workflow/$id/conditions'
      path: '/settings/approval-workflow/$id/conditions'
      fullPath: '/settings/approval-workflow/$id/conditions'
      preLoaderRoute: typeof appSettingsApprovalWorkflowIdConditionsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/approval-workflow/$id/levels': {
      id: '/(app)/settings/approval-workflow/$id/levels'
      path: '/settings/approval-workflow/$id/levels'
      fullPath: '/settings/approval-workflow/$id/levels'
      preLoaderRoute: typeof appSettingsApprovalWorkflowIdLevelsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/approval-workflow/$id/test': {
      id: '/(app)/settings/approval-workflow/$id/test'
      path: '/settings/approval-workflow/$id/test'
      fullPath: '/settings/approval-workflow/$id/test'
      preLoaderRoute: typeof appSettingsApprovalWorkflowIdTestRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appdashboardIndexRoute: typeof appdashboardIndexRoute
  appApprovalIndexRoute: typeof appApprovalIndexRoute
  appAttendanceIndexRoute: typeof appAttendanceIndexRoute
  appLeaveIndexRoute: typeof appLeaveIndexRoute
  appPayrollIndexRoute: typeof appPayrollIndexRoute
  appPerformanceIndexRoute: typeof appPerformanceIndexRoute
  appReportIndexRoute: typeof appReportIndexRoute
  appdashboardDashboardCustomizeRoute: typeof appdashboardDashboardCustomizeRoute
  appdashboardDashboardEmployeeRoute: typeof appdashboardDashboardEmployeeRoute
  appdashboardDashboardExecutiveRoute: typeof appdashboardDashboardExecutiveRoute
  appdashboardDashboardHrRoute: typeof appdashboardDashboardHrRoute
  appdashboardDashboardManagerRoute: typeof appdashboardDashboardManagerRoute
  appCompanyEmployeeIdRoute: typeof appCompanyEmployeeIdRoute
  appCompanyEmployeeNewRoute: typeof appCompanyEmployeeNewRoute
  appCompanyEmployeeUpdateRoute: typeof appCompanyEmployeeUpdateRoute
  appCompanyOrganizationIdRoute: typeof appCompanyOrganizationIdRoute
  appCompanyOrganizationNewRoute: typeof appCompanyOrganizationNewRoute
  appCompanyOrganizationUpdateRoute: typeof appCompanyOrganizationUpdateRoute
  appSettingsApprovalWorkflowMatrixRoute: typeof appSettingsApprovalWorkflowMatrixRoute
  appSettingsApprovalWorkflowNewRoute: typeof appSettingsApprovalWorkflowNewRoute
  appSettingsMasterDataDepartmentsRoute: typeof appSettingsMasterDataDepartmentsRoute
  appSettingsMasterDataDivisionsRoute: typeof appSettingsMasterDataDivisionsRoute
  appSettingsMasterDataGradesRoute: typeof appSettingsMasterDataGradesRoute
  appSettingsMasterDataHolidaysRoute: typeof appSettingsMasterDataHolidaysRoute
  appSettingsMasterDataImportRoute: typeof appSettingsMasterDataImportRoute
  appSettingsMasterDataLeaveTypesRoute: typeof appSettingsMasterDataLeaveTypesRoute
  appSettingsMasterDataPayrollComponentsRoute: typeof appSettingsMasterDataPayrollComponentsRoute
  appSettingsMasterDataPositionsRoute: typeof appSettingsMasterDataPositionsRoute
  appSettingsMasterDataShiftsRoute: typeof appSettingsMasterDataShiftsRoute
  appSettingsUserRoleCreateRoleRoute: typeof appSettingsUserRoleCreateRoleRoute
  appCompanyDocumentIndexRoute: typeof appCompanyDocumentIndexRoute
  appCompanyEmployeeIndexRoute: typeof appCompanyEmployeeIndexRoute
  appCompanyOrganizationIndexRoute: typeof appCompanyOrganizationIndexRoute
  appSettingsApprovalWorkflowIndexRoute: typeof appSettingsApprovalWorkflowIndexRoute
  appSettingsCompanyIndexRoute: typeof appSettingsCompanyIndexRoute
  appSettingsMasterDataIndexRoute: typeof appSettingsMasterDataIndexRoute
  appSettingsNotificationIndexRoute: typeof appSettingsNotificationIndexRoute
  appSettingsSecurityIndexRoute: typeof appSettingsSecurityIndexRoute
  appSettingsUserRoleIndexRoute: typeof appSettingsUserRoleIndexRoute
  appSettingsApprovalWorkflowIdConditionsRoute: typeof appSettingsApprovalWorkflowIdConditionsRoute
  appSettingsApprovalWorkflowIdLevelsRoute: typeof appSettingsApprovalWorkflowIdLevelsRoute
  appSettingsApprovalWorkflowIdTestRoute: typeof appSettingsApprovalWorkflowIdTestRoute
  appSettingsApprovalWorkflowIdIndexRoute: typeof appSettingsApprovalWorkflowIdIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appdashboardIndexRoute: appdashboardIndexRoute,
  appApprovalIndexRoute: appApprovalIndexRoute,
  appAttendanceIndexRoute: appAttendanceIndexRoute,
  appLeaveIndexRoute: appLeaveIndexRoute,
  appPayrollIndexRoute: appPayrollIndexRoute,
  appPerformanceIndexRoute: appPerformanceIndexRoute,
  appReportIndexRoute: appReportIndexRoute,
  appdashboardDashboardCustomizeRoute: appdashboardDashboardCustomizeRoute,
  appdashboardDashboardEmployeeRoute: appdashboardDashboardEmployeeRoute,
  appdashboardDashboardExecutiveRoute: appdashboardDashboardExecutiveRoute,
  appdashboardDashboardHrRoute: appdashboardDashboardHrRoute,
  appdashboardDashboardManagerRoute: appdashboardDashboardManagerRoute,
  appCompanyEmployeeIdRoute: appCompanyEmployeeIdRoute,
  appCompanyEmployeeNewRoute: appCompanyEmployeeNewRoute,
  appCompanyEmployeeUpdateRoute: appCompanyEmployeeUpdateRoute,
  appCompanyOrganizationIdRoute: appCompanyOrganizationIdRoute,
  appCompanyOrganizationNewRoute: appCompanyOrganizationNewRoute,
  appCompanyOrganizationUpdateRoute: appCompanyOrganizationUpdateRoute,
  appSettingsApprovalWorkflowMatrixRoute:
    appSettingsApprovalWorkflowMatrixRoute,
  appSettingsApprovalWorkflowNewRoute: appSettingsApprovalWorkflowNewRoute,
  appSettingsMasterDataDepartmentsRoute: appSettingsMasterDataDepartmentsRoute,
  appSettingsMasterDataDivisionsRoute: appSettingsMasterDataDivisionsRoute,
  appSettingsMasterDataGradesRoute: appSettingsMasterDataGradesRoute,
  appSettingsMasterDataHolidaysRoute: appSettingsMasterDataHolidaysRoute,
  appSettingsMasterDataImportRoute: appSettingsMasterDataImportRoute,
  appSettingsMasterDataLeaveTypesRoute: appSettingsMasterDataLeaveTypesRoute,
  appSettingsMasterDataPayrollComponentsRoute:
    appSettingsMasterDataPayrollComponentsRoute,
  appSettingsMasterDataPositionsRoute: appSettingsMasterDataPositionsRoute,
  appSettingsMasterDataShiftsRoute: appSettingsMasterDataShiftsRoute,
  appSettingsUserRoleCreateRoleRoute: appSettingsUserRoleCreateRoleRoute,
  appCompanyDocumentIndexRoute: appCompanyDocumentIndexRoute,
  appCompanyEmployeeIndexRoute: appCompanyEmployeeIndexRoute,
  appCompanyOrganizationIndexRoute: appCompanyOrganizationIndexRoute,
  appSettingsApprovalWorkflowIndexRoute: appSettingsApprovalWorkflowIndexRoute,
  appSettingsCompanyIndexRoute: appSettingsCompanyIndexRoute,
  appSettingsMasterDataIndexRoute: appSettingsMasterDataIndexRoute,
  appSettingsNotificationIndexRoute: appSettingsNotificationIndexRoute,
  appSettingsSecurityIndexRoute: appSettingsSecurityIndexRoute,
  appSettingsUserRoleIndexRoute: appSettingsUserRoleIndexRoute,
  appSettingsApprovalWorkflowIdConditionsRoute:
    appSettingsApprovalWorkflowIdConditionsRoute,
  appSettingsApprovalWorkflowIdLevelsRoute:
    appSettingsApprovalWorkflowIdLevelsRoute,
  appSettingsApprovalWorkflowIdTestRoute:
    appSettingsApprovalWorkflowIdTestRoute,
  appSettingsApprovalWorkflowIdIndexRoute:
    appSettingsApprovalWorkflowIdIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authResetRoute: authResetRoute,
  authSigninRoute: authSigninRoute,
  authSignoutRoute: authSignoutRoute,
  authVerificationRoute: authVerificationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
