/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../routes/__root'
import { Route as appRouteRouteImport } from './../../routes/(app)/route'
import { Route as authResetRouteImport } from './../../routes/(auth)/reset'
import { Route as authSigninRouteImport } from './../../routes/(auth)/signin'
import { Route as authSignoutRouteImport } from './../../routes/(auth)/signout'
import { Route as authVerificationRouteImport } from './../../routes/(auth)/verification'
import { Route as appdashboardIndexRouteImport } from './../../routes/(app)/(dashboard)/index'
import { Route as appApprovalIndexRouteImport } from './../../routes/(app)/approval/index'
import { Route as appAttendanceIndexRouteImport } from './../../routes/(app)/attendance/index'
import { Route as appAttendanceAllMenuRouteImport } from './../../routes/(app)/attendance/all-menu'
import { Route as appAttendanceClockInOutRouteImport } from './../../routes/(app)/attendance/clock-in-out'
import { Route as appAttendanceFaceRecognitionRouteImport } from './../../routes/(app)/attendance/face-recognition'
import { Route as appAttendanceGpsSecurityRouteImport } from './../../routes/(app)/attendance/gps-security'
import { Route as appAttendanceHistoryRouteImport } from './../../routes/(app)/attendance/history'
import { Route as appAttendanceSettingsRouteImport } from './../../routes/(app)/attendance/settings'
import { Route as appLeaveIndexRouteImport } from './../../routes/(app)/leave/index'
import { Route as appLeaveBalanceRouteImport } from './../../routes/(app)/leave/balance'
import { Route as appLeaveHistoryRouteImport } from './../../routes/(app)/leave/history'
import { Route as appPayrollIndexRouteImport } from './../../routes/(app)/payroll/index'
import { Route as appPerformanceIndexRouteImport } from './../../routes/(app)/performance/index'
import { Route as appReportIndexRouteImport } from './../../routes/(app)/report/index'
import { Route as appdashboardDashboardCustomizeRouteImport } from './../../routes/(app)/(dashboard)/dashboard.customize'
import { Route as appdashboardDashboardEmployeeRouteImport } from './../../routes/(app)/(dashboard)/dashboard.employee'
import { Route as appdashboardDashboardExecutiveRouteImport } from './../../routes/(app)/(dashboard)/dashboard.executive'
import { Route as appdashboardDashboardHrRouteImport } from './../../routes/(app)/(dashboard)/dashboard.hr'
import { Route as appdashboardDashboardManagerRouteImport } from './../../routes/(app)/(dashboard)/dashboard.manager'
import { Route as appAttendanceApprovalIndexRouteImport } from './../../routes/(app)/attendance/approval/index'
import { Route as appAttendanceApprovalRequestIdRouteImport } from './../../routes/(app)/attendance/approval/$requestId'
import { Route as appAttendanceCalendarIndexRouteImport } from './../../routes/(app)/attendance/calendar/index'
import { Route as appAttendanceCalendarHolidaysRouteImport } from './../../routes/(app)/attendance/calendar/holidays'
import { Route as appAttendanceCalendarSettingsRouteImport } from './../../routes/(app)/attendance/calendar/settings'
import { Route as appAttendanceManagementIndexRouteImport } from './../../routes/(app)/attendance/management/index'
import { Route as appAttendanceManagementManualRouteImport } from './../../routes/(app)/attendance/management/manual'
import { Route as appAttendanceRequestsIndexRouteImport } from './../../routes/(app)/attendance/requests/index'
import { Route as appAttendanceRequestsNewRouteImport } from './../../routes/(app)/attendance/requests/new'
import { Route as appCompanyDocumentIndexRouteImport } from './../../routes/(app)/company/document/index'
import { Route as appCompanyEmployeeIndexRouteImport } from './../../routes/(app)/company/employee/index'
import { Route as appCompanyEmployeeIdRouteImport } from './../../routes/(app)/company/employee/$id'
import { Route as appCompanyEmployeeNewRouteImport } from './../../routes/(app)/company/employee/new'
import { Route as appCompanyEmployeeUpdateRouteImport } from './../../routes/(app)/company/employee/update'
import { Route as appCompanyOrganizationIndexRouteImport } from './../../routes/(app)/company/organization/index'
import { Route as appCompanyOrganizationIdRouteImport } from './../../routes/(app)/company/organization/$id'
import { Route as appCompanyOrganizationNewRouteImport } from './../../routes/(app)/company/organization/new'
import { Route as appCompanyOrganizationUpdateRouteImport } from './../../routes/(app)/company/organization/update'
import { Route as appLeaveApprovalIndexRouteImport } from './../../routes/(app)/leave/approval/index'
import { Route as appLeaveApprovalRequestIdRouteImport } from './../../routes/(app)/leave/approval/$requestId'
import { Route as appLeaveRequestsIndexRouteImport } from './../../routes/(app)/leave/requests/index'
import { Route as appLeaveRequestsRequestIdRouteImport } from './../../routes/(app)/leave/requests/$requestId'
import { Route as appLeaveRequestsNewRouteImport } from './../../routes/(app)/leave/requests/new'
import { Route as appSettingsApprovalWorkflowIndexRouteImport } from './../../routes/(app)/settings/approval-workflow/index'
import { Route as appSettingsApprovalWorkflowMatrixRouteImport } from './../../routes/(app)/settings/approval-workflow/matrix'
import { Route as appSettingsApprovalWorkflowNewRouteImport } from './../../routes/(app)/settings/approval-workflow/new'
import { Route as appSettingsCompanyIndexRouteImport } from './../../routes/(app)/settings/company/index'
import { Route as appSettingsMasterDataIndexRouteImport } from './../../routes/(app)/settings/master-data/index'
import { Route as appSettingsMasterDataDepartmentsRouteImport } from './../../routes/(app)/settings/master-data/departments'
import { Route as appSettingsMasterDataDivisionsRouteImport } from './../../routes/(app)/settings/master-data/divisions'
import { Route as appSettingsMasterDataGradesRouteImport } from './../../routes/(app)/settings/master-data/grades'
import { Route as appSettingsMasterDataHolidaysRouteImport } from './../../routes/(app)/settings/master-data/holidays'
import { Route as appSettingsMasterDataImportRouteImport } from './../../routes/(app)/settings/master-data/import'
import { Route as appSettingsMasterDataLeaveTypesRouteImport } from './../../routes/(app)/settings/master-data/leave-types'
import { Route as appSettingsMasterDataPayrollComponentsRouteImport } from './../../routes/(app)/settings/master-data/payroll-components'
import { Route as appSettingsMasterDataPositionsRouteImport } from './../../routes/(app)/settings/master-data/positions'
import { Route as appSettingsMasterDataShiftsRouteImport } from './../../routes/(app)/settings/master-data/shifts'
import { Route as appSettingsNotificationIndexRouteImport } from './../../routes/(app)/settings/notification/index'
import { Route as appSettingsRoleAccessIndexRouteImport } from './../../routes/(app)/settings/role-access/index'
import { Route as appSettingsRoleAccessCreateRoleRouteImport } from './../../routes/(app)/settings/role-access/create-role'
import { Route as appSettingsRoleAccessPermissionMatrixRouteImport } from './../../routes/(app)/settings/role-access/permission-matrix'
import { Route as appSettingsSecurityIndexRouteImport } from './../../routes/(app)/settings/security/index'
import { Route as appAttendanceApprovalRequestIdRejectRouteImport } from './../../routes/(app)/attendance/approval/$requestId/reject'
import { Route as appAttendanceManagementExceptionsExceptionIdRouteImport } from './../../routes/(app)/attendance/management/exceptions/$exceptionId'
import { Route as appAttendanceManagementShiftsIndexRouteImport } from './../../routes/(app)/attendance/management/shifts/index'
import { Route as appAttendanceManagementShiftsAssignmentsRouteImport } from './../../routes/(app)/attendance/management/shifts/assignments'
import { Route as appAttendanceManagementShiftsSetupRouteImport } from './../../routes/(app)/attendance/management/shifts/setup'
import { Route as appAttendanceManagementShiftsSwapsRouteImport } from './../../routes/(app)/attendance/management/shifts/swaps'
import { Route as appSettingsApprovalWorkflowIdIndexRouteImport } from './../../routes/(app)/settings/approval-workflow/$id/index'
import { Route as appSettingsApprovalWorkflowIdConditionsRouteImport } from './../../routes/(app)/settings/approval-workflow/$id/conditions'
import { Route as appSettingsApprovalWorkflowIdLevelsRouteImport } from './../../routes/(app)/settings/approval-workflow/$id/levels'
import { Route as appSettingsApprovalWorkflowIdTestRouteImport } from './../../routes/(app)/settings/approval-workflow/$id/test'
import { Route as appSettingsRoleAccessRoleIdAssignUsersRouteImport } from './../../routes/(app)/settings/role-access/$roleId/assign-users'
import { Route as appSettingsRoleAccessRoleIdEditRouteImport } from './../../routes/(app)/settings/role-access/$roleId/edit'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetRoute = authResetRouteImport.update({
  id: '/(auth)/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const authSigninRoute = authSigninRouteImport.update({
  id: '/(auth)/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignoutRoute = authSignoutRouteImport.update({
  id: '/(auth)/signout',
  path: '/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerificationRoute = authVerificationRouteImport.update({
  id: '/(auth)/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const appdashboardIndexRoute = appdashboardIndexRouteImport.update({
  id: '/(dashboard)/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const appApprovalIndexRoute = appApprovalIndexRouteImport.update({
  id: '/approval/',
  path: '/approval/',
  getParentRoute: () => appRouteRoute,
} as any)
const appAttendanceIndexRoute = appAttendanceIndexRouteImport.update({
  id: '/attendance/',
  path: '/attendance/',
  getParentRoute: () => appRouteRoute,
} as any)
const appAttendanceAllMenuRoute = appAttendanceAllMenuRouteImport.update({
  id: '/attendance/all-menu',
  path: '/attendance/all-menu',
  getParentRoute: () => appRouteRoute,
} as any)
const appAttendanceClockInOutRoute = appAttendanceClockInOutRouteImport.update({
  id: '/attendance/clock-in-out',
  path: '/attendance/clock-in-out',
  getParentRoute: () => appRouteRoute,
} as any)
const appAttendanceFaceRecognitionRoute =
  appAttendanceFaceRecognitionRouteImport.update({
    id: '/attendance/face-recognition',
    path: '/attendance/face-recognition',
    getParentRoute: () => appRouteRoute,
  } as any)
const appAttendanceGpsSecurityRoute =
  appAttendanceGpsSecurityRouteImport.update({
    id: '/attendance/gps-security',
    path: '/attendance/gps-security',
    getParentRoute: () => appRouteRoute,
  } as any)
const appAttendanceHistoryRoute = appAttendanceHistoryRouteImport.update({
  id: '/attendance/history',
  path: '/attendance/history',
  getParentRoute: () => appRouteRoute,
} as any)
const appAttendanceSettingsRoute = appAttendanceSettingsRouteImport.update({
  id: '/attendance/settings',
  path: '/attendance/settings',
  getParentRoute: () => appRouteRoute,
} as any)
const appLeaveIndexRoute = appLeaveIndexRouteImport.update({
  id: '/leave/',
  path: '/leave/',
  getParentRoute: () => appRouteRoute,
} as any)
const appLeaveBalanceRoute = appLeaveBalanceRouteImport.update({
  id: '/leave/balance',
  path: '/leave/balance',
  getParentRoute: () => appRouteRoute,
} as any)
const appLeaveHistoryRoute = appLeaveHistoryRouteImport.update({
  id: '/leave/history',
  path: '/leave/history',
  getParentRoute: () => appRouteRoute,
} as any)
const appPayrollIndexRoute = appPayrollIndexRouteImport.update({
  id: '/payroll/',
  path: '/payroll/',
  getParentRoute: () => appRouteRoute,
} as any)
const appPerformanceIndexRoute = appPerformanceIndexRouteImport.update({
  id: '/performance/',
  path: '/performance/',
  getParentRoute: () => appRouteRoute,
} as any)
const appReportIndexRoute = appReportIndexRouteImport.update({
  id: '/report/',
  path: '/report/',
  getParentRoute: () => appRouteRoute,
} as any)
const appdashboardDashboardCustomizeRoute =
  appdashboardDashboardCustomizeRouteImport.update({
    id: '/(dashboard)/dashboard/customize',
    path: '/dashboard/customize',
    getParentRoute: () => appRouteRoute,
  } as any)
const appdashboardDashboardEmployeeRoute =
  appdashboardDashboardEmployeeRouteImport.update({
    id: '/(dashboard)/dashboard/employee',
    path: '/dashboard/employee',
    getParentRoute: () => appRouteRoute,
  } as any)
const appdashboardDashboardExecutiveRoute =
  appdashboardDashboardExecutiveRouteImport.update({
    id: '/(dashboard)/dashboard/executive',
    path: '/dashboard/executive',
    getParentRoute: () => appRouteRoute,
  } as any)
const appdashboardDashboardHrRoute = appdashboardDashboardHrRouteImport.update({
  id: '/(dashboard)/dashboard/hr',
  path: '/dashboard/hr',
  getParentRoute: () => appRouteRoute,
} as any)
const appdashboardDashboardManagerRoute =
  appdashboardDashboardManagerRouteImport.update({
    id: '/(dashboard)/dashboard/manager',
    path: '/dashboard/manager',
    getParentRoute: () => appRouteRoute,
  } as any)
const appAttendanceApprovalIndexRoute =
  appAttendanceApprovalIndexRouteImport.update({
    id: '/attendance/approval/',
    path: '/attendance/approval/',
    getParentRoute: () => appRouteRoute,
  } as any)
const appAttendanceApprovalRequestIdRoute =
  appAttendanceApprovalRequestIdRouteImport.update({
    id: '/attendance/approval/$requestId',
    path: '/attendance/approval/$requestId',
    getParentRoute: () => appRouteRoute,
  } as any)
const appAttendanceCalendarIndexRoute =
  appAttendanceCalendarIndexRouteImport.update({
    id: '/attendance/calendar/',
    path: '/attendance/calendar/',
    getParentRoute: () => appRouteRoute,
  } as any)
const appAttendanceCalendarHolidaysRoute =
  appAttendanceCalendarHolidaysRouteImport.update({
    id: '/attendance/calendar/holidays',
    path: '/attendance/calendar/holidays',
    getParentRoute: () => appRouteRoute,
  } as any)
const appAttendanceCalendarSettingsRoute =
  appAttendanceCalendarSettingsRouteImport.update({
    id: '/attendance/calendar/settings',
    path: '/attendance/calendar/settings',
    getParentRoute: () => appRouteRoute,
  } as any)
const appAttendanceManagementIndexRoute =
  appAttendanceManagementIndexRouteImport.update({
    id: '/attendance/management/',
    path: '/attendance/management/',
    getParentRoute: () => appRouteRoute,
  } as any)
const appAttendanceManagementManualRoute =
  appAttendanceManagementManualRouteImport.update({
    id: '/attendance/management/manual',
    path: '/attendance/management/manual',
    getParentRoute: () => appRouteRoute,
  } as any)
const appAttendanceRequestsIndexRoute =
  appAttendanceRequestsIndexRouteImport.update({
    id: '/attendance/requests/',
    path: '/attendance/requests/',
    getParentRoute: () => appRouteRoute,
  } as any)
const appAttendanceRequestsNewRoute =
  appAttendanceRequestsNewRouteImport.update({
    id: '/attendance/requests/new',
    path: '/attendance/requests/new',
    getParentRoute: () => appRouteRoute,
  } as any)
const appCompanyDocumentIndexRoute = appCompanyDocumentIndexRouteImport.update({
  id: '/company/document/',
  path: '/company/document/',
  getParentRoute: () => appRouteRoute,
} as any)
const appCompanyEmployeeIndexRoute = appCompanyEmployeeIndexRouteImport.update({
  id: '/company/employee/',
  path: '/company/employee/',
  getParentRoute: () => appRouteRoute,
} as any)
const appCompanyEmployeeIdRoute = appCompanyEmployeeIdRouteImport.update({
  id: '/company/employee/$id',
  path: '/company/employee/$id',
  getParentRoute: () => appRouteRoute,
} as any)
const appCompanyEmployeeNewRoute = appCompanyEmployeeNewRouteImport.update({
  id: '/company/employee/new',
  path: '/company/employee/new',
  getParentRoute: () => appRouteRoute,
} as any)
const appCompanyEmployeeUpdateRoute =
  appCompanyEmployeeUpdateRouteImport.update({
    id: '/company/employee/update',
    path: '/company/employee/update',
    getParentRoute: () => appRouteRoute,
  } as any)
const appCompanyOrganizationIndexRoute =
  appCompanyOrganizationIndexRouteImport.update({
    id: '/company/organization/',
    path: '/company/organization/',
    getParentRoute: () => appRouteRoute,
  } as any)
const appCompanyOrganizationIdRoute =
  appCompanyOrganizationIdRouteImport.update({
    id: '/company/organization/$id',
    path: '/company/organization/$id',
    getParentRoute: () => appRouteRoute,
  } as any)
const appCompanyOrganizationNewRoute =
  appCompanyOrganizationNewRouteImport.update({
    id: '/company/organization/new',
    path: '/company/organization/new',
    getParentRoute: () => appRouteRoute,
  } as any)
const appCompanyOrganizationUpdateRoute =
  appCompanyOrganizationUpdateRouteImport.update({
    id: '/company/organization/update',
    path: '/company/organization/update',
    getParentRoute: () => appRouteRoute,
  } as any)
const appLeaveApprovalIndexRoute = appLeaveApprovalIndexRouteImport.update({
  id: '/leave/approval/',
  path: '/leave/approval/',
  getParentRoute: () => appRouteRoute,
} as any)
const appLeaveApprovalRequestIdRoute =
  appLeaveApprovalRequestIdRouteImport.update({
    id: '/leave/approval/$requestId',
    path: '/leave/approval/$requestId',
    getParentRoute: () => appRouteRoute,
  } as any)
const appLeaveRequestsIndexRoute = appLeaveRequestsIndexRouteImport.update({
  id: '/leave/requests/',
  path: '/leave/requests/',
  getParentRoute: () => appRouteRoute,
} as any)
const appLeaveRequestsRequestIdRoute =
  appLeaveRequestsRequestIdRouteImport.update({
    id: '/leave/requests/$requestId',
    path: '/leave/requests/$requestId',
    getParentRoute: () => appRouteRoute,
  } as any)
const appLeaveRequestsNewRoute = appLeaveRequestsNewRouteImport.update({
  id: '/leave/requests/new',
  path: '/leave/requests/new',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsApprovalWorkflowIndexRoute =
  appSettingsApprovalWorkflowIndexRouteImport.update({
    id: '/settings/approval-workflow/',
    path: '/settings/approval-workflow/',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsApprovalWorkflowMatrixRoute =
  appSettingsApprovalWorkflowMatrixRouteImport.update({
    id: '/settings/approval-workflow/matrix',
    path: '/settings/approval-workflow/matrix',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsApprovalWorkflowNewRoute =
  appSettingsApprovalWorkflowNewRouteImport.update({
    id: '/settings/approval-workflow/new',
    path: '/settings/approval-workflow/new',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsCompanyIndexRoute = appSettingsCompanyIndexRouteImport.update({
  id: '/settings/company/',
  path: '/settings/company/',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsMasterDataIndexRoute =
  appSettingsMasterDataIndexRouteImport.update({
    id: '/settings/master-data/',
    path: '/settings/master-data/',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsMasterDataDepartmentsRoute =
  appSettingsMasterDataDepartmentsRouteImport.update({
    id: '/settings/master-data/departments',
    path: '/settings/master-data/departments',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsMasterDataDivisionsRoute =
  appSettingsMasterDataDivisionsRouteImport.update({
    id: '/settings/master-data/divisions',
    path: '/settings/master-data/divisions',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsMasterDataGradesRoute =
  appSettingsMasterDataGradesRouteImport.update({
    id: '/settings/master-data/grades',
    path: '/settings/master-data/grades',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsMasterDataHolidaysRoute =
  appSettingsMasterDataHolidaysRouteImport.update({
    id: '/settings/master-data/holidays',
    path: '/settings/master-data/holidays',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsMasterDataImportRoute =
  appSettingsMasterDataImportRouteImport.update({
    id: '/settings/master-data/import',
    path: '/settings/master-data/import',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsMasterDataLeaveTypesRoute =
  appSettingsMasterDataLeaveTypesRouteImport.update({
    id: '/settings/master-data/leave-types',
    path: '/settings/master-data/leave-types',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsMasterDataPayrollComponentsRoute =
  appSettingsMasterDataPayrollComponentsRouteImport.update({
    id: '/settings/master-data/payroll-components',
    path: '/settings/master-data/payroll-components',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsMasterDataPositionsRoute =
  appSettingsMasterDataPositionsRouteImport.update({
    id: '/settings/master-data/positions',
    path: '/settings/master-data/positions',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsMasterDataShiftsRoute =
  appSettingsMasterDataShiftsRouteImport.update({
    id: '/settings/master-data/shifts',
    path: '/settings/master-data/shifts',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsNotificationIndexRoute =
  appSettingsNotificationIndexRouteImport.update({
    id: '/settings/notification/',
    path: '/settings/notification/',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsRoleAccessIndexRoute =
  appSettingsRoleAccessIndexRouteImport.update({
    id: '/settings/role-access/',
    path: '/settings/role-access/',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsRoleAccessCreateRoleRoute =
  appSettingsRoleAccessCreateRoleRouteImport.update({
    id: '/settings/role-access/create-role',
    path: '/settings/role-access/create-role',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsRoleAccessPermissionMatrixRoute =
  appSettingsRoleAccessPermissionMatrixRouteImport.update({
    id: '/settings/role-access/permission-matrix',
    path: '/settings/role-access/permission-matrix',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsSecurityIndexRoute =
  appSettingsSecurityIndexRouteImport.update({
    id: '/settings/security/',
    path: '/settings/security/',
    getParentRoute: () => appRouteRoute,
  } as any)
const appAttendanceApprovalRequestIdRejectRoute =
  appAttendanceApprovalRequestIdRejectRouteImport.update({
    id: '/reject',
    path: '/reject',
    getParentRoute: () => appAttendanceApprovalRequestIdRoute,
  } as any)
const appAttendanceManagementExceptionsExceptionIdRoute =
  appAttendanceManagementExceptionsExceptionIdRouteImport.update({
    id: '/attendance/management/exceptions/$exceptionId',
    path: '/attendance/management/exceptions/$exceptionId',
    getParentRoute: () => appRouteRoute,
  } as any)
const appAttendanceManagementShiftsIndexRoute =
  appAttendanceManagementShiftsIndexRouteImport.update({
    id: '/attendance/management/shifts/',
    path: '/attendance/management/shifts/',
    getParentRoute: () => appRouteRoute,
  } as any)
const appAttendanceManagementShiftsAssignmentsRoute =
  appAttendanceManagementShiftsAssignmentsRouteImport.update({
    id: '/attendance/management/shifts/assignments',
    path: '/attendance/management/shifts/assignments',
    getParentRoute: () => appRouteRoute,
  } as any)
const appAttendanceManagementShiftsSetupRoute =
  appAttendanceManagementShiftsSetupRouteImport.update({
    id: '/attendance/management/shifts/setup',
    path: '/attendance/management/shifts/setup',
    getParentRoute: () => appRouteRoute,
  } as any)
const appAttendanceManagementShiftsSwapsRoute =
  appAttendanceManagementShiftsSwapsRouteImport.update({
    id: '/attendance/management/shifts/swaps',
    path: '/attendance/management/shifts/swaps',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsApprovalWorkflowIdIndexRoute =
  appSettingsApprovalWorkflowIdIndexRouteImport.update({
    id: '/settings/approval-workflow/$id/',
    path: '/settings/approval-workflow/$id/',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsApprovalWorkflowIdConditionsRoute =
  appSettingsApprovalWorkflowIdConditionsRouteImport.update({
    id: '/settings/approval-workflow/$id/conditions',
    path: '/settings/approval-workflow/$id/conditions',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsApprovalWorkflowIdLevelsRoute =
  appSettingsApprovalWorkflowIdLevelsRouteImport.update({
    id: '/settings/approval-workflow/$id/levels',
    path: '/settings/approval-workflow/$id/levels',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsApprovalWorkflowIdTestRoute =
  appSettingsApprovalWorkflowIdTestRouteImport.update({
    id: '/settings/approval-workflow/$id/test',
    path: '/settings/approval-workflow/$id/test',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsRoleAccessRoleIdAssignUsersRoute =
  appSettingsRoleAccessRoleIdAssignUsersRouteImport.update({
    id: '/settings/role-access/$roleId/assign-users',
    path: '/settings/role-access/$roleId/assign-users',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsRoleAccessRoleIdEditRoute =
  appSettingsRoleAccessRoleIdEditRouteImport.update({
    id: '/settings/role-access/$roleId/edit',
    path: '/settings/role-access/$roleId/edit',
    getParentRoute: () => appRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/reset': typeof authResetRoute
  '/signin': typeof authSigninRoute
  '/signout': typeof authSignoutRoute
  '/verification': typeof authVerificationRoute
  '/attendance/all-menu': typeof appAttendanceAllMenuRoute
  '/attendance/clock-in-out': typeof appAttendanceClockInOutRoute
  '/attendance/face-recognition': typeof appAttendanceFaceRecognitionRoute
  '/attendance/gps-security': typeof appAttendanceGpsSecurityRoute
  '/attendance/history': typeof appAttendanceHistoryRoute
  '/attendance/settings': typeof appAttendanceSettingsRoute
  '/leave/balance': typeof appLeaveBalanceRoute
  '/leave/history': typeof appLeaveHistoryRoute
  '/': typeof appdashboardIndexRoute
  '/approval/': typeof appApprovalIndexRoute
  '/attendance/': typeof appAttendanceIndexRoute
  '/leave/': typeof appLeaveIndexRoute
  '/payroll/': typeof appPayrollIndexRoute
  '/performance/': typeof appPerformanceIndexRoute
  '/report/': typeof appReportIndexRoute
  '/dashboard/customize': typeof appdashboardDashboardCustomizeRoute
  '/dashboard/employee': typeof appdashboardDashboardEmployeeRoute
  '/dashboard/executive': typeof appdashboardDashboardExecutiveRoute
  '/dashboard/hr': typeof appdashboardDashboardHrRoute
  '/dashboard/manager': typeof appdashboardDashboardManagerRoute
  '/attendance/approval/$requestId': typeof appAttendanceApprovalRequestIdRouteWithChildren
  '/attendance/calendar/holidays': typeof appAttendanceCalendarHolidaysRoute
  '/attendance/calendar/settings': typeof appAttendanceCalendarSettingsRoute
  '/attendance/management/manual': typeof appAttendanceManagementManualRoute
  '/attendance/requests/new': typeof appAttendanceRequestsNewRoute
  '/company/employee/$id': typeof appCompanyEmployeeIdRoute
  '/company/employee/new': typeof appCompanyEmployeeNewRoute
  '/company/employee/update': typeof appCompanyEmployeeUpdateRoute
  '/company/organization/$id': typeof appCompanyOrganizationIdRoute
  '/company/organization/new': typeof appCompanyOrganizationNewRoute
  '/company/organization/update': typeof appCompanyOrganizationUpdateRoute
  '/leave/approval/$requestId': typeof appLeaveApprovalRequestIdRoute
  '/leave/requests/$requestId': typeof appLeaveRequestsRequestIdRoute
  '/leave/requests/new': typeof appLeaveRequestsNewRoute
  '/settings/approval-workflow/matrix': typeof appSettingsApprovalWorkflowMatrixRoute
  '/settings/approval-workflow/new': typeof appSettingsApprovalWorkflowNewRoute
  '/settings/master-data/departments': typeof appSettingsMasterDataDepartmentsRoute
  '/settings/master-data/divisions': typeof appSettingsMasterDataDivisionsRoute
  '/settings/master-data/grades': typeof appSettingsMasterDataGradesRoute
  '/settings/master-data/holidays': typeof appSettingsMasterDataHolidaysRoute
  '/settings/master-data/import': typeof appSettingsMasterDataImportRoute
  '/settings/master-data/leave-types': typeof appSettingsMasterDataLeaveTypesRoute
  '/settings/master-data/payroll-components': typeof appSettingsMasterDataPayrollComponentsRoute
  '/settings/master-data/positions': typeof appSettingsMasterDataPositionsRoute
  '/settings/master-data/shifts': typeof appSettingsMasterDataShiftsRoute
  '/settings/role-access/create-role': typeof appSettingsRoleAccessCreateRoleRoute
  '/settings/role-access/permission-matrix': typeof appSettingsRoleAccessPermissionMatrixRoute
  '/attendance/approval/': typeof appAttendanceApprovalIndexRoute
  '/attendance/calendar/': typeof appAttendanceCalendarIndexRoute
  '/attendance/management/': typeof appAttendanceManagementIndexRoute
  '/attendance/requests/': typeof appAttendanceRequestsIndexRoute
  '/company/document/': typeof appCompanyDocumentIndexRoute
  '/company/employee/': typeof appCompanyEmployeeIndexRoute
  '/company/organization/': typeof appCompanyOrganizationIndexRoute
  '/leave/approval/': typeof appLeaveApprovalIndexRoute
  '/leave/requests/': typeof appLeaveRequestsIndexRoute
  '/settings/approval-workflow/': typeof appSettingsApprovalWorkflowIndexRoute
  '/settings/company/': typeof appSettingsCompanyIndexRoute
  '/settings/master-data/': typeof appSettingsMasterDataIndexRoute
  '/settings/notification/': typeof appSettingsNotificationIndexRoute
  '/settings/role-access/': typeof appSettingsRoleAccessIndexRoute
  '/settings/security/': typeof appSettingsSecurityIndexRoute
  '/attendance/approval/$requestId/reject': typeof appAttendanceApprovalRequestIdRejectRoute
  '/attendance/management/exceptions/$exceptionId': typeof appAttendanceManagementExceptionsExceptionIdRoute
  '/attendance/management/shifts/assignments': typeof appAttendanceManagementShiftsAssignmentsRoute
  '/attendance/management/shifts/setup': typeof appAttendanceManagementShiftsSetupRoute
  '/attendance/management/shifts/swaps': typeof appAttendanceManagementShiftsSwapsRoute
  '/settings/approval-workflow/$id/conditions': typeof appSettingsApprovalWorkflowIdConditionsRoute
  '/settings/approval-workflow/$id/levels': typeof appSettingsApprovalWorkflowIdLevelsRoute
  '/settings/approval-workflow/$id/test': typeof appSettingsApprovalWorkflowIdTestRoute
  '/settings/role-access/$roleId/assign-users': typeof appSettingsRoleAccessRoleIdAssignUsersRoute
  '/settings/role-access/$roleId/edit': typeof appSettingsRoleAccessRoleIdEditRoute
  '/attendance/management/shifts/': typeof appAttendanceManagementShiftsIndexRoute
  '/settings/approval-workflow/$id/': typeof appSettingsApprovalWorkflowIdIndexRoute
}
export interface FileRoutesByTo {
  '/reset': typeof authResetRoute
  '/signin': typeof authSigninRoute
  '/signout': typeof authSignoutRoute
  '/verification': typeof authVerificationRoute
  '/attendance/all-menu': typeof appAttendanceAllMenuRoute
  '/attendance/clock-in-out': typeof appAttendanceClockInOutRoute
  '/attendance/face-recognition': typeof appAttendanceFaceRecognitionRoute
  '/attendance/gps-security': typeof appAttendanceGpsSecurityRoute
  '/attendance/history': typeof appAttendanceHistoryRoute
  '/attendance/settings': typeof appAttendanceSettingsRoute
  '/leave/balance': typeof appLeaveBalanceRoute
  '/leave/history': typeof appLeaveHistoryRoute
  '/': typeof appdashboardIndexRoute
  '/approval': typeof appApprovalIndexRoute
  '/attendance': typeof appAttendanceIndexRoute
  '/leave': typeof appLeaveIndexRoute
  '/payroll': typeof appPayrollIndexRoute
  '/performance': typeof appPerformanceIndexRoute
  '/report': typeof appReportIndexRoute
  '/dashboard/customize': typeof appdashboardDashboardCustomizeRoute
  '/dashboard/employee': typeof appdashboardDashboardEmployeeRoute
  '/dashboard/executive': typeof appdashboardDashboardExecutiveRoute
  '/dashboard/hr': typeof appdashboardDashboardHrRoute
  '/dashboard/manager': typeof appdashboardDashboardManagerRoute
  '/attendance/approval/$requestId': typeof appAttendanceApprovalRequestIdRouteWithChildren
  '/attendance/calendar/holidays': typeof appAttendanceCalendarHolidaysRoute
  '/attendance/calendar/settings': typeof appAttendanceCalendarSettingsRoute
  '/attendance/management/manual': typeof appAttendanceManagementManualRoute
  '/attendance/requests/new': typeof appAttendanceRequestsNewRoute
  '/company/employee/$id': typeof appCompanyEmployeeIdRoute
  '/company/employee/new': typeof appCompanyEmployeeNewRoute
  '/company/employee/update': typeof appCompanyEmployeeUpdateRoute
  '/company/organization/$id': typeof appCompanyOrganizationIdRoute
  '/company/organization/new': typeof appCompanyOrganizationNewRoute
  '/company/organization/update': typeof appCompanyOrganizationUpdateRoute
  '/leave/approval/$requestId': typeof appLeaveApprovalRequestIdRoute
  '/leave/requests/$requestId': typeof appLeaveRequestsRequestIdRoute
  '/leave/requests/new': typeof appLeaveRequestsNewRoute
  '/settings/approval-workflow/matrix': typeof appSettingsApprovalWorkflowMatrixRoute
  '/settings/approval-workflow/new': typeof appSettingsApprovalWorkflowNewRoute
  '/settings/master-data/departments': typeof appSettingsMasterDataDepartmentsRoute
  '/settings/master-data/divisions': typeof appSettingsMasterDataDivisionsRoute
  '/settings/master-data/grades': typeof appSettingsMasterDataGradesRoute
  '/settings/master-data/holidays': typeof appSettingsMasterDataHolidaysRoute
  '/settings/master-data/import': typeof appSettingsMasterDataImportRoute
  '/settings/master-data/leave-types': typeof appSettingsMasterDataLeaveTypesRoute
  '/settings/master-data/payroll-components': typeof appSettingsMasterDataPayrollComponentsRoute
  '/settings/master-data/positions': typeof appSettingsMasterDataPositionsRoute
  '/settings/master-data/shifts': typeof appSettingsMasterDataShiftsRoute
  '/settings/role-access/create-role': typeof appSettingsRoleAccessCreateRoleRoute
  '/settings/role-access/permission-matrix': typeof appSettingsRoleAccessPermissionMatrixRoute
  '/attendance/approval': typeof appAttendanceApprovalIndexRoute
  '/attendance/calendar': typeof appAttendanceCalendarIndexRoute
  '/attendance/management': typeof appAttendanceManagementIndexRoute
  '/attendance/requests': typeof appAttendanceRequestsIndexRoute
  '/company/document': typeof appCompanyDocumentIndexRoute
  '/company/employee': typeof appCompanyEmployeeIndexRoute
  '/company/organization': typeof appCompanyOrganizationIndexRoute
  '/leave/approval': typeof appLeaveApprovalIndexRoute
  '/leave/requests': typeof appLeaveRequestsIndexRoute
  '/settings/approval-workflow': typeof appSettingsApprovalWorkflowIndexRoute
  '/settings/company': typeof appSettingsCompanyIndexRoute
  '/settings/master-data': typeof appSettingsMasterDataIndexRoute
  '/settings/notification': typeof appSettingsNotificationIndexRoute
  '/settings/role-access': typeof appSettingsRoleAccessIndexRoute
  '/settings/security': typeof appSettingsSecurityIndexRoute
  '/attendance/approval/$requestId/reject': typeof appAttendanceApprovalRequestIdRejectRoute
  '/attendance/management/exceptions/$exceptionId': typeof appAttendanceManagementExceptionsExceptionIdRoute
  '/attendance/management/shifts/assignments': typeof appAttendanceManagementShiftsAssignmentsRoute
  '/attendance/management/shifts/setup': typeof appAttendanceManagementShiftsSetupRoute
  '/attendance/management/shifts/swaps': typeof appAttendanceManagementShiftsSwapsRoute
  '/settings/approval-workflow/$id/conditions': typeof appSettingsApprovalWorkflowIdConditionsRoute
  '/settings/approval-workflow/$id/levels': typeof appSettingsApprovalWorkflowIdLevelsRoute
  '/settings/approval-workflow/$id/test': typeof appSettingsApprovalWorkflowIdTestRoute
  '/settings/role-access/$roleId/assign-users': typeof appSettingsRoleAccessRoleIdAssignUsersRoute
  '/settings/role-access/$roleId/edit': typeof appSettingsRoleAccessRoleIdEditRoute
  '/attendance/management/shifts': typeof appAttendanceManagementShiftsIndexRoute
  '/settings/approval-workflow/$id': typeof appSettingsApprovalWorkflowIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)/reset': typeof authResetRoute
  '/(auth)/signin': typeof authSigninRoute
  '/(auth)/signout': typeof authSignoutRoute
  '/(auth)/verification': typeof authVerificationRoute
  '/(app)/attendance/all-menu': typeof appAttendanceAllMenuRoute
  '/(app)/attendance/clock-in-out': typeof appAttendanceClockInOutRoute
  '/(app)/attendance/face-recognition': typeof appAttendanceFaceRecognitionRoute
  '/(app)/attendance/gps-security': typeof appAttendanceGpsSecurityRoute
  '/(app)/attendance/history': typeof appAttendanceHistoryRoute
  '/(app)/attendance/settings': typeof appAttendanceSettingsRoute
  '/(app)/leave/balance': typeof appLeaveBalanceRoute
  '/(app)/leave/history': typeof appLeaveHistoryRoute
  '/(app)/(dashboard)/': typeof appdashboardIndexRoute
  '/(app)/approval/': typeof appApprovalIndexRoute
  '/(app)/attendance/': typeof appAttendanceIndexRoute
  '/(app)/leave/': typeof appLeaveIndexRoute
  '/(app)/payroll/': typeof appPayrollIndexRoute
  '/(app)/performance/': typeof appPerformanceIndexRoute
  '/(app)/report/': typeof appReportIndexRoute
  '/(app)/(dashboard)/dashboard/customize': typeof appdashboardDashboardCustomizeRoute
  '/(app)/(dashboard)/dashboard/employee': typeof appdashboardDashboardEmployeeRoute
  '/(app)/(dashboard)/dashboard/executive': typeof appdashboardDashboardExecutiveRoute
  '/(app)/(dashboard)/dashboard/hr': typeof appdashboardDashboardHrRoute
  '/(app)/(dashboard)/dashboard/manager': typeof appdashboardDashboardManagerRoute
  '/(app)/attendance/approval/$requestId': typeof appAttendanceApprovalRequestIdRouteWithChildren
  '/(app)/attendance/calendar/holidays': typeof appAttendanceCalendarHolidaysRoute
  '/(app)/attendance/calendar/settings': typeof appAttendanceCalendarSettingsRoute
  '/(app)/attendance/management/manual': typeof appAttendanceManagementManualRoute
  '/(app)/attendance/requests/new': typeof appAttendanceRequestsNewRoute
  '/(app)/company/employee/$id': typeof appCompanyEmployeeIdRoute
  '/(app)/company/employee/new': typeof appCompanyEmployeeNewRoute
  '/(app)/company/employee/update': typeof appCompanyEmployeeUpdateRoute
  '/(app)/company/organization/$id': typeof appCompanyOrganizationIdRoute
  '/(app)/company/organization/new': typeof appCompanyOrganizationNewRoute
  '/(app)/company/organization/update': typeof appCompanyOrganizationUpdateRoute
  '/(app)/leave/approval/$requestId': typeof appLeaveApprovalRequestIdRoute
  '/(app)/leave/requests/$requestId': typeof appLeaveRequestsRequestIdRoute
  '/(app)/leave/requests/new': typeof appLeaveRequestsNewRoute
  '/(app)/settings/approval-workflow/matrix': typeof appSettingsApprovalWorkflowMatrixRoute
  '/(app)/settings/approval-workflow/new': typeof appSettingsApprovalWorkflowNewRoute
  '/(app)/settings/master-data/departments': typeof appSettingsMasterDataDepartmentsRoute
  '/(app)/settings/master-data/divisions': typeof appSettingsMasterDataDivisionsRoute
  '/(app)/settings/master-data/grades': typeof appSettingsMasterDataGradesRoute
  '/(app)/settings/master-data/holidays': typeof appSettingsMasterDataHolidaysRoute
  '/(app)/settings/master-data/import': typeof appSettingsMasterDataImportRoute
  '/(app)/settings/master-data/leave-types': typeof appSettingsMasterDataLeaveTypesRoute
  '/(app)/settings/master-data/payroll-components': typeof appSettingsMasterDataPayrollComponentsRoute
  '/(app)/settings/master-data/positions': typeof appSettingsMasterDataPositionsRoute
  '/(app)/settings/master-data/shifts': typeof appSettingsMasterDataShiftsRoute
  '/(app)/settings/role-access/create-role': typeof appSettingsRoleAccessCreateRoleRoute
  '/(app)/settings/role-access/permission-matrix': typeof appSettingsRoleAccessPermissionMatrixRoute
  '/(app)/attendance/approval/': typeof appAttendanceApprovalIndexRoute
  '/(app)/attendance/calendar/': typeof appAttendanceCalendarIndexRoute
  '/(app)/attendance/management/': typeof appAttendanceManagementIndexRoute
  '/(app)/attendance/requests/': typeof appAttendanceRequestsIndexRoute
  '/(app)/company/document/': typeof appCompanyDocumentIndexRoute
  '/(app)/company/employee/': typeof appCompanyEmployeeIndexRoute
  '/(app)/company/organization/': typeof appCompanyOrganizationIndexRoute
  '/(app)/leave/approval/': typeof appLeaveApprovalIndexRoute
  '/(app)/leave/requests/': typeof appLeaveRequestsIndexRoute
  '/(app)/settings/approval-workflow/': typeof appSettingsApprovalWorkflowIndexRoute
  '/(app)/settings/company/': typeof appSettingsCompanyIndexRoute
  '/(app)/settings/master-data/': typeof appSettingsMasterDataIndexRoute
  '/(app)/settings/notification/': typeof appSettingsNotificationIndexRoute
  '/(app)/settings/role-access/': typeof appSettingsRoleAccessIndexRoute
  '/(app)/settings/security/': typeof appSettingsSecurityIndexRoute
  '/(app)/attendance/approval/$requestId/reject': typeof appAttendanceApprovalRequestIdRejectRoute
  '/(app)/attendance/management/exceptions/$exceptionId': typeof appAttendanceManagementExceptionsExceptionIdRoute
  '/(app)/attendance/management/shifts/assignments': typeof appAttendanceManagementShiftsAssignmentsRoute
  '/(app)/attendance/management/shifts/setup': typeof appAttendanceManagementShiftsSetupRoute
  '/(app)/attendance/management/shifts/swaps': typeof appAttendanceManagementShiftsSwapsRoute
  '/(app)/settings/approval-workflow/$id/conditions': typeof appSettingsApprovalWorkflowIdConditionsRoute
  '/(app)/settings/approval-workflow/$id/levels': typeof appSettingsApprovalWorkflowIdLevelsRoute
  '/(app)/settings/approval-workflow/$id/test': typeof appSettingsApprovalWorkflowIdTestRoute
  '/(app)/settings/role-access/$roleId/assign-users': typeof appSettingsRoleAccessRoleIdAssignUsersRoute
  '/(app)/settings/role-access/$roleId/edit': typeof appSettingsRoleAccessRoleIdEditRoute
  '/(app)/attendance/management/shifts/': typeof appAttendanceManagementShiftsIndexRoute
  '/(app)/settings/approval-workflow/$id/': typeof appSettingsApprovalWorkflowIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/reset'
    | '/signin'
    | '/signout'
    | '/verification'
    | '/attendance/all-menu'
    | '/attendance/clock-in-out'
    | '/attendance/face-recognition'
    | '/attendance/gps-security'
    | '/attendance/history'
    | '/attendance/settings'
    | '/leave/balance'
    | '/leave/history'
    | '/'
    | '/approval/'
    | '/attendance/'
    | '/leave/'
    | '/payroll/'
    | '/performance/'
    | '/report/'
    | '/dashboard/customize'
    | '/dashboard/employee'
    | '/dashboard/executive'
    | '/dashboard/hr'
    | '/dashboard/manager'
    | '/attendance/approval/$requestId'
    | '/attendance/calendar/holidays'
    | '/attendance/calendar/settings'
    | '/attendance/management/manual'
    | '/attendance/requests/new'
    | '/company/employee/$id'
    | '/company/employee/new'
    | '/company/employee/update'
    | '/company/organization/$id'
    | '/company/organization/new'
    | '/company/organization/update'
    | '/leave/approval/$requestId'
    | '/leave/requests/$requestId'
    | '/leave/requests/new'
    | '/settings/approval-workflow/matrix'
    | '/settings/approval-workflow/new'
    | '/settings/master-data/departments'
    | '/settings/master-data/divisions'
    | '/settings/master-data/grades'
    | '/settings/master-data/holidays'
    | '/settings/master-data/import'
    | '/settings/master-data/leave-types'
    | '/settings/master-data/payroll-components'
    | '/settings/master-data/positions'
    | '/settings/master-data/shifts'
    | '/settings/role-access/create-role'
    | '/settings/role-access/permission-matrix'
    | '/attendance/approval/'
    | '/attendance/calendar/'
    | '/attendance/management/'
    | '/attendance/requests/'
    | '/company/document/'
    | '/company/employee/'
    | '/company/organization/'
    | '/leave/approval/'
    | '/leave/requests/'
    | '/settings/approval-workflow/'
    | '/settings/company/'
    | '/settings/master-data/'
    | '/settings/notification/'
    | '/settings/role-access/'
    | '/settings/security/'
    | '/attendance/approval/$requestId/reject'
    | '/attendance/management/exceptions/$exceptionId'
    | '/attendance/management/shifts/assignments'
    | '/attendance/management/shifts/setup'
    | '/attendance/management/shifts/swaps'
    | '/settings/approval-workflow/$id/conditions'
    | '/settings/approval-workflow/$id/levels'
    | '/settings/approval-workflow/$id/test'
    | '/settings/role-access/$roleId/assign-users'
    | '/settings/role-access/$roleId/edit'
    | '/attendance/management/shifts/'
    | '/settings/approval-workflow/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/reset'
    | '/signin'
    | '/signout'
    | '/verification'
    | '/attendance/all-menu'
    | '/attendance/clock-in-out'
    | '/attendance/face-recognition'
    | '/attendance/gps-security'
    | '/attendance/history'
    | '/attendance/settings'
    | '/leave/balance'
    | '/leave/history'
    | '/'
    | '/approval'
    | '/attendance'
    | '/leave'
    | '/payroll'
    | '/performance'
    | '/report'
    | '/dashboard/customize'
    | '/dashboard/employee'
    | '/dashboard/executive'
    | '/dashboard/hr'
    | '/dashboard/manager'
    | '/attendance/approval/$requestId'
    | '/attendance/calendar/holidays'
    | '/attendance/calendar/settings'
    | '/attendance/management/manual'
    | '/attendance/requests/new'
    | '/company/employee/$id'
    | '/company/employee/new'
    | '/company/employee/update'
    | '/company/organization/$id'
    | '/company/organization/new'
    | '/company/organization/update'
    | '/leave/approval/$requestId'
    | '/leave/requests/$requestId'
    | '/leave/requests/new'
    | '/settings/approval-workflow/matrix'
    | '/settings/approval-workflow/new'
    | '/settings/master-data/departments'
    | '/settings/master-data/divisions'
    | '/settings/master-data/grades'
    | '/settings/master-data/holidays'
    | '/settings/master-data/import'
    | '/settings/master-data/leave-types'
    | '/settings/master-data/payroll-components'
    | '/settings/master-data/positions'
    | '/settings/master-data/shifts'
    | '/settings/role-access/create-role'
    | '/settings/role-access/permission-matrix'
    | '/attendance/approval'
    | '/attendance/calendar'
    | '/attendance/management'
    | '/attendance/requests'
    | '/company/document'
    | '/company/employee'
    | '/company/organization'
    | '/leave/approval'
    | '/leave/requests'
    | '/settings/approval-workflow'
    | '/settings/company'
    | '/settings/master-data'
    | '/settings/notification'
    | '/settings/role-access'
    | '/settings/security'
    | '/attendance/approval/$requestId/reject'
    | '/attendance/management/exceptions/$exceptionId'
    | '/attendance/management/shifts/assignments'
    | '/attendance/management/shifts/setup'
    | '/attendance/management/shifts/swaps'
    | '/settings/approval-workflow/$id/conditions'
    | '/settings/approval-workflow/$id/levels'
    | '/settings/approval-workflow/$id/test'
    | '/settings/role-access/$roleId/assign-users'
    | '/settings/role-access/$roleId/edit'
    | '/attendance/management/shifts'
    | '/settings/approval-workflow/$id'
  id:
    | '__root__'
    | '/(app)'
    | '/(auth)/reset'
    | '/(auth)/signin'
    | '/(auth)/signout'
    | '/(auth)/verification'
    | '/(app)/attendance/all-menu'
    | '/(app)/attendance/clock-in-out'
    | '/(app)/attendance/face-recognition'
    | '/(app)/attendance/gps-security'
    | '/(app)/attendance/history'
    | '/(app)/attendance/settings'
    | '/(app)/leave/balance'
    | '/(app)/leave/history'
    | '/(app)/(dashboard)/'
    | '/(app)/approval/'
    | '/(app)/attendance/'
    | '/(app)/leave/'
    | '/(app)/payroll/'
    | '/(app)/performance/'
    | '/(app)/report/'
    | '/(app)/(dashboard)/dashboard/customize'
    | '/(app)/(dashboard)/dashboard/employee'
    | '/(app)/(dashboard)/dashboard/executive'
    | '/(app)/(dashboard)/dashboard/hr'
    | '/(app)/(dashboard)/dashboard/manager'
    | '/(app)/attendance/approval/$requestId'
    | '/(app)/attendance/calendar/holidays'
    | '/(app)/attendance/calendar/settings'
    | '/(app)/attendance/management/manual'
    | '/(app)/attendance/requests/new'
    | '/(app)/company/employee/$id'
    | '/(app)/company/employee/new'
    | '/(app)/company/employee/update'
    | '/(app)/company/organization/$id'
    | '/(app)/company/organization/new'
    | '/(app)/company/organization/update'
    | '/(app)/leave/approval/$requestId'
    | '/(app)/leave/requests/$requestId'
    | '/(app)/leave/requests/new'
    | '/(app)/settings/approval-workflow/matrix'
    | '/(app)/settings/approval-workflow/new'
    | '/(app)/settings/master-data/departments'
    | '/(app)/settings/master-data/divisions'
    | '/(app)/settings/master-data/grades'
    | '/(app)/settings/master-data/holidays'
    | '/(app)/settings/master-data/import'
    | '/(app)/settings/master-data/leave-types'
    | '/(app)/settings/master-data/payroll-components'
    | '/(app)/settings/master-data/positions'
    | '/(app)/settings/master-data/shifts'
    | '/(app)/settings/role-access/create-role'
    | '/(app)/settings/role-access/permission-matrix'
    | '/(app)/attendance/approval/'
    | '/(app)/attendance/calendar/'
    | '/(app)/attendance/management/'
    | '/(app)/attendance/requests/'
    | '/(app)/company/document/'
    | '/(app)/company/employee/'
    | '/(app)/company/organization/'
    | '/(app)/leave/approval/'
    | '/(app)/leave/requests/'
    | '/(app)/settings/approval-workflow/'
    | '/(app)/settings/company/'
    | '/(app)/settings/master-data/'
    | '/(app)/settings/notification/'
    | '/(app)/settings/role-access/'
    | '/(app)/settings/security/'
    | '/(app)/attendance/approval/$requestId/reject'
    | '/(app)/attendance/management/exceptions/$exceptionId'
    | '/(app)/attendance/management/shifts/assignments'
    | '/(app)/attendance/management/shifts/setup'
    | '/(app)/attendance/management/shifts/swaps'
    | '/(app)/settings/approval-workflow/$id/conditions'
    | '/(app)/settings/approval-workflow/$id/levels'
    | '/(app)/settings/approval-workflow/$id/test'
    | '/(app)/settings/role-access/$roleId/assign-users'
    | '/(app)/settings/role-access/$roleId/edit'
    | '/(app)/attendance/management/shifts/'
    | '/(app)/settings/approval-workflow/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authResetRoute: typeof authResetRoute
  authSigninRoute: typeof authSigninRoute
  authSignoutRoute: typeof authSignoutRoute
  authVerificationRoute: typeof authVerificationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset': {
      id: '/(auth)/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof authResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signout': {
      id: '/(auth)/signout'
      path: '/signout'
      fullPath: '/signout'
      preLoaderRoute: typeof authSignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verification': {
      id: '/(auth)/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof authVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(dashboard)/': {
      id: '/(app)/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appdashboardIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/approval/': {
      id: '/(app)/approval/'
      path: '/approval'
      fullPath: '/approval/'
      preLoaderRoute: typeof appApprovalIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/attendance/': {
      id: '/(app)/attendance/'
      path: '/attendance'
      fullPath: '/attendance/'
      preLoaderRoute: typeof appAttendanceIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/attendance/all-menu': {
      id: '/(app)/attendance/all-menu'
      path: '/attendance/all-menu'
      fullPath: '/attendance/all-menu'
      preLoaderRoute: typeof appAttendanceAllMenuRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/attendance/clock-in-out': {
      id: '/(app)/attendance/clock-in-out'
      path: '/attendance/clock-in-out'
      fullPath: '/attendance/clock-in-out'
      preLoaderRoute: typeof appAttendanceClockInOutRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/attendance/face-recognition': {
      id: '/(app)/attendance/face-recognition'
      path: '/attendance/face-recognition'
      fullPath: '/attendance/face-recognition'
      preLoaderRoute: typeof appAttendanceFaceRecognitionRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/attendance/gps-security': {
      id: '/(app)/attendance/gps-security'
      path: '/attendance/gps-security'
      fullPath: '/attendance/gps-security'
      preLoaderRoute: typeof appAttendanceGpsSecurityRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/attendance/history': {
      id: '/(app)/attendance/history'
      path: '/attendance/history'
      fullPath: '/attendance/history'
      preLoaderRoute: typeof appAttendanceHistoryRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/attendance/settings': {
      id: '/(app)/attendance/settings'
      path: '/attendance/settings'
      fullPath: '/attendance/settings'
      preLoaderRoute: typeof appAttendanceSettingsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/leave/': {
      id: '/(app)/leave/'
      path: '/leave'
      fullPath: '/leave/'
      preLoaderRoute: typeof appLeaveIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/leave/balance': {
      id: '/(app)/leave/balance'
      path: '/leave/balance'
      fullPath: '/leave/balance'
      preLoaderRoute: typeof appLeaveBalanceRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/leave/history': {
      id: '/(app)/leave/history'
      path: '/leave/history'
      fullPath: '/leave/history'
      preLoaderRoute: typeof appLeaveHistoryRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/payroll/': {
      id: '/(app)/payroll/'
      path: '/payroll'
      fullPath: '/payroll/'
      preLoaderRoute: typeof appPayrollIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/performance/': {
      id: '/(app)/performance/'
      path: '/performance'
      fullPath: '/performance/'
      preLoaderRoute: typeof appPerformanceIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/report/': {
      id: '/(app)/report/'
      path: '/report'
      fullPath: '/report/'
      preLoaderRoute: typeof appReportIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(dashboard)/dashboard/customize': {
      id: '/(app)/(dashboard)/dashboard/customize'
      path: '/dashboard/customize'
      fullPath: '/dashboard/customize'
      preLoaderRoute: typeof appdashboardDashboardCustomizeRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(dashboard)/dashboard/employee': {
      id: '/(app)/(dashboard)/dashboard/employee'
      path: '/dashboard/employee'
      fullPath: '/dashboard/employee'
      preLoaderRoute: typeof appdashboardDashboardEmployeeRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(dashboard)/dashboard/executive': {
      id: '/(app)/(dashboard)/dashboard/executive'
      path: '/dashboard/executive'
      fullPath: '/dashboard/executive'
      preLoaderRoute: typeof appdashboardDashboardExecutiveRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(dashboard)/dashboard/hr': {
      id: '/(app)/(dashboard)/dashboard/hr'
      path: '/dashboard/hr'
      fullPath: '/dashboard/hr'
      preLoaderRoute: typeof appdashboardDashboardHrRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(dashboard)/dashboard/manager': {
      id: '/(app)/(dashboard)/dashboard/manager'
      path: '/dashboard/manager'
      fullPath: '/dashboard/manager'
      preLoaderRoute: typeof appdashboardDashboardManagerRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/attendance/approval/': {
      id: '/(app)/attendance/approval/'
      path: '/attendance/approval'
      fullPath: '/attendance/approval/'
      preLoaderRoute: typeof appAttendanceApprovalIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/attendance/approval/$requestId': {
      id: '/(app)/attendance/approval/$requestId'
      path: '/attendance/approval/$requestId'
      fullPath: '/attendance/approval/$requestId'
      preLoaderRoute: typeof appAttendanceApprovalRequestIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/attendance/calendar/': {
      id: '/(app)/attendance/calendar/'
      path: '/attendance/calendar'
      fullPath: '/attendance/calendar/'
      preLoaderRoute: typeof appAttendanceCalendarIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/attendance/calendar/holidays': {
      id: '/(app)/attendance/calendar/holidays'
      path: '/attendance/calendar/holidays'
      fullPath: '/attendance/calendar/holidays'
      preLoaderRoute: typeof appAttendanceCalendarHolidaysRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/attendance/calendar/settings': {
      id: '/(app)/attendance/calendar/settings'
      path: '/attendance/calendar/settings'
      fullPath: '/attendance/calendar/settings'
      preLoaderRoute: typeof appAttendanceCalendarSettingsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/attendance/management/': {
      id: '/(app)/attendance/management/'
      path: '/attendance/management'
      fullPath: '/attendance/management/'
      preLoaderRoute: typeof appAttendanceManagementIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/attendance/management/manual': {
      id: '/(app)/attendance/management/manual'
      path: '/attendance/management/manual'
      fullPath: '/attendance/management/manual'
      preLoaderRoute: typeof appAttendanceManagementManualRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/attendance/requests/': {
      id: '/(app)/attendance/requests/'
      path: '/attendance/requests'
      fullPath: '/attendance/requests/'
      preLoaderRoute: typeof appAttendanceRequestsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/attendance/requests/new': {
      id: '/(app)/attendance/requests/new'
      path: '/attendance/requests/new'
      fullPath: '/attendance/requests/new'
      preLoaderRoute: typeof appAttendanceRequestsNewRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/company/document/': {
      id: '/(app)/company/document/'
      path: '/company/document'
      fullPath: '/company/document/'
      preLoaderRoute: typeof appCompanyDocumentIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/company/employee/': {
      id: '/(app)/company/employee/'
      path: '/company/employee'
      fullPath: '/company/employee/'
      preLoaderRoute: typeof appCompanyEmployeeIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/company/employee/$id': {
      id: '/(app)/company/employee/$id'
      path: '/company/employee/$id'
      fullPath: '/company/employee/$id'
      preLoaderRoute: typeof appCompanyEmployeeIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/company/employee/new': {
      id: '/(app)/company/employee/new'
      path: '/company/employee/new'
      fullPath: '/company/employee/new'
      preLoaderRoute: typeof appCompanyEmployeeNewRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/company/employee/update': {
      id: '/(app)/company/employee/update'
      path: '/company/employee/update'
      fullPath: '/company/employee/update'
      preLoaderRoute: typeof appCompanyEmployeeUpdateRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/company/organization/': {
      id: '/(app)/company/organization/'
      path: '/company/organization'
      fullPath: '/company/organization/'
      preLoaderRoute: typeof appCompanyOrganizationIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/company/organization/$id': {
      id: '/(app)/company/organization/$id'
      path: '/company/organization/$id'
      fullPath: '/company/organization/$id'
      preLoaderRoute: typeof appCompanyOrganizationIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/company/organization/new': {
      id: '/(app)/company/organization/new'
      path: '/company/organization/new'
      fullPath: '/company/organization/new'
      preLoaderRoute: typeof appCompanyOrganizationNewRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/company/organization/update': {
      id: '/(app)/company/organization/update'
      path: '/company/organization/update'
      fullPath: '/company/organization/update'
      preLoaderRoute: typeof appCompanyOrganizationUpdateRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/leave/approval/': {
      id: '/(app)/leave/approval/'
      path: '/leave/approval'
      fullPath: '/leave/approval/'
      preLoaderRoute: typeof appLeaveApprovalIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/leave/approval/$requestId': {
      id: '/(app)/leave/approval/$requestId'
      path: '/leave/approval/$requestId'
      fullPath: '/leave/approval/$requestId'
      preLoaderRoute: typeof appLeaveApprovalRequestIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/leave/requests/': {
      id: '/(app)/leave/requests/'
      path: '/leave/requests'
      fullPath: '/leave/requests/'
      preLoaderRoute: typeof appLeaveRequestsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/leave/requests/$requestId': {
      id: '/(app)/leave/requests/$requestId'
      path: '/leave/requests/$requestId'
      fullPath: '/leave/requests/$requestId'
      preLoaderRoute: typeof appLeaveRequestsRequestIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/leave/requests/new': {
      id: '/(app)/leave/requests/new'
      path: '/leave/requests/new'
      fullPath: '/leave/requests/new'
      preLoaderRoute: typeof appLeaveRequestsNewRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/approval-workflow/': {
      id: '/(app)/settings/approval-workflow/'
      path: '/settings/approval-workflow'
      fullPath: '/settings/approval-workflow/'
      preLoaderRoute: typeof appSettingsApprovalWorkflowIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/approval-workflow/matrix': {
      id: '/(app)/settings/approval-workflow/matrix'
      path: '/settings/approval-workflow/matrix'
      fullPath: '/settings/approval-workflow/matrix'
      preLoaderRoute: typeof appSettingsApprovalWorkflowMatrixRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/approval-workflow/new': {
      id: '/(app)/settings/approval-workflow/new'
      path: '/settings/approval-workflow/new'
      fullPath: '/settings/approval-workflow/new'
      preLoaderRoute: typeof appSettingsApprovalWorkflowNewRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/company/': {
      id: '/(app)/settings/company/'
      path: '/settings/company'
      fullPath: '/settings/company/'
      preLoaderRoute: typeof appSettingsCompanyIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/master-data/': {
      id: '/(app)/settings/master-data/'
      path: '/settings/master-data'
      fullPath: '/settings/master-data/'
      preLoaderRoute: typeof appSettingsMasterDataIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/master-data/departments': {
      id: '/(app)/settings/master-data/departments'
      path: '/settings/master-data/departments'
      fullPath: '/settings/master-data/departments'
      preLoaderRoute: typeof appSettingsMasterDataDepartmentsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/master-data/divisions': {
      id: '/(app)/settings/master-data/divisions'
      path: '/settings/master-data/divisions'
      fullPath: '/settings/master-data/divisions'
      preLoaderRoute: typeof appSettingsMasterDataDivisionsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/master-data/grades': {
      id: '/(app)/settings/master-data/grades'
      path: '/settings/master-data/grades'
      fullPath: '/settings/master-data/grades'
      preLoaderRoute: typeof appSettingsMasterDataGradesRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/master-data/holidays': {
      id: '/(app)/settings/master-data/holidays'
      path: '/settings/master-data/holidays'
      fullPath: '/settings/master-data/holidays'
      preLoaderRoute: typeof appSettingsMasterDataHolidaysRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/master-data/import': {
      id: '/(app)/settings/master-data/import'
      path: '/settings/master-data/import'
      fullPath: '/settings/master-data/import'
      preLoaderRoute: typeof appSettingsMasterDataImportRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/master-data/leave-types': {
      id: '/(app)/settings/master-data/leave-types'
      path: '/settings/master-data/leave-types'
      fullPath: '/settings/master-data/leave-types'
      preLoaderRoute: typeof appSettingsMasterDataLeaveTypesRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/master-data/payroll-components': {
      id: '/(app)/settings/master-data/payroll-components'
      path: '/settings/master-data/payroll-components'
      fullPath: '/settings/master-data/payroll-components'
      preLoaderRoute: typeof appSettingsMasterDataPayrollComponentsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/master-data/positions': {
      id: '/(app)/settings/master-data/positions'
      path: '/settings/master-data/positions'
      fullPath: '/settings/master-data/positions'
      preLoaderRoute: typeof appSettingsMasterDataPositionsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/master-data/shifts': {
      id: '/(app)/settings/master-data/shifts'
      path: '/settings/master-data/shifts'
      fullPath: '/settings/master-data/shifts'
      preLoaderRoute: typeof appSettingsMasterDataShiftsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/notification/': {
      id: '/(app)/settings/notification/'
      path: '/settings/notification'
      fullPath: '/settings/notification/'
      preLoaderRoute: typeof appSettingsNotificationIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/role-access/': {
      id: '/(app)/settings/role-access/'
      path: '/settings/role-access'
      fullPath: '/settings/role-access/'
      preLoaderRoute: typeof appSettingsRoleAccessIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/role-access/create-role': {
      id: '/(app)/settings/role-access/create-role'
      path: '/settings/role-access/create-role'
      fullPath: '/settings/role-access/create-role'
      preLoaderRoute: typeof appSettingsRoleAccessCreateRoleRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/role-access/permission-matrix': {
      id: '/(app)/settings/role-access/permission-matrix'
      path: '/settings/role-access/permission-matrix'
      fullPath: '/settings/role-access/permission-matrix'
      preLoaderRoute: typeof appSettingsRoleAccessPermissionMatrixRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/security/': {
      id: '/(app)/settings/security/'
      path: '/settings/security'
      fullPath: '/settings/security/'
      preLoaderRoute: typeof appSettingsSecurityIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/attendance/approval/$requestId/reject': {
      id: '/(app)/attendance/approval/$requestId/reject'
      path: '/reject'
      fullPath: '/attendance/approval/$requestId/reject'
      preLoaderRoute: typeof appAttendanceApprovalRequestIdRejectRouteImport
      parentRoute: typeof appAttendanceApprovalRequestIdRoute
    }
    '/(app)/attendance/management/exceptions/$exceptionId': {
      id: '/(app)/attendance/management/exceptions/$exceptionId'
      path: '/attendance/management/exceptions/$exceptionId'
      fullPath: '/attendance/management/exceptions/$exceptionId'
      preLoaderRoute: typeof appAttendanceManagementExceptionsExceptionIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/attendance/management/shifts/': {
      id: '/(app)/attendance/management/shifts/'
      path: '/attendance/management/shifts'
      fullPath: '/attendance/management/shifts/'
      preLoaderRoute: typeof appAttendanceManagementShiftsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/attendance/management/shifts/assignments': {
      id: '/(app)/attendance/management/shifts/assignments'
      path: '/attendance/management/shifts/assignments'
      fullPath: '/attendance/management/shifts/assignments'
      preLoaderRoute: typeof appAttendanceManagementShiftsAssignmentsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/attendance/management/shifts/setup': {
      id: '/(app)/attendance/management/shifts/setup'
      path: '/attendance/management/shifts/setup'
      fullPath: '/attendance/management/shifts/setup'
      preLoaderRoute: typeof appAttendanceManagementShiftsSetupRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/attendance/management/shifts/swaps': {
      id: '/(app)/attendance/management/shifts/swaps'
      path: '/attendance/management/shifts/swaps'
      fullPath: '/attendance/management/shifts/swaps'
      preLoaderRoute: typeof appAttendanceManagementShiftsSwapsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/approval-workflow/$id/': {
      id: '/(app)/settings/approval-workflow/$id/'
      path: '/settings/approval-workflow/$id'
      fullPath: '/settings/approval-workflow/$id/'
      preLoaderRoute: typeof appSettingsApprovalWorkflowIdIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/approval-workflow/$id/conditions': {
      id: '/(app)/settings/approval-workflow/$id/conditions'
      path: '/settings/approval-workflow/$id/conditions'
      fullPath: '/settings/approval-workflow/$id/conditions'
      preLoaderRoute: typeof appSettingsApprovalWorkflowIdConditionsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/approval-workflow/$id/levels': {
      id: '/(app)/settings/approval-workflow/$id/levels'
      path: '/settings/approval-workflow/$id/levels'
      fullPath: '/settings/approval-workflow/$id/levels'
      preLoaderRoute: typeof appSettingsApprovalWorkflowIdLevelsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/approval-workflow/$id/test': {
      id: '/(app)/settings/approval-workflow/$id/test'
      path: '/settings/approval-workflow/$id/test'
      fullPath: '/settings/approval-workflow/$id/test'
      preLoaderRoute: typeof appSettingsApprovalWorkflowIdTestRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/role-access/$roleId/assign-users': {
      id: '/(app)/settings/role-access/$roleId/assign-users'
      path: '/settings/role-access/$roleId/assign-users'
      fullPath: '/settings/role-access/$roleId/assign-users'
      preLoaderRoute: typeof appSettingsRoleAccessRoleIdAssignUsersRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/role-access/$roleId/edit': {
      id: '/(app)/settings/role-access/$roleId/edit'
      path: '/settings/role-access/$roleId/edit'
      fullPath: '/settings/role-access/$roleId/edit'
      preLoaderRoute: typeof appSettingsRoleAccessRoleIdEditRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appAttendanceApprovalRequestIdRouteChildren {
  appAttendanceApprovalRequestIdRejectRoute: typeof appAttendanceApprovalRequestIdRejectRoute
}

const appAttendanceApprovalRequestIdRouteChildren: appAttendanceApprovalRequestIdRouteChildren =
  {
    appAttendanceApprovalRequestIdRejectRoute:
      appAttendanceApprovalRequestIdRejectRoute,
  }

const appAttendanceApprovalRequestIdRouteWithChildren =
  appAttendanceApprovalRequestIdRoute._addFileChildren(
    appAttendanceApprovalRequestIdRouteChildren,
  )

interface appRouteRouteChildren {
  appAttendanceAllMenuRoute: typeof appAttendanceAllMenuRoute
  appAttendanceClockInOutRoute: typeof appAttendanceClockInOutRoute
  appAttendanceFaceRecognitionRoute: typeof appAttendanceFaceRecognitionRoute
  appAttendanceGpsSecurityRoute: typeof appAttendanceGpsSecurityRoute
  appAttendanceHistoryRoute: typeof appAttendanceHistoryRoute
  appAttendanceSettingsRoute: typeof appAttendanceSettingsRoute
  appLeaveBalanceRoute: typeof appLeaveBalanceRoute
  appLeaveHistoryRoute: typeof appLeaveHistoryRoute
  appdashboardIndexRoute: typeof appdashboardIndexRoute
  appApprovalIndexRoute: typeof appApprovalIndexRoute
  appAttendanceIndexRoute: typeof appAttendanceIndexRoute
  appLeaveIndexRoute: typeof appLeaveIndexRoute
  appPayrollIndexRoute: typeof appPayrollIndexRoute
  appPerformanceIndexRoute: typeof appPerformanceIndexRoute
  appReportIndexRoute: typeof appReportIndexRoute
  appdashboardDashboardCustomizeRoute: typeof appdashboardDashboardCustomizeRoute
  appdashboardDashboardEmployeeRoute: typeof appdashboardDashboardEmployeeRoute
  appdashboardDashboardExecutiveRoute: typeof appdashboardDashboardExecutiveRoute
  appdashboardDashboardHrRoute: typeof appdashboardDashboardHrRoute
  appdashboardDashboardManagerRoute: typeof appdashboardDashboardManagerRoute
  appAttendanceApprovalRequestIdRoute: typeof appAttendanceApprovalRequestIdRouteWithChildren
  appAttendanceCalendarHolidaysRoute: typeof appAttendanceCalendarHolidaysRoute
  appAttendanceCalendarSettingsRoute: typeof appAttendanceCalendarSettingsRoute
  appAttendanceManagementManualRoute: typeof appAttendanceManagementManualRoute
  appAttendanceRequestsNewRoute: typeof appAttendanceRequestsNewRoute
  appCompanyEmployeeIdRoute: typeof appCompanyEmployeeIdRoute
  appCompanyEmployeeNewRoute: typeof appCompanyEmployeeNewRoute
  appCompanyEmployeeUpdateRoute: typeof appCompanyEmployeeUpdateRoute
  appCompanyOrganizationIdRoute: typeof appCompanyOrganizationIdRoute
  appCompanyOrganizationNewRoute: typeof appCompanyOrganizationNewRoute
  appCompanyOrganizationUpdateRoute: typeof appCompanyOrganizationUpdateRoute
  appLeaveApprovalRequestIdRoute: typeof appLeaveApprovalRequestIdRoute
  appLeaveRequestsRequestIdRoute: typeof appLeaveRequestsRequestIdRoute
  appLeaveRequestsNewRoute: typeof appLeaveRequestsNewRoute
  appSettingsApprovalWorkflowMatrixRoute: typeof appSettingsApprovalWorkflowMatrixRoute
  appSettingsApprovalWorkflowNewRoute: typeof appSettingsApprovalWorkflowNewRoute
  appSettingsMasterDataDepartmentsRoute: typeof appSettingsMasterDataDepartmentsRoute
  appSettingsMasterDataDivisionsRoute: typeof appSettingsMasterDataDivisionsRoute
  appSettingsMasterDataGradesRoute: typeof appSettingsMasterDataGradesRoute
  appSettingsMasterDataHolidaysRoute: typeof appSettingsMasterDataHolidaysRoute
  appSettingsMasterDataImportRoute: typeof appSettingsMasterDataImportRoute
  appSettingsMasterDataLeaveTypesRoute: typeof appSettingsMasterDataLeaveTypesRoute
  appSettingsMasterDataPayrollComponentsRoute: typeof appSettingsMasterDataPayrollComponentsRoute
  appSettingsMasterDataPositionsRoute: typeof appSettingsMasterDataPositionsRoute
  appSettingsMasterDataShiftsRoute: typeof appSettingsMasterDataShiftsRoute
  appSettingsRoleAccessCreateRoleRoute: typeof appSettingsRoleAccessCreateRoleRoute
  appSettingsRoleAccessPermissionMatrixRoute: typeof appSettingsRoleAccessPermissionMatrixRoute
  appAttendanceApprovalIndexRoute: typeof appAttendanceApprovalIndexRoute
  appAttendanceCalendarIndexRoute: typeof appAttendanceCalendarIndexRoute
  appAttendanceManagementIndexRoute: typeof appAttendanceManagementIndexRoute
  appAttendanceRequestsIndexRoute: typeof appAttendanceRequestsIndexRoute
  appCompanyDocumentIndexRoute: typeof appCompanyDocumentIndexRoute
  appCompanyEmployeeIndexRoute: typeof appCompanyEmployeeIndexRoute
  appCompanyOrganizationIndexRoute: typeof appCompanyOrganizationIndexRoute
  appLeaveApprovalIndexRoute: typeof appLeaveApprovalIndexRoute
  appLeaveRequestsIndexRoute: typeof appLeaveRequestsIndexRoute
  appSettingsApprovalWorkflowIndexRoute: typeof appSettingsApprovalWorkflowIndexRoute
  appSettingsCompanyIndexRoute: typeof appSettingsCompanyIndexRoute
  appSettingsMasterDataIndexRoute: typeof appSettingsMasterDataIndexRoute
  appSettingsNotificationIndexRoute: typeof appSettingsNotificationIndexRoute
  appSettingsRoleAccessIndexRoute: typeof appSettingsRoleAccessIndexRoute
  appSettingsSecurityIndexRoute: typeof appSettingsSecurityIndexRoute
  appAttendanceManagementExceptionsExceptionIdRoute: typeof appAttendanceManagementExceptionsExceptionIdRoute
  appAttendanceManagementShiftsAssignmentsRoute: typeof appAttendanceManagementShiftsAssignmentsRoute
  appAttendanceManagementShiftsSetupRoute: typeof appAttendanceManagementShiftsSetupRoute
  appAttendanceManagementShiftsSwapsRoute: typeof appAttendanceManagementShiftsSwapsRoute
  appSettingsApprovalWorkflowIdConditionsRoute: typeof appSettingsApprovalWorkflowIdConditionsRoute
  appSettingsApprovalWorkflowIdLevelsRoute: typeof appSettingsApprovalWorkflowIdLevelsRoute
  appSettingsApprovalWorkflowIdTestRoute: typeof appSettingsApprovalWorkflowIdTestRoute
  appSettingsRoleAccessRoleIdAssignUsersRoute: typeof appSettingsRoleAccessRoleIdAssignUsersRoute
  appSettingsRoleAccessRoleIdEditRoute: typeof appSettingsRoleAccessRoleIdEditRoute
  appAttendanceManagementShiftsIndexRoute: typeof appAttendanceManagementShiftsIndexRoute
  appSettingsApprovalWorkflowIdIndexRoute: typeof appSettingsApprovalWorkflowIdIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appAttendanceAllMenuRoute: appAttendanceAllMenuRoute,
  appAttendanceClockInOutRoute: appAttendanceClockInOutRoute,
  appAttendanceFaceRecognitionRoute: appAttendanceFaceRecognitionRoute,
  appAttendanceGpsSecurityRoute: appAttendanceGpsSecurityRoute,
  appAttendanceHistoryRoute: appAttendanceHistoryRoute,
  appAttendanceSettingsRoute: appAttendanceSettingsRoute,
  appLeaveBalanceRoute: appLeaveBalanceRoute,
  appLeaveHistoryRoute: appLeaveHistoryRoute,
  appdashboardIndexRoute: appdashboardIndexRoute,
  appApprovalIndexRoute: appApprovalIndexRoute,
  appAttendanceIndexRoute: appAttendanceIndexRoute,
  appLeaveIndexRoute: appLeaveIndexRoute,
  appPayrollIndexRoute: appPayrollIndexRoute,
  appPerformanceIndexRoute: appPerformanceIndexRoute,
  appReportIndexRoute: appReportIndexRoute,
  appdashboardDashboardCustomizeRoute: appdashboardDashboardCustomizeRoute,
  appdashboardDashboardEmployeeRoute: appdashboardDashboardEmployeeRoute,
  appdashboardDashboardExecutiveRoute: appdashboardDashboardExecutiveRoute,
  appdashboardDashboardHrRoute: appdashboardDashboardHrRoute,
  appdashboardDashboardManagerRoute: appdashboardDashboardManagerRoute,
  appAttendanceApprovalRequestIdRoute:
    appAttendanceApprovalRequestIdRouteWithChildren,
  appAttendanceCalendarHolidaysRoute: appAttendanceCalendarHolidaysRoute,
  appAttendanceCalendarSettingsRoute: appAttendanceCalendarSettingsRoute,
  appAttendanceManagementManualRoute: appAttendanceManagementManualRoute,
  appAttendanceRequestsNewRoute: appAttendanceRequestsNewRoute,
  appCompanyEmployeeIdRoute: appCompanyEmployeeIdRoute,
  appCompanyEmployeeNewRoute: appCompanyEmployeeNewRoute,
  appCompanyEmployeeUpdateRoute: appCompanyEmployeeUpdateRoute,
  appCompanyOrganizationIdRoute: appCompanyOrganizationIdRoute,
  appCompanyOrganizationNewRoute: appCompanyOrganizationNewRoute,
  appCompanyOrganizationUpdateRoute: appCompanyOrganizationUpdateRoute,
  appLeaveApprovalRequestIdRoute: appLeaveApprovalRequestIdRoute,
  appLeaveRequestsRequestIdRoute: appLeaveRequestsRequestIdRoute,
  appLeaveRequestsNewRoute: appLeaveRequestsNewRoute,
  appSettingsApprovalWorkflowMatrixRoute:
    appSettingsApprovalWorkflowMatrixRoute,
  appSettingsApprovalWorkflowNewRoute: appSettingsApprovalWorkflowNewRoute,
  appSettingsMasterDataDepartmentsRoute: appSettingsMasterDataDepartmentsRoute,
  appSettingsMasterDataDivisionsRoute: appSettingsMasterDataDivisionsRoute,
  appSettingsMasterDataGradesRoute: appSettingsMasterDataGradesRoute,
  appSettingsMasterDataHolidaysRoute: appSettingsMasterDataHolidaysRoute,
  appSettingsMasterDataImportRoute: appSettingsMasterDataImportRoute,
  appSettingsMasterDataLeaveTypesRoute: appSettingsMasterDataLeaveTypesRoute,
  appSettingsMasterDataPayrollComponentsRoute:
    appSettingsMasterDataPayrollComponentsRoute,
  appSettingsMasterDataPositionsRoute: appSettingsMasterDataPositionsRoute,
  appSettingsMasterDataShiftsRoute: appSettingsMasterDataShiftsRoute,
  appSettingsRoleAccessCreateRoleRoute: appSettingsRoleAccessCreateRoleRoute,
  appSettingsRoleAccessPermissionMatrixRoute:
    appSettingsRoleAccessPermissionMatrixRoute,
  appAttendanceApprovalIndexRoute: appAttendanceApprovalIndexRoute,
  appAttendanceCalendarIndexRoute: appAttendanceCalendarIndexRoute,
  appAttendanceManagementIndexRoute: appAttendanceManagementIndexRoute,
  appAttendanceRequestsIndexRoute: appAttendanceRequestsIndexRoute,
  appCompanyDocumentIndexRoute: appCompanyDocumentIndexRoute,
  appCompanyEmployeeIndexRoute: appCompanyEmployeeIndexRoute,
  appCompanyOrganizationIndexRoute: appCompanyOrganizationIndexRoute,
  appLeaveApprovalIndexRoute: appLeaveApprovalIndexRoute,
  appLeaveRequestsIndexRoute: appLeaveRequestsIndexRoute,
  appSettingsApprovalWorkflowIndexRoute: appSettingsApprovalWorkflowIndexRoute,
  appSettingsCompanyIndexRoute: appSettingsCompanyIndexRoute,
  appSettingsMasterDataIndexRoute: appSettingsMasterDataIndexRoute,
  appSettingsNotificationIndexRoute: appSettingsNotificationIndexRoute,
  appSettingsRoleAccessIndexRoute: appSettingsRoleAccessIndexRoute,
  appSettingsSecurityIndexRoute: appSettingsSecurityIndexRoute,
  appAttendanceManagementExceptionsExceptionIdRoute:
    appAttendanceManagementExceptionsExceptionIdRoute,
  appAttendanceManagementShiftsAssignmentsRoute:
    appAttendanceManagementShiftsAssignmentsRoute,
  appAttendanceManagementShiftsSetupRoute:
    appAttendanceManagementShiftsSetupRoute,
  appAttendanceManagementShiftsSwapsRoute:
    appAttendanceManagementShiftsSwapsRoute,
  appSettingsApprovalWorkflowIdConditionsRoute:
    appSettingsApprovalWorkflowIdConditionsRoute,
  appSettingsApprovalWorkflowIdLevelsRoute:
    appSettingsApprovalWorkflowIdLevelsRoute,
  appSettingsApprovalWorkflowIdTestRoute:
    appSettingsApprovalWorkflowIdTestRoute,
  appSettingsRoleAccessRoleIdAssignUsersRoute:
    appSettingsRoleAccessRoleIdAssignUsersRoute,
  appSettingsRoleAccessRoleIdEditRoute: appSettingsRoleAccessRoleIdEditRoute,
  appAttendanceManagementShiftsIndexRoute:
    appAttendanceManagementShiftsIndexRoute,
  appSettingsApprovalWorkflowIdIndexRoute:
    appSettingsApprovalWorkflowIdIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authResetRoute: authResetRoute,
  authSigninRoute: authSigninRoute,
  authSignoutRoute: authSignoutRoute,
  authVerificationRoute: authVerificationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
