/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as authSigninRouteImport } from './routes/(auth)/signin'
import { Route as authSignoutRouteImport } from './routes/(auth)/signout'
import { Route as appdashboardIndexRouteImport } from './routes/(app)/(dashboard)/index'
import { Route as appdashboardEmployeeDashboardRouteImport } from './routes/(app)/(dashboard)/employee-dashboard'
import { Route as appdashboardExecutiveDashboardRouteImport } from './routes/(app)/(dashboard)/executive-dashboard'
import { Route as appdashboardManagerDashboardRouteImport } from './routes/(app)/(dashboard)/manager-dashboard'
import { Route as appAttendanceIndexRouteImport } from './routes/(app)/attendance/index'
import { Route as appEmployeeIndexRouteImport } from './routes/(app)/employee/index'
import { Route as appLeaveIndexRouteImport } from './routes/(app)/leave/index'
import { Route as appPayrollIndexRouteImport } from './routes/(app)/payroll/index'
import { Route as appPerformanceIndexRouteImport } from './routes/(app)/performance/index'
import { Route as appReportIndexRouteImport } from './routes/(app)/report/index'
import { Route as appSettingsIndexRouteImport } from './routes/(app)/settings/index'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const authSigninRoute = authSigninRouteImport.update({
  id: '/(auth)/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignoutRoute = authSignoutRouteImport.update({
  id: '/(auth)/signout',
  path: '/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const appdashboardIndexRoute = appdashboardIndexRouteImport.update({
  id: '/(dashboard)/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const appdashboardEmployeeDashboardRoute =
  appdashboardEmployeeDashboardRouteImport.update({
    id: '/(dashboard)/employee-dashboard',
    path: '/employee-dashboard',
    getParentRoute: () => appRouteRoute,
  } as any)
const appdashboardExecutiveDashboardRoute =
  appdashboardExecutiveDashboardRouteImport.update({
    id: '/(dashboard)/executive-dashboard',
    path: '/executive-dashboard',
    getParentRoute: () => appRouteRoute,
  } as any)
const appdashboardManagerDashboardRoute =
  appdashboardManagerDashboardRouteImport.update({
    id: '/(dashboard)/manager-dashboard',
    path: '/manager-dashboard',
    getParentRoute: () => appRouteRoute,
  } as any)
const appAttendanceIndexRoute = appAttendanceIndexRouteImport.update({
  id: '/attendance/',
  path: '/attendance/',
  getParentRoute: () => appRouteRoute,
} as any)
const appEmployeeIndexRoute = appEmployeeIndexRouteImport.update({
  id: '/employee/',
  path: '/employee/',
  getParentRoute: () => appRouteRoute,
} as any)
const appLeaveIndexRoute = appLeaveIndexRouteImport.update({
  id: '/leave/',
  path: '/leave/',
  getParentRoute: () => appRouteRoute,
} as any)
const appPayrollIndexRoute = appPayrollIndexRouteImport.update({
  id: '/payroll/',
  path: '/payroll/',
  getParentRoute: () => appRouteRoute,
} as any)
const appPerformanceIndexRoute = appPerformanceIndexRouteImport.update({
  id: '/performance/',
  path: '/performance/',
  getParentRoute: () => appRouteRoute,
} as any)
const appReportIndexRoute = appReportIndexRouteImport.update({
  id: '/report/',
  path: '/report/',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsIndexRoute = appSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/signin': typeof authSigninRoute
  '/signout': typeof authSignoutRoute
  '/employee-dashboard': typeof appdashboardEmployeeDashboardRoute
  '/executive-dashboard': typeof appdashboardExecutiveDashboardRoute
  '/manager-dashboard': typeof appdashboardManagerDashboardRoute
  '/': typeof appdashboardIndexRoute
  '/attendance/': typeof appAttendanceIndexRoute
  '/employee/': typeof appEmployeeIndexRoute
  '/leave/': typeof appLeaveIndexRoute
  '/payroll/': typeof appPayrollIndexRoute
  '/performance/': typeof appPerformanceIndexRoute
  '/report/': typeof appReportIndexRoute
  '/settings/': typeof appSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/signin': typeof authSigninRoute
  '/signout': typeof authSignoutRoute
  '/employee-dashboard': typeof appdashboardEmployeeDashboardRoute
  '/executive-dashboard': typeof appdashboardExecutiveDashboardRoute
  '/manager-dashboard': typeof appdashboardManagerDashboardRoute
  '/': typeof appdashboardIndexRoute
  '/attendance': typeof appAttendanceIndexRoute
  '/employee': typeof appEmployeeIndexRoute
  '/leave': typeof appLeaveIndexRoute
  '/payroll': typeof appPayrollIndexRoute
  '/performance': typeof appPerformanceIndexRoute
  '/report': typeof appReportIndexRoute
  '/settings': typeof appSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)/signin': typeof authSigninRoute
  '/(auth)/signout': typeof authSignoutRoute
  '/(app)/(dashboard)/employee-dashboard': typeof appdashboardEmployeeDashboardRoute
  '/(app)/(dashboard)/executive-dashboard': typeof appdashboardExecutiveDashboardRoute
  '/(app)/(dashboard)/manager-dashboard': typeof appdashboardManagerDashboardRoute
  '/(app)/(dashboard)/': typeof appdashboardIndexRoute
  '/(app)/attendance/': typeof appAttendanceIndexRoute
  '/(app)/employee/': typeof appEmployeeIndexRoute
  '/(app)/leave/': typeof appLeaveIndexRoute
  '/(app)/payroll/': typeof appPayrollIndexRoute
  '/(app)/performance/': typeof appPerformanceIndexRoute
  '/(app)/report/': typeof appReportIndexRoute
  '/(app)/settings/': typeof appSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/signin'
    | '/signout'
    | '/employee-dashboard'
    | '/executive-dashboard'
    | '/manager-dashboard'
    | '/'
    | '/attendance/'
    | '/employee/'
    | '/leave/'
    | '/payroll/'
    | '/performance/'
    | '/report/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/signin'
    | '/signout'
    | '/employee-dashboard'
    | '/executive-dashboard'
    | '/manager-dashboard'
    | '/'
    | '/attendance'
    | '/employee'
    | '/leave'
    | '/payroll'
    | '/performance'
    | '/report'
    | '/settings'
  id:
    | '__root__'
    | '/(app)'
    | '/(auth)/signin'
    | '/(auth)/signout'
    | '/(app)/(dashboard)/employee-dashboard'
    | '/(app)/(dashboard)/executive-dashboard'
    | '/(app)/(dashboard)/manager-dashboard'
    | '/(app)/(dashboard)/'
    | '/(app)/attendance/'
    | '/(app)/employee/'
    | '/(app)/leave/'
    | '/(app)/payroll/'
    | '/(app)/performance/'
    | '/(app)/report/'
    | '/(app)/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authSigninRoute: typeof authSigninRoute
  authSignoutRoute: typeof authSignoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signout': {
      id: '/(auth)/signout'
      path: '/signout'
      fullPath: '/signout'
      preLoaderRoute: typeof authSignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(dashboard)/': {
      id: '/(app)/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appdashboardIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(dashboard)/employee-dashboard': {
      id: '/(app)/(dashboard)/employee-dashboard'
      path: '/employee-dashboard'
      fullPath: '/employee-dashboard'
      preLoaderRoute: typeof appdashboardEmployeeDashboardRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(dashboard)/executive-dashboard': {
      id: '/(app)/(dashboard)/executive-dashboard'
      path: '/executive-dashboard'
      fullPath: '/executive-dashboard'
      preLoaderRoute: typeof appdashboardExecutiveDashboardRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(dashboard)/manager-dashboard': {
      id: '/(app)/(dashboard)/manager-dashboard'
      path: '/manager-dashboard'
      fullPath: '/manager-dashboard'
      preLoaderRoute: typeof appdashboardManagerDashboardRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/attendance/': {
      id: '/(app)/attendance/'
      path: '/attendance'
      fullPath: '/attendance/'
      preLoaderRoute: typeof appAttendanceIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/employee/': {
      id: '/(app)/employee/'
      path: '/employee'
      fullPath: '/employee/'
      preLoaderRoute: typeof appEmployeeIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/leave/': {
      id: '/(app)/leave/'
      path: '/leave'
      fullPath: '/leave/'
      preLoaderRoute: typeof appLeaveIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/payroll/': {
      id: '/(app)/payroll/'
      path: '/payroll'
      fullPath: '/payroll/'
      preLoaderRoute: typeof appPayrollIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/performance/': {
      id: '/(app)/performance/'
      path: '/performance'
      fullPath: '/performance/'
      preLoaderRoute: typeof appPerformanceIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/report/': {
      id: '/(app)/report/'
      path: '/report'
      fullPath: '/report/'
      preLoaderRoute: typeof appReportIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/': {
      id: '/(app)/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof appSettingsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appdashboardEmployeeDashboardRoute: typeof appdashboardEmployeeDashboardRoute
  appdashboardExecutiveDashboardRoute: typeof appdashboardExecutiveDashboardRoute
  appdashboardManagerDashboardRoute: typeof appdashboardManagerDashboardRoute
  appdashboardIndexRoute: typeof appdashboardIndexRoute
  appAttendanceIndexRoute: typeof appAttendanceIndexRoute
  appEmployeeIndexRoute: typeof appEmployeeIndexRoute
  appLeaveIndexRoute: typeof appLeaveIndexRoute
  appPayrollIndexRoute: typeof appPayrollIndexRoute
  appPerformanceIndexRoute: typeof appPerformanceIndexRoute
  appReportIndexRoute: typeof appReportIndexRoute
  appSettingsIndexRoute: typeof appSettingsIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appdashboardEmployeeDashboardRoute: appdashboardEmployeeDashboardRoute,
  appdashboardExecutiveDashboardRoute: appdashboardExecutiveDashboardRoute,
  appdashboardManagerDashboardRoute: appdashboardManagerDashboardRoute,
  appdashboardIndexRoute: appdashboardIndexRoute,
  appAttendanceIndexRoute: appAttendanceIndexRoute,
  appEmployeeIndexRoute: appEmployeeIndexRoute,
  appLeaveIndexRoute: appLeaveIndexRoute,
  appPayrollIndexRoute: appPayrollIndexRoute,
  appPerformanceIndexRoute: appPerformanceIndexRoute,
  appReportIndexRoute: appReportIndexRoute,
  appSettingsIndexRoute: appSettingsIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authSigninRoute: authSigninRoute,
  authSignoutRoute: authSignoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
